### ISSUE TITLE
Peptide-shaker bug (decoys?)

### ISSUE THREAD

**Issue by rosshartman** [compomics/peptide-shaker#103]
I keep getting the following error report, any help would be greatly appreciated.  This seems to be a new problem with the 1.2.2 version of peptide shaker or perhaps with the latest version of searchgui

Here is the full report.
Thanks,
Ross

Mon Dec 21 17:01:47 MST 2015: PeptideShaker version 1.2.2.
Memory given to the Java virtual machine: 3817865216.
Total amount of memory in the Java virtual machine: 163053568.
Free memory: 129224752.
Java version: 1.8.0_60.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.8.0_60
os.name: Windows 7
memory: 49.3/163.1
processors available: 8
useCommandThread: false
<CompomicsError>PeptideShaker processing failed. See the PeptideShaker log for details.</CompomicsError>
java.lang.NullPointerException
	at eu.isas.peptideshaker.scoring.targetdecoy.TargetDecoySeries.<init>(TargetDecoySeries.java:141)
	at eu.isas.peptideshaker.scoring.targetdecoy.TargetDecoyMap.getTargetDecoySeries(TargetDecoyMap.java:416)
	at eu.isas.peptideshaker.validation.MatchesValidator.validateIdentifications(MatchesValidator.java:202)
	at eu.isas.peptideshaker.PeptideShaker.processIdentifications(PeptideShaker.java:460)
	at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importFiles(FileImporter.java:553)
	at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.doInBackground(FileImporter.java:438)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Free memory: 148033392

**Comment by mvaudel** [comment]
Hi and thank you for reporting this issue. Would it be possible for you to
share the data with us so that we can reproduce the error on our side?

Best regards,

Marc

2015-12-22 18:44 GMT+01:00 rosshartman <notifications@github.com>:

**Comment by rosshartman** [comment]
Sure,

I played with the program some more and it seems like it is trying to load the wrong database from the searchgui output .zip.   Instead of loading the decoy database that I used for the search it reverts to the original database.   If I manually select the correct database file when loading the new project it seems to work fine.


I've attached the datafile, and output file, as well as the database files (with and without decoys).  Let me know if you need any more information to fix the bug.


Ross


________________________________

**Comment by hbarsnes** [comment]
Issue assumed resolved in later PeptideShaker versions. If this is not the case, please let us know and we'll reopen the issue.
