### ISSUE TITLE
PSM import timed out

### ISSUE THREAD

**Issue by copyymk** [compomics/peptide-shaker#119]
Hi, Pfr
I used peptideshaker-1.4.0 on linux, but something wrong, could you help me?
File from X!Tandem: "R15153_1_A1.t.xml", ~165Mb
database: ~285Mb (target+decoy)
Error: stop at "Importing PSMs from..." this step every time, why? If the result file (.xml) is too large? By the way, i used java with "-Xmx10000M".
Thanks!

Error info:
java.lang.InterruptedException: PSM import timed out. Please contact the developers.   
        at eu.isas.peptideshaker.fileimport.PsmImporter.importPsmsMultipleThreads(PsmImporter.java:295)
        at eu.isas.peptideshaker.fileimport.PsmImporter.importPsms(PsmImporter.java:257)
        at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importPsms(FileImporter.java:778)
        at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importFiles(FileImporter.java:482)
        at eu.isas.peptideshaker.fileimport.FileImporter.importFiles(FileImporter.java:158)
        at eu.isas.peptideshaker.PeptideShaker.importFiles(PeptideShaker.java:232)
        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.createProject(PeptideShakerCLI.java:684)
        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:203)  
        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:896)
Free memory: 3307741560
Thu Jan 21 12:34:47 CST 2016 PeptideShaker Processing Canceled.
<CompomicsError>PeptideShaker processing canceled. See the PeptideShaker log for details.</CompomicsError>

**Comment by hbarsnes** [comment]
Hi.

The timeout is set to one day, so this should not happen often. And especially not for files as small as the ones you are processing. When it does happen it is usually because the search result file(s), the mgf file(s) or the FASTA file is at a location that cannot be reached, for example on a shared drive. Is this the case in your setup?

Best regards,
Harald

**Comment by hbarsnes** [comment]
(Issue assumed fixed. If this is not the case, please let us know and we'll reopen the issue.)
