### ISSUE TITLE
Peptideshaker hangs while importing

### ISSUE THREAD

**Issue by somakray** [compomics/peptide-shaker#122]
I'm getting the following error, and eventually it hangs at 30% progress while importing running on Ubuntu 14.04
<code>
Sun Jan 24 20:36:21 EST 2016 Import process for myExp (Sample: mySamp, Replicate: 1)

Sun Jan 24 20:36:22 EST 2016 Importing sequences from SIMION.CHOwRT_NoRed_FixHeader_concatenated_target_decoy.fasta.
java.lang.IllegalArgumentException: Database import was not successfully completed. Database will be reindexed.
	at com.compomics.util.experiment.identification.protein_inference.proteintree.ProteinTree.initiateTree(ProteinTree.java:257)
	at com.compomics.util.experiment.identification.protein_inference.proteintree.ProteinTree.initiateTree(ProteinTree.java:204)
	at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.getDefaultProteinTree(SequenceFactory.java:1411)
	at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.getDefaultProteinTree(SequenceFactory.java:1346)
	at eu.isas.peptideshaker.fileimport.FileImporter.importSequences(FileImporter.java:211)
	at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importFiles(FileImporter.java:449)
	at eu.isas.peptideshaker.fileimport.FileImporter.importFiles(FileImporter.java:158)
	at eu.isas.peptideshaker.PeptideShaker.importFiles(PeptideShaker.java:232)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.createProject(PeptideShakerCLI.java:684)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:203)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:896)
java.sql.SQLNonTransientConnectionException: No current connection.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.noCurrentConnection(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkIfClosed(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.createStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.createStatement(Unknown Source)
	at com.compomics.util.db.ObjectsDB.retrieveObjectSynchronized(ObjectsDB.java:794)
	at com.compomics.util.db.ObjectsDB.retrieveObject(ObjectsDB.java:746)
	at com.compomics.util.db.ObjectsDB.retrieveObject(ObjectsDB.java:708)
	at com.compomics.util.experiment.identification.protein_inference.proteintree.ProteinTreeComponentsFactory.isCorrupted(ProteinTreeComponentsFactory.java:366)
	at com.compomics.util.experiment.identification.protein_inference.proteintree.ProteinTreeComponentsFactory.delete(ProteinTreeComponentsFactory.java:141)
	at com.compomics.util.experiment.identification.protein_inference.proteintree.ProteinTree.initiateTree(ProteinTree.java:271)
	at com.compomics.util.experiment.identification.protein_inference.proteintree.ProteinTree.initiateTree(ProteinTree.java:204)
	at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.getDefaultProteinTree(SequenceFactory.java:1411)
	at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.getDefaultProteinTree(SequenceFactory.java:1346)
	at eu.isas.peptideshaker.fileimport.FileImporter.importSequences(FileImporter.java:211)
	at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importFiles(FileImporter.java:449)
	at eu.isas.peptideshaker.fileimport.FileImporter.importFiles(FileImporter.java:158)
	at eu.isas.peptideshaker.PeptideShaker.importFiles(PeptideShaker.java:232)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.createProject(PeptideShakerCLI.java:684)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:203)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:896)
Caused by: java.sql.SQLException: No current connection.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 23 more
java.sql.SQLNonTransientConnectionException: No current connection.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.noCurrentConnection(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkIfClosed(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.getMetaData(Unknown Source)
	at com.compomics.util.db.ObjectsDB.getTables(ObjectsDB.java:250)
	at com.compomics.util.db.ObjectsDB.hasTable(ObjectsDB.java:229)
	at com.compomics.util.db.ObjectsDB.saveLongKeys(ObjectsDB.java:1185)
	at com.compomics.util.db.ObjectsDB.close(ObjectsDB.java:1224)
	at com.compomics.util.experiment.identification.protein_inference.proteintree.ProteinTreeComponentsFactory.close(ProteinTreeComponentsFactory.java:170)
	at com.compomics.util.experiment.identification.protein_inference.proteintree.ProteinTreeComponentsFactory.delete(ProteinTreeComponentsFactory.java:148)
	at com.compomics.util.experiment.identification.protein_inference.proteintree.ProteinTree.initiateTree(ProteinTree.java:271)
	at com.compomics.util.experiment.identification.protein_inference.proteintree.ProteinTree.initiateTree(ProteinTree.java:204)
	at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.getDefaultProteinTree(SequenceFactory.java:1411)
	at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.getDefaultProteinTree(SequenceFactory.java:1346)
	at eu.isas.peptideshaker.fileimport.FileImporter.importSequences(FileImporter.java:211)
	at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importFiles(FileImporter.java:449)
	at eu.isas.peptideshaker.fileimport.FileImporter.importFiles(FileImporter.java:158)
	at eu.isas.peptideshaker.PeptideShaker.importFiles(PeptideShaker.java:232)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.createProject(PeptideShakerCLI.java:684)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:203)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:896)
Caused by: java.sql.SQLException: No current connection.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 23 more
Sun Jan 24 20:36:35 EST 2016 Estimated import time: 7 minutes.
Sun Jan 24 20:36:35 EST 2016     See http://compomics.github.io/compomics-utilities/wiki/proteininference.html.
10% 20% 30%
</code>

**Comment by mvaudel** [comment]
Hi and thank you for reporting this. It seems that the tool is having problems when indexing the database. Is it a non standard database?

From what you send it has problem reading/writing the database index. Please make sure that the tool and the files are located locally on the computer in a folder with read/write access, and not on a network drive or a folder synced/mapped to a server. Also make sure that the maximum amount of memory available on the machine is given to the tool via the "Edit" -> "Java Settings" menu, and that java 64 bits is installed. Finally, make sure that the tool has writing privileges in the user folder. If it is not the case, please change the path used for resources folders via the "Edit" -> "Resources Settings".

Hope that helps, if not, can you send us the log of the tool? You can access it via the "Help" -> "Bug Report" menu.

Best regards,

Marc

**Comment by hbarsnes** [comment]
(Issue assumed fixed. If this is not the case, please let us know and we'll reopen the issue.)
