### ISSUE TITLE
Data import canceled when loading target-only search

### ISSUE THREAD

**Issue by BernhardBlank** [compomics/peptide-shaker#124]
When I'm trying to load the results from a SearchGUI run PeptideShaker will cancel the import, apparently because the search doesn't contain decoy sequences and thus validation metrics cannot be calculated.
I'm leaving out the decoys on purpose as I'm trying to use a two-step search strategy with rather large databases.
Are there any parameters I can deactivate in order to be able to load my decoy-free searches into PeptideShaker as well?

Here's the bugreport:

Wed Jan 27 09:24:34 CET 2016: PeptideShaker version 1.5.1.
Memory given to the Java virtual machine: 27962376192.
Total amount of memory in the Java virtual machine: 163053568.
Free memory: 126548672.
Java version: 1.8.0_60.
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read1(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at sun.net.www.http.HttpClient.parseHTTPHeader(Unknown Source)
	at sun.net.www.http.HttpClient.parseHTTP(Unknown Source)
	at sun.net.www.http.HttpClient.parseHTTP(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at com.compomics.software.autoupdater.WebDAO.getLatestVersionNumberFromRemoteRepo(WebDAO.java:34)
	at com.compomics.software.autoupdater.WebDAO.newVersionReleased(WebDAO.java:105)
	at com.compomics.software.CompomicsWrapper.checkForNewDeployedVersion(CompomicsWrapper.java:520)
	at eu.isas.peptideshaker.gui.PeptideShakerGUI.checkForNewVersion(PeptideShakerGUI.java:6884)
	at eu.isas.peptideshaker.gui.PeptideShakerGUI.<init>(PeptideShakerGUI.java:536)
	at eu.isas.peptideshaker.gui.PeptideShakerGUI.main(PeptideShakerGUI.java:475)
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.8.0_60
os.name: Windows 7
memory: 48.3/163.1
processors available: 16
useCommandThread: false
<CompomicsError>PeptideShaker processing failed. See the PeptideShaker log for details.</CompomicsError>
java.lang.NullPointerException
	at eu.isas.peptideshaker.scoring.targetdecoy.TargetDecoySeries.<init>(TargetDecoySeries.java:141)
	at eu.isas.peptideshaker.scoring.targetdecoy.TargetDecoyMap.getTargetDecoySeries(TargetDecoyMap.java:416)
	at eu.isas.peptideshaker.validation.MatchesValidator.validateIdentifications(MatchesValidator.java:202)
	at eu.isas.peptideshaker.PeptideShaker.processIdentifications(PeptideShaker.java:460)
	at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importFiles(FileImporter.java:553)
	at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.doInBackground(FileImporter.java:438)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Free memory: 7564628888

Thanks in advance!

**Comment by mvaudel** [comment]
Hi Bernhard and thanks for reporting this issue!

No decoys is a border line use case which brakes many components. It used to work in previous versions but it seems not to be the case anymore. I will correct this.

Apologies for the inconvenience,

Marc

**Comment by BernhardBlank** [comment]
Thanks Marc!

I know that's not a common way to use these tools, hope it is not too much effort to change!

Bernhard

**Comment by hbarsnes** [comment]
Hi Bernhard,

The issue should be fixed in PeptideShaker v1.7.0. If not, please let us know and we'll reopen the issue.

Best regards,
Harald

**Comment by BernhardBlank** [comment]
Thanks a lot, working like a charm now :)
