### ISSUE TITLE
Parsing comet pep.xml with sparse MGF spectrum file

### ISSUE THREAD

**Issue by jj-umn** [compomics/peptide-shaker#157]
I am trying to help a user with a PeptideShakerCLI run with MGF inputs that are sparse, i.e the scan number in the TITLE does represent the ordinal location in the file.   

Comet puts the scan number from the MGF TITLE into the "start_scan" attribute of the "spectrum_query" element of the pep.xml

com/compomics/util/experiment/io/identifications/idfilereaders/PepxmlIdfileReader.java 
treats the "start_scan" attribute of the "spectrum_query" element of a pep.xml as the index into the MGF file,  This is not the case when the MGF doesn't include all scans.

I posted the details to the compomics-utilities repository:
https://github.com/compomics/compomics-utilities/issues/11

**Comment by hbarsnes** [comment]
Thanks for telling us about this. Would it be possible for you to give us access to the search results the user is trying to process in PeptideShaker so that we can try to reproduce the error on our side?

**Comment by jj-umn** [comment]
The searchgui zip is 4.2GB.   I'll try to generate a smaller file that exhibits the same issue.

**Comment by hbarsnes** [comment]
Ok. I guess we should be able to reproduce the issue on our side with just one of the mgf files as well? By redoing the Comet search and trying to load the results in PeptideShaker?

**Comment by jj-umn** [comment]
A 30MB searchgui.zip   Using less than10 spectra per MGF
https://drive.google.com/file/d/0B5gotQcSckTmWjVpLWNLbDFOZGs/view?usp=sharing

PeptideShaker stack trace:

/home/mscls/apps/galaxyp2014/job_working_directory/000/112/112355/PeptideShakerCLI/.PeptideShaker_unzip_temp/searchgui_input_PeptideShaker_temp/Select first on data 12.comet.pep.xmljava.lang.IndexOutOfBoundsException: Index: 6, Size: 6
	at java.util.ArrayList.rangeCheck(ArrayList.java:635)
	at java.util.ArrayList.get(ArrayList.java:411)
	at com.compomics.util.experiment.io.massspectrometry.MgfIndex.getSpectrumTitle(MgfIndex.java:239)
	at com.compomics.util.experiment.massspectrometry.SpectrumFactory.getSpectrumTitle(SpectrumFactory.java:992)
	at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importSpectrum(FileImporter.java:999)
	at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importPsms(FileImporter.java:727)
	at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importFiles(FileImporter.java:482)
	at eu.isas.peptideshaker.fileimport.FileImporter.importFiles(FileImporter.java:158)
	at eu.isas.peptideshaker.PeptideShaker.importFiles(PeptideShaker.java:232)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.createProject(PeptideShakerCLI.java:696)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:205)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:908)
Free memory: 7985895048

**Comment by hbarsnes** [comment]
Thanks for the test files. I can confirm that the error is reproducible on our side. We will try to come up with a proper fix and release a new version next week.

**Comment by hbarsnes** [comment]
The parsing now uses spectrumNativeID if it exists, and we're now able to process your example dataset. A new version of PeptideShaker has been released. Please let us know if you still have problems when parsing the complete dataset and we'll reopen the issue.
