### ISSUE TITLE
Error when parsing spectrum title from X! Tandem example mgf file

### ISSUE THREAD

**Issue by im281** [compomics/peptide-shaker#169]
can you please advise on this error?

10% 20% 30% 40% 50% 60% 70% 80% 90% 100%

Thu May 12 16:28:50 PDT 2016 Import process for CommandLineExperiment (Sample: B
SA, Replicate: 1)

Thu May 12 16:28:51 PDT 2016 Importing sequences from bsa.fasta.
Thu May 12 16:28:55 PDT 2016 Estimated import time: 0 seconds.
Thu May 12 16:28:55 PDT 2016     See http://compomics.github.io/compomics-utilit
ies/wiki/proteininference.html.
Thu May 12 16:28:56 PDT 2016 FASTA file import completed.
Thu May 12 16:28:56 PDT 2016 Importing gene mappings.
Thu May 12 16:28:56 PDT 2016     Downloading GO and gene mappings for species Bo
s taurus.
Thu May 12 16:28:57 PDT 2016 Downloading GO Mappings. Please Wait...
Thu May 12 16:28:58 PDT 2016     GO mappings downloaded.
Thu May 12 16:28:58 PDT 2016     GO mappings downloaded.
Thu May 12 16:28:58 PDT 2016 Downloading Gene Mappings. Please Wait...
Thu May 12 16:28:58 PDT 2016     Gene mappings downloaded.
Thu May 12 16:28:58 PDT 2016     Gene mappings downloaded.
Thu May 12 16:28:58 PDT 2016 Establishing local database connection.
Thu May 12 16:29:00 PDT 2016 Reading identification files.
Thu May 12 16:29:00 PDT 2016 Parsing test_spectra.comet.pep.xml.
Thu May 12 16:29:00 PDT 2016 Loading spectra for test_spectra.comet.pep.xml.
Thu May 12 16:29:00 PDT 2016 Importing test_spectra.mgf
Thu May 12 16:29:01 PDT 2016 test_spectra.mgf imported.
 0%
10% 20% 30% 40% 50% 60% 70% 80%
Thu May 12 16:29:01 PDT 2016 Collecting peptides to map.
10% 20% 30% 40% 50% 60% 70% 80% 100%
Thu May 12 16:29:01 PDT 2016 Mapping peptides to proteins.
10% 20% 30% 50% 60% 70% 80% 100%
Thu May 12 16:29:01 PDT 2016 Importing PSMs from test_spectra.comet.pep.xml
 20% 30% 40% 50% 60% 80% 100%
Thu May 12 16:29:01 PDT 2016 4 identified spectra (44.4%) did not present a vali
d peptide.
Thu May 12 16:29:01 PDT 2016 4 of the best scoring peptides were excluded by the
 import filters:
Thu May 12 16:29:01 PDT 2016     - 100.0% peptide presenting high mass or isotop
ic deviation.
Thu May 12 16:29:01 PDT 2016 Parsing test_spectra.ms-amanda.csv.
10% 100%
Thu May 12 16:29:01 PDT 2016 Loading spectra for test_spectra.ms-amanda.csv.
Thu May 12 16:29:01 PDT 2016 Spectrum 'Label: W1297, Spot_Id: 160174, Peak_List_
Id: 184987, MSMS Job_Run_Id: 14047, Comment: ' not found in file test_spectra.mg
f.
<CompomicsError>PeptideShaker processing failed. See the PeptideShaker log for d
etails.</CompomicsError>
Thu May 12 16:29:01 PDT 2016 An error occurred while loading the identification
files:
Thu May 12 16:29:01 PDT 2016 Spectrum 'Label: W1297, Spot_Id: 160174, Peak_List_
Id: 184987, MSMS Job_Run_Id: 14047, Comment: ' not found in file test_spectra.mg
f.
java.lang.IllegalArgumentException: Spectrum 'Label: W1297, Spot_Id: 160174, Pea
k_List_Id: 184987, MSMS Job_Run_Id: 14047, Comment: ' not found in file test_spe
ctra.mgf.
        at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.imp
ortSpectrum(FileImporter.java:1006)
        at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.imp
ortPsms(FileImporter.java:726)
        at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.imp
ortFiles(FileImporter.java:481)
        at eu.isas.peptideshaker.fileimport.FileImporter.importFiles(FileImporte
r.java:156)
        at eu.isas.peptideshaker.PeptideShaker.importFiles(PeptideShaker.java:23
2)
        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.createProject(PeptideShake
rCLI.java:696)
        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java
:205)
        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java
:908)
Free memory: 274137000
Thu May 12 16:29:01 PDT 2016 PeptideShaker Processing Canceled.
<CompomicsError>PeptideShaker processing canceled. See the PeptideShaker log for
 details.</CompomicsError>

C:\Users\iman.mohtashemi\Downloads\PeptideShaker-1.10.3\PeptideShaker-1.10.3>

**Comment by mvaudel** [comment]
Hi and thank you for reporting this issue. Can you send us the log and the command line used? 

The is available via the "Help" -> "Bug Report" menu of the interface or in the "resources" folder of PeptideShaker ("PeptideShaker.log").

**Comment by im281** [comment]
Here is the log:

Thu May 12 16:26:00 PDT 2016: PeptideShaker version 1.10.3.
Memory given to the Java virtual machine: 3817799680.
Total amount of memory in the Java virtual machine: 128647168.
Free memory: 93022128.
Java version: 1.7.0_03.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.7.0_03
os.name: Windows 7
memory: 36.1/128.6
processors available: 8
useCommandThread: false
Reindexing: uniprot-human-reviewed-trypsin-april-2016_concatenated_target_decoy.fasta.

**Comment by im281** [comment]
Here is the command:
C:\PeptideShaker-1.10.3>java -cp PeptideShaker-1.10.3.jar eu.isas.peptideshaker.cmd.PeptideShakerCLI -experiment CommandLineExperiment -sample BSA -replicate 1 -identification_files C:\Results\searchgui_out.zip -out C:\Results\BSAResults.cpsx -spectrum_files C:\SearchGUI\test_spectra.mgf -id_params \testparams.par

**Comment by im281** [comment]
The errors copied:
Fri May 13 06:33:20 PDT 2016 Spectrum 'Label: W1297, Spot_Id: 160174, Peak_List_
Id: 184987, MSMS Job_Run_Id: 14047, Comment: ' not found in file test_spectra.mg
f.
java.lang.IllegalArgumentException: Spectrum 'Label: W1297, Spot_Id: 160174, Pea
k_List_Id: 184987, MSMS Job_Run_Id: 14047, Comment: ' not found in file test_spe
ctra.mgf.
        at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.imp
ortSpectrum(FileImporter.java:1006)
        at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.imp
ortPsms(FileImporter.java:726)
        at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.imp
ortFiles(FileImporter.java:481)
        at eu.isas.peptideshaker.fileimport.FileImporter.importFiles(FileImporte
r.java:156)
        at eu.isas.peptideshaker.PeptideShaker.importFiles(PeptideShaker.java:23
2)
        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.createProject(PeptideShake
rCLI.java:696)
        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java
:205)
        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java
:908)

**Comment by im281** [comment]
latest log file:
Thu May 12 16:26:00 PDT 2016: PeptideShaker version 1.10.3.
Memory given to the Java virtual machine: 3817799680.
Total amount of memory in the Java virtual machine: 128647168.
Free memory: 93022128.
Java version: 1.7.0_03.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.7.0_03
os.name: Windows 7
memory: 36.1/128.6
processors available: 8
useCommandThread: false
Reindexing: uniprot-human-reviewed-trypsin-april-2016_concatenated_target_decoy.fasta.


Fri May 13 06:29:28 PDT 2016: PeptideShaker version 1.10.3.
Memory given to the Java virtual machine: 3817799680.
Total amount of memory in the Java virtual machine: 128647168.
Free memory: 93179264.
Java version: 1.7.0_03.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.7.0_03
os.name: Windows 7
memory: 62.1/162.2
processors available: 8
useCommandThread: false
Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
	at javax.swing.plaf.synth.SynthTableUI$SynthBooleanTableCellRenderer.getTableCellRendererComponent(Unknown Source)
	at javax.swing.JTable.prepareRenderer(Unknown Source)
	at javax.swing.plaf.synth.SynthTableUI.paintCell(Unknown Source)
	at javax.swing.plaf.synth.SynthTableUI.paintCells(Unknown Source)
	at javax.swing.plaf.synth.SynthTableUI.paint(Unknown Source)
	at javax.swing.plaf.synth.SynthTableUI.update(Unknown Source)
	at javax.swing.JComponent.paintComponent(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JViewport.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JLayeredPane.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JSplitPane.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JLayeredPane.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintToOffscreen(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
	at javax.swing.RepaintManager.paint(Unknown Source)
	at javax.swing.JComponent._paintImmediately(Unknown Source)
	at javax.swing.JComponent.paintImmediately(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.access$700(Unknown Source)
	at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$000(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.WaitDispatchSupport$2.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$000(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by mvaudel** [comment]
Hi again,

It seems that the tool does not find the spectrum of one of your peptides. Can you make sure that the same mgf file was used for the search, and make the file available to us for testing? It can be that the spectrum titles contain special characters not handled adequately by some search engines.

Best regards,

Marc

**Comment by im281** [comment]
Here are the files

**Comment by im281** [comment]
[files.zip](https://github.com/compomics/peptide-shaker/files/263382/files.zip)

**Comment by im281** [comment]
This mgf file is the example mgf file from the XTandem Search algorithm download

**Comment by im281** [comment]
It worked with your example files. Probably something wrong witht ehexample mgf file I provided. Thanks! This is awesome!

**Comment by hbarsnes** [comment]
> It worked with your example files. Probably something wrong witht ehexample mgf file I provided.

Good to hear that it worked for other mgf files. I think the problem might be the space at the end of the spectrum title in the X! Tandem mgf example file. We'll look into it and get back to you.

Best regards,
Harald

**Comment by hbarsnes** [comment]
The issue with the loading of the X! Tandem mgf example file (or rather the loading of mgfs with spectrum titles with trailing white space) has been resolved in the latest releases of SearchGUI and PeptideShaker.

Best regards,
Harald
