### ISSUE TITLE
PTM localization error

### ISSUE THREAD

**Issue by K019471** [compomics/peptide-shaker#184]
Dear developer,

I encountered some problems while using the PeptideShaker tool. I have tried a few times uploading my searchgui_out that I obtained from SearchGUI tool. Unfortunately the error keeps popping out and I cannot view the data. Please find attached Error log. Hope to get some insights on this. 

[Error log 15.06.16.txt](https://github.com/compomics/peptide-shaker/files/324659/Error.log.15.06.16.txt)

Thanks.

Aizat

**Comment by hbarsnes** [comment]
Hi Aizat,

Thanks for setting up the issues. I still need the PeptideShaker log file though, in addition to the output from the user interface that you provided above. You'll find the log via the PeptideShaker Welcome Dialog > Settings & Help > Help > Bug Report.

Best regards,
Harald

**Comment by K019471** [comment]
Hi Harald,

Attached is the Bug report. I hope this is the right one. I've also
attached the same file in our MQ Google groups tread. Thanks.

Aizat

On 21 June 2016 at 17:25, Harald Barsnes <notifications@github.com> wrote:

> Hi Aizat,
>
> Thanks for setting up the issues. I still need the PeptideShaker log file
> though, in addition to the output from the user interface that you provided
> above. You'll find the log via the PeptideShaker Welcome Dialog > Settings
> & Help > Help > Bug Report.
>
> Best regards,
> Harald
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/compomics/peptide-shaker/issues/184#issuecomment-227387384>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ATIJPe_wMmE6EJ18gvC8ttDP_ElwYJk7ks5qN64MgaJpZM4I6Se8>
> .
>



Wed Jun 08 15:54:34 SGT 2016: PeptideShaker version 1.11.0.
Memory given to the Java virtual machine: 1042022400.
Total amount of memory in the Java virtual machine: 129761280.
Free memory: 108365928.
Java version: 1.8.0_91.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.8.0_91
os.name: Windows 10
memory: 48.2/129.9
processors available: 8
useCommandThread: false


Fri Jun 10 10:46:37 SGT 2016: PeptideShaker version 1.11.0.
Memory given to the Java virtual machine: 1042022400.
Total amount of memory in the Java virtual machine: 129761280.
Free memory: 108408064.
Java version: 1.8.0_91.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.8.0_91
os.name: Windows 10
memory: 48.4/129.9
processors available: 8
useCommandThread: false


Fri Jun 10 18:17:22 SGT 2016: PeptideShaker version 1.11.0.
Memory given to the Java virtual machine: 1042022400.
Total amount of memory in the Java virtual machine: 129761280.
Free memory: 108360776.
Java version: 1.8.0_91.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.8.0_91
os.name: Windows 10
memory: 48.2/129.9
processors available: 8
useCommandThread: false
<CompomicsError>PeptideShaker processing failed. See the PeptideShaker log for details.</CompomicsError>
java.lang.NullPointerException
	at eu.isas.peptideshaker.parameters.PSPtmScores.changeRepresentativeSite(PSPtmScores.java:227)
	at eu.isas.peptideshaker.ptm.PtmScorer.peptideInference(PtmScorer.java:1876)
	at eu.isas.peptideshaker.PeptideShaker.processIdentifications(PeptideShaker.java:391)
	at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importFiles(FileImporter.java:556)
	at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.doInBackground(FileImporter.java:439)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Free memory: 421752720


Sat Jun 11 13:53:29 SGT 2016: PeptideShaker version 1.11.0.
Memory given to the Java virtual machine: 1042022400.
Total amount of memory in the Java virtual machine: 129761280.
Free memory: 107627272.
Java version: 1.8.0_91.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.8.0_91
os.name: Windows 10
memory: 48.4/129.9
processors available: 8
useCommandThread: false
<CompomicsError>PeptideShaker processing failed. See the PeptideShaker log for details.</CompomicsError>
java.lang.NullPointerException
	at eu.isas.peptideshaker.parameters.PSPtmScores.changeRepresentativeSite(PSPtmScores.java:227)
	at eu.isas.peptideshaker.ptm.PtmScorer.peptideInference(PtmScorer.java:1876)
	at eu.isas.peptideshaker.PeptideShaker.processIdentifications(PeptideShaker.java:391)
	at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importFiles(FileImporter.java:556)
	at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.doInBackground(FileImporter.java:439)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Free memory: 559817000


Wed Jun 15 11:17:09 SGT 2016: PeptideShaker version 1.11.0.
Memory given to the Java virtual machine: 1042022400.
Total amount of memory in the Java virtual machine: 129761280.
Free memory: 107529840.
Java version: 1.8.0_91.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.8.0_91
os.name: Windows 10
memory: 48.3/129.9
processors available: 8
useCommandThread: false
<CompomicsError>PeptideShaker processing failed. See the PeptideShaker log for details.</CompomicsError>
java.lang.NullPointerException
	at eu.isas.peptideshaker.parameters.PSPtmScores.changeRepresentativeSite(PSPtmScores.java:227)
	at eu.isas.peptideshaker.ptm.PtmScorer.peptideInference(PtmScorer.java:1876)
	at eu.isas.peptideshaker.PeptideShaker.processIdentifications(PeptideShaker.java:391)
	at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importFiles(FileImporter.java:556)
	at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.doInBackground(FileImporter.java:439)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Free memory: 256015800


Wed Jun 15 18:10:51 SGT 2016: PeptideShaker version 1.11.0.
Memory given to the Java virtual machine: 1042022400.
Total amount of memory in the Java virtual machine: 129761280.
Free memory: 107654056.
Java version: 1.8.0_91.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.8.0_91
os.name: Windows 10
memory: 48.3/129.9
processors available: 8
useCommandThread: false


Wed Jun 15 19:56:36 SGT 2016: PeptideShaker version 1.11.0.
Memory given to the Java virtual machine: 1042022400.
Total amount of memory in the Java virtual machine: 129761280.
Free memory: 99402712.
Java version: 1.8.0_91.


Thu Jun 16 09:34:47 SGT 2016: PeptideShaker version 1.11.0.
Memory given to the Java virtual machine: 1042022400.
Total amount of memory in the Java virtual machine: 129761280.
Free memory: 106672152.
Java version: 1.8.0_91.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.8.0_91
os.name: Windows 10
memory: 48.4/129.9
processors available: 8
useCommandThread: false
<CompomicsError>PeptideShaker processing failed. See the PeptideShaker log for details.</CompomicsError>
java.lang.NullPointerException
	at eu.isas.peptideshaker.parameters.PSPtmScores.changeRepresentativeSite(PSPtmScores.java:227)
	at eu.isas.peptideshaker.ptm.PtmScorer.peptideInference(PtmScorer.java:1876)
	at eu.isas.peptideshaker.PeptideShaker.processIdentifications(PeptideShaker.java:391)
	at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importFiles(FileImporter.java:556)
	at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.doInBackground(FileImporter.java:439)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Free memory: 378998792


Tue Jun 21 17:50:14 SGT 2016: PeptideShaker version 1.11.0.
Memory given to the Java virtual machine: 1042022400.
Total amount of memory in the Java virtual machine: 129761280.
Free memory: 107602944.
Java version: 1.8.0_91.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.8.0_91
os.name: Windows 10
memory: 48.3/129.9
processors available: 8
useCommandThread: false
<CompomicsError>PeptideShaker processing failed. See the PeptideShaker log for details.</CompomicsError>
java.lang.NullPointerException
	at eu.isas.peptideshaker.parameters.PSPtmScores.changeRepresentativeSite(PSPtmScores.java:227)
	at eu.isas.peptideshaker.ptm.PtmScorer.peptideInference(PtmScorer.java:1876)
	at eu.isas.peptideshaker.PeptideShaker.processIdentifications(PeptideShaker.java:391)
	at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importFiles(FileImporter.java:556)
	at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.doInBackground(FileImporter.java:439)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Free memory: 253062104

**Comment by mvaudel** [comment]
Hi,

It seems to be a problem with the localization of PTMs. Can you make the SearchGUI output as well as mgf and fasta files available to us?

Additionally, when creating your PeptideShaker project, can you try the following: Edit the _Identification Settings_, click on _Show Advanced Settings_, and under _PTM Localization_ set the _Site Alignment_ of _Confident Sites_ to _No_.

Thank you for your help and apologies for the inconvenience,

Marc

**Comment by K019471** [comment]
Great Marc, thanks for the info. Will try that PTM setting change first and will let you know soon.

Thanks 

Aizat

**Comment by K019471** [comment]
Hi Marc, 

Sorry for taking quite a long time to update you on this issue. I tried your suggestion (selecting "no" for the Site Alignment of Confident Sites in the PTM localization but still the same error message (importing data cancelled) emerged and the analysis was aborted. I tried this for a few times with the same result. Attached is the bug log file. Hope you can shed some lights to this problem. Thanks

Aizat 

PS. If needed I can supply you the mgf and fasta files too. Perhaps via google drive or ftp. Please let me know the details for the transfer.

[PeptideShaker 1.11.0 log_bug report2_29.06.16.txt](https://github.com/compomics/peptide-shaker/files/338437/PeptideShaker.1.11.0.log_bug.report2_29.06.16.txt)

**Comment by mvaudel** [comment]
Hi Aizat,

I am very sorry to hear that it did not work. Can you make the SearchGUI output, fasta, and mgf files available to us? Google drive would be perfect :)

Apologies again for the inconvenience,

Marc

**Comment by K019471** [comment]
Hi Marc,

Many thanks for the help. No need to apologise. I am also pretty much new
to Peptideshaker and perhaps I did something wrong in the process. Hope to
get some insights from you. Cheers

Aizat
​
 CHA_271115_01.mgf
<https://drive.google.com/file/d/0B6UCdYN_vr1pMlBUdERWQ041V2s/view?usp=drive_web>
​​
 CHB_041215_01.mgf
<https://drive.google.com/file/d/0B6UCdYN_vr1pQ1V0bERBTDZPMjg/view?usp=drive_web>
​​
 CHC_041215_01.mgf
<https://drive.google.com/file/d/0B6UCdYN_vr1pTkNoN3YtaGd6UTg/view?usp=drive_web>
​​
 Cntl_271115_01.mgf
<https://drive.google.com/file/d/0B6UCdYN_vr1pR0tDc1N1bzFhTm8/view?usp=drive_web>
​​
 CntlB_041215_01.mgf
<https://drive.google.com/file/d/0B6UCdYN_vr1pUHBzV3dkOVQ1bVE/view?usp=drive_web>
​​
 CntlC_041215_01.mgf
<https://drive.google.com/file/d/0B6UCdYN_vr1pS3JvTFp3QWRUdmM/view?usp=drive_web>
​​
 searchgui_out.zip
<https://drive.google.com/file/d/0B6UCdYN_vr1pSE1OZUxQWlVjMkk/view?usp=drive_web>
​​
 uniprot-epinephelus_15Feb16.fasta
<https://drive.google.com/file/d/0B6UCdYN_vr1pak5yWkFrdXhqczQ/view?usp=drive_web>
​

**Comment by hbarsnes** [comment]
Hi Aizat,

PeptideShaker v1.13.0 has just been released which hopefully fixes this issue. If this is not the case please let us know and we'll reopen the issue.

Best regards,
Harald
