### ISSUE TITLE
Can't reopen PeptideShaker projects

### ISSUE THREAD

**Issue by pjvolders** [compomics/peptide-shaker#189]
Hi,

I'm having some trouble with PeptideShaker on Ubuntu 14.04.4. Everything works fine when the project is processed and opened the first time (processing from SearchGUI), but when I save the project and try to reopen it in PeptideShaker I get the following error: "It looks like another instance of PeptideShaker is still connected to the file. Please close all instances of PeptideShaker and try again.". I tried copying the file and exporting in cpsx and zip format. I have provided the cpsx and PeptideShaker log file below.

Cheers,
PJ

https://www.dropbox.com/s/xu3cirm08z1ad8n/Spectral%20Searching%202.cpsx?dl=0

Tue Jul 05 10:51:47 CEST 2016: PeptideShaker version 1.12.1.
Memory given to the Java virtual machine: 3817865216.
Total amount of memory in the Java virtual machine: 163053568.
Free memory: 126803552.
Java version: 1.8.0_91.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.8.0_91
os.name: Linux
memory: 54.6/163.1
processors available: 16
useCommandThread: false
java.sql.SQLSyntaxErrorException: Table/View 'PEPTIDESHAKER_EXPERIMENT_SETTINGS' does not exist.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.execute(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeQuery(Unknown Source)
	at com.compomics.util.db.ObjectsDB.retrieveObjectSynchronized(ObjectsDB.java:801)
	at com.compomics.util.db.ObjectsDB.retrieveObject(ObjectsDB.java:750)
	at eu.isas.peptideshaker.fileimport.CpsFileImporter.getPeptideShakerSettings(CpsFileImporter.java:78)
	at eu.isas.peptideshaker.utils.CpsParent.loadCpsFile(CpsParent.java:245)
	at eu.isas.peptideshaker.gui.PeptideShakerGUI$104.run(PeptideShakerGUI.java:5461)
Caused by: java.sql.SQLException: Table/View 'PEPTIDESHAKER_EXPERIMENT_SETTINGS' does not exist.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 13 more
Caused by: ERROR 42X05: Table/View 'PEPTIDESHAKER_EXPERIMENT_SETTINGS' does not exist.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.compile.FromBaseTable.bindTableDescriptor(Unknown Source)
	at org.apache.derby.impl.sql.compile.FromBaseTable.bindNonVTITables(Unknown Source)
	at org.apache.derby.impl.sql.compile.FromList.bindTables(Unknown Source)
	at org.apache.derby.impl.sql.compile.SelectNode.bindNonVTITables(Unknown Source)
	at org.apache.derby.impl.sql.compile.DMLStatementNode.bindTables(Unknown Source)
	at org.apache.derby.impl.sql.compile.DMLStatementNode.bind(Unknown Source)
	at org.apache.derby.impl.sql.compile.CursorNode.bindStatement(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepMinion(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepare(Unknown Source)
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.prepareInternalStatement(Unknown Source)
	... 7 more
java.sql.SQLSyntaxErrorException: Table/View 'PEPTIDESHAKER_EXPERIMENT_SETTINGS' does not exist.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.execute(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeQuery(Unknown Source)
	at com.compomics.util.db.ObjectsDB.retrieveObjectSynchronized(ObjectsDB.java:801)
	at com.compomics.util.db.ObjectsDB.retrieveObject(ObjectsDB.java:750)
	at eu.isas.peptideshaker.fileimport.CpsFileImporter.getPeptideShakerSettings(CpsFileImporter.java:78)
	at eu.isas.peptideshaker.utils.CpsParent.loadCpsFile(CpsParent.java:245)
	at eu.isas.peptideshaker.gui.PeptideShakerGUI$104.run(PeptideShakerGUI.java:5461)
Caused by: java.sql.SQLException: Table/View 'PEPTIDESHAKER_EXPERIMENT_SETTINGS' does not exist.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 13 more
Caused by: ERROR 42X05: Table/View 'PEPTIDESHAKER_EXPERIMENT_SETTINGS' does not exist.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.compile.FromBaseTable.bindTableDescriptor(Unknown Source)
	at org.apache.derby.impl.sql.compile.FromBaseTable.bindNonVTITables(Unknown Source)
	at org.apache.derby.impl.sql.compile.FromList.bindTables(Unknown Source)
	at org.apache.derby.impl.sql.compile.SelectNode.bindNonVTITables(Unknown Source)
	at org.apache.derby.impl.sql.compile.DMLStatementNode.bindTables(Unknown Source)
	at org.apache.derby.impl.sql.compile.DMLStatementNode.bind(Unknown Source)
	at org.apache.derby.impl.sql.compile.CursorNode.bindStatement(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepMinion(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepare(Unknown Source)
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.prepareInternalStatement(Unknown Source)
	... 7 more

**Comment by hbarsnes** [comment]
Hi PJ,

Thanks for telling us about this. I assume you've already checked that you only have one version of PeptideShaker running when trying to save the project?

And just to be clear, it all works fine when doing the search and post-processing in PeptideShaker via SearchGUI? I.e. no errors and you're able to open the saved PeptideShaker project? And saving again after opening directly in PeptideShaker also gives no errors? But then you get the above error when trying to reopen this saved project?

In any case, to me it seems like something went wrong in the saving of the project. Can you send me the complete PeptideShaker log file? Maybe it can tell us what the problem is.

Best regards,
Harald

**Comment by pjvolders** [comment]
Dear Harald,

Indeed I verified that no PeptideShaker instance was running and even did a reboot to be completely sure. All seems to work fine when doing the search with SearchGUI, I am able to view, save and even export the project without issues. I only get the error when reopening the saved project. I have attached the full log, hope this helps.

Cheers,
PJ

[PeptideShaker.log.txt](https://github.com/compomics/peptide-shaker/files/349459/PeptideShaker.log.txt)

**Comment by hbarsnes** [comment]
Hi PJ,

I see some errors in your log file, but not sure if they can explain the problem or not. Worth having a look at though.

The first is this one:
`Page Page(220,Container(0, 2864)) could not be written to disk, please check if the disk is full, or if a file system limit, such as a quota or a maximum file size, has been reached.`

This would indicate that you're running out of disk space. Or at least did so on June 30th. So please make sure that you have enough free disk space available.

The next is:
`java.lang.OutOfMemoryError: Java heap space`

This indicates memory issues. How much memory are you giving to PeptideShaker? You can change this via the PeptideShaker Welcome dialog > Settings & Help > Settings > Java Settings. The more memory you can give PeptideShaker the better, and the faster the processing will go.

Also, I would recommend changing the peptide to protein mapping method to using the FM-Index, as this is a lot quicker and uses a lot less memory. This is the default for all new search settings, but for older settings you can change this option by clicking the Edit button next to the Identification settings in either SearchGUI or PeptideShaker, then click Show Advanced Settings > Sequence Matching > and select FM-Index as the index type. Should no have any impact on the error above though.

Could you please try the suggestions above? If it still does not work it would be great if you could send me a zip file with the SearchGUI output plus the fasta and mgf files. I will then try to reproduce the errors on my side.

BTW, I assume you've tried redoing the search from scratch to see if the error is reproducible? Because if the PeptideShaker cpsx file has gotten corrupted (perhaps due to the disk space or memory issues above) it cannot be rescued and the only fix would be to reload the search results.

Best regards,
Harald

**Comment by pjvolders** [comment]
Hi Harald,

I believe those at least errors are from a previous run, before I moved the matches folder to a different partition. As suggested, I redid the run this time for a single mgf, verified that I have sufficient disk space and increased the RAM to 16Gb. Sequence Matching was already set to FM-Index.
Even with a single mgf file I have the same issue. I have prepared a folder for you which contains all files used in the run:

[http://genesis.ugent.be/uvpublicdata/pjvolders_peptideshaker_bug/](http://genesis.ugent.be/uvpublicdata/pjvolders_peptideshaker_bug/)

I have cleared the PeptideShaker log file, so all errors in there are from this one run.

Cheers,
PJ

**Comment by hbarsnes** [comment]
Hi PJ,

I can confirm that your cpsx file is corrupt and cannot be opened. However, I have no problems if I load your search results in PeptideShaker. Reopening after saving is also fine. Even after making changes and resaving.

According to my co-developer we've seen this issue once before, but it was not reproducible, not even by the user reporting the issue. So hopefully reloading the search results directly in PeptideShaker will solve the problem. Please let us know if this is still not the case.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi PJ,

As I didn't hear back from you regarding this issue I assume you managed to solve the problem? If this is not the case, please try the just released PeptideShaker v1.13.0 and let me know if you still have problems with this one? In that case we'll reopen the issue.

Best regards,
Harald
