### ISSUE TITLE
"java.lang.NullPointerException" error when reading SearchGUI file

### ISSUE THREAD

**Issue by paulstodghill** [compomics/peptide-shaker#198]
I received the following error when trying to create a new project using a SearchGUI results file,

```
Fri Aug 12 14:14:30 EDT 2016: PeptideShaker version 1.12.3.
Memory given to the Java virtual machine: 3817865216.
Total amount of memory in the Java virtual machine: 128974848.
Free memory: 97718088.
Java version: 1.8.0_91.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.8.0_91
os.name: Linux
memory: 51.7/163.1
processors available: 12
useCommandThread: false
java.lang.NullPointerException
	at com.compomics.util.experiment.identification.ptm.ptmscores.PhosphoRS.filterSpectrum(PhosphoRS.java:842)
	at com.compomics.util.experiment.identification.ptm.ptmscores.PhosphoRS.getSequenceProbabilities(PhosphoRS.java:190)
	at eu.isas.peptideshaker.ptm.PtmScorer.attachProbabilisticScore(PtmScorer.java:316)
	at eu.isas.peptideshaker.ptm.PtmScorer.scorePTMs(PtmScorer.java:415)
	at eu.isas.peptideshaker.ptm.PtmScorer$PsmPtmScorerRunnable.run(PtmScorer.java:2363)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```
I can provide additional info, if it would be helpful. I can also make make the SearchGUI results file available by out-of-band channel.

Thanks.

**Comment by hbarsnes** [comment]
Hi.

Thanks for telling us about this. Would be great I you could send us the SearchGUI results file, plus the FASTA and mgf files, so that we can try to reproduce the error on our side. You can send the data directly to me at harald.barsnes AT gmail.com.

Best regards,
Harald

**Comment by paulstodghill** [comment]
Done.

In the process of putting together files to send you, I ended up
running PeptideShaker several more times. 

There appears to be a race condition. Sometimes when I run with 12
threads and the `-xtandem 1 -myrimatch 1 -comet 1` options, I get
ArrayIndexOutOfBoundsException, and other times I get the
NullPointerException error. It seems runs to completion with `-threads
1`.

Since I filed the bug eport for the NullPointerException error, those
are files that I'm providing.

**Comment by hbarsnes** [comment]
Thanks for the files, and yes, it looks like a threading issue. We'll look into it and hopefully come up with a solution.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi Paul,

PeptideShaker v1.13.1 has just been released which should fix this threading issue. If this is not the case, please let us know and we'll reopen the issue.

Note that this fix most likely does not correct the other threading issue you reported. Marc is still looking into on that one.

Best regards,
Harald
