### ISSUE TITLE
Will PeptideShaker import mzIdentML results files generated by PEAKS Studio?

### ISSUE THREAD

**Issue by AnotherKiwi** [compomics/peptide-shaker#199]
I've tried importing the mzIdentML file exported by PEAKS Studio 8 for use by Scaffold (both v 1.0 and 1.1 - see attached screenshot) but PeptideShaker fails to find PSM in the file. The PeptideShaker output shows:

Tue Aug 16 11:57:16 NZST 2016        Reading identification files.
Tue Aug 16 11:57:16 NZST 2016        Parsing peptides_1_1_0.mzid.
Tue Aug 16 11:57:16 NZST 2016        No PSM found in peptides_1_1_0.mzid.
Tue Aug 16 11:57:16 NZST 2016        No identifications retained.

Can you please advise if it is possible to import PEAKS results files into PeptideShaker? If so, what am I doing wrong?

Thanks
Stephen

![peaksstudio_2016-08-16_11-49-08](https://cloud.githubusercontent.com/assets/17808219/17683535/c7bf63fe-63a7-11e6-8651-07db3ce6c804.png)

**Comment by hbarsnes** [comment]
Hi Stephen,

My guess is that we don't parse the PSM scores used by PEAKS. Could you send us an example mzid file from PEAKS so that we can try to locate the problem? We would also need the mgf file used as input in order to ensure that we can map the PSMs back to the spectra.

Best regards,
Harald

**Comment by AnotherKiwi** [comment]
Hi Harald

The mzid file and MGFs used for the search are attached. I must confess to being a complete newbie with mzIdentML files so I'm not sure whether PEAKS exports all the required information. I'll be interested to hear your verdict!

Kind regards
Stephen

[XTandem Test_PEAKS PTM_16.zip](https://github.com/compomics/peptide-shaker/files/421221/XTandem.Test_PEAKS.PTM_16.zip)

**Comment by hbarsnes** [comment]
Hi Stephen,

Seems like the PEAKS mzid file exposed an issue in the way we parsed mzid files. Already corrected, just need to check that the fix it generic enough. Will release a new version later this week.

Best regards,
Harald

**Comment by AnotherKiwi** [comment]
Thanks Harald

I look forward to trying incorporating PEAKS results in the new version.

Kind regards
Stephen

**Comment by 1Moe** [comment]
Hi Harald and Stephen,

might hijack this topic and see if I could get some help.
Trying to import a mzid file from peptideshaker into peakview but peakview complaines and doesn't accept the format. 

mzid file can be downloaded here:
https://drive.google.com/drive/folders/0BybCLLWRgDsUX2VTc0F1ZlpCMnM

See below for the PeakView error message (very non-descriptive, unfortunately):
Cheers
Moe

The given key was not present in the dictionary.

   at ABSciex.PeakViewPlugin.SwathMenu.SwathLoadIonLibraryAction.LoadIonLibrary()
   at ABSciex.PeakViewPlugin.SwathMenu.SwathLoadIonLibraryAction.Execute()
   at Clearcore2.Utility.UI.UICommands.CommandAction.ExecuteCommand(Command command)
   at Clearcore2.Utility.UI.UICommands.Command.Execute(CommandExecutor executor)
   at Clearcore2.Utility.UI.UICommands.CommandExecutor.ExecuteCommand()

PeakView Version: 2.2.0.0
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
OS Size: 64-bit
DotNet Loader Version: 4.0.30319.42000

**Comment by hbarsnes** [comment]
Hi Moe,

The PeptideShaker mzid files should be ok. At least they pass all the mzid validation tests. It looks like PeakView is not supporting one (or more) of the CV terms used in the PeptideShaker mzid file. We used to have similar issues with Skyline. In order to fix it you'll have to contact the PeakView developers. Should be straightforward for them to adapt their code.

Best regards,
Harald

**Comment by AnotherKiwi** [comment]
Hi Harald
I'll give v1.13.1 a try and let you know if I still have problems.
Thanks very much for the excellent support!
Cheers
Stephen
