### ISSUE TITLE
filter / view results error, view subsets of data

### ISSUE THREAD

**Issue by dblyon** [compomics/peptide-shaker#214]
Dear Compomics-team,

I would like to **view subsets of the data** in peptideShaker (filter data), that fulfil certain criteria (e.g. confidence >= 95.0%, protein = validated, etc.). Also, I would like to **save results based on these filters**. (I'm not referring to the mzid issue raised in the previous post #146.)

I've been trying to filter using the following menu items in the GUI of peptideShaker:
Filtering/viewing results in peptideShaker:
- "View / Validated peptides only" --> doesn't change anything. Nothing starred, and not validated proteins still visible.
- "Edit / Filter" --> process error (tried to filter for Confidence, Validation, etc., using only one parameter or multiple, getting the same error message, see petideShaker-log message below).

What am I missing/doing wrong?

Thank you for your help!

Best regards from Copenhagen,
David

I'm using peptideShaker on OSX with the example data set.
###
Wed Oct 19 17:58:58 CEST 2016: PeptideShaker version 1.13.6.
Memory given to the Java virtual machine: 4750049280.
Total amount of memory in the Java virtual machine: 128974848.
Free memory: 93636840.
Java version: 1.8.0_91.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.8.0_91
os.name: Mac OS X
memory: 54.7/163.1
processors available: 8
useCommandThread: false
java.lang.NullPointerException
	at eu.isas.peptideshaker.filtering.ProteinFilter.isValidated(ProteinFilter.java:101)
	at eu.isas.peptideshaker.filtering.MatchFilter.isValidated(MatchFilter.java:432)
	at eu.isas.peptideshaker.utils.StarHider.isProteinStarred(StarHider.java:814)
	at eu.isas.peptideshaker.utils.StarHider$StarHiderRunnable.run(StarHider.java:1007)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
###

**Comment by dblyon** [comment]
Got the **filters** to **work**.
After some food and a cafe...  It was my mistake. Please excuse my unnecessary question/post.
