### ISSUE TITLE
Issue opening xml file 

### ISSUE THREAD

**Issue by thandie777** [compomics/peptide-shaker#228]
Hi, it is actually my very first time using this software, so I'm sorry if this issue was caused by wrong settings.

I tried doing a research with SearchGUI, using an Agilent raw file previously converted in mzML format. I only selected some databases and submitted the fasta of my protein. The process just stops when peptide shaker seems to be unable to identify the result file from the output. 

This is the log I got:

Mon Nov 21 11:48:20 CET 2016: PeptideShaker version 1.13.6.
Memory given to the Java virtual machine: 3817865216.
Total amount of memory in the Java virtual machine: 163053568.
Free memory: 132766456.
Java version: 1.8.0_111.
java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.<init>(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at com.compomics.software.autoupdater.WebDAO.getLatestVersionNumberFromRemoteRepo(WebDAO.java:34)
	at com.compomics.software.autoupdater.WebDAO.newVersionReleased(WebDAO.java:105)
	at com.compomics.software.CompomicsWrapper.checkForNewDeployedVersion(CompomicsWrapper.java:523)
	at eu.isas.peptideshaker.gui.PeptideShakerGUI.checkForNewVersion(PeptideShakerGUI.java:6900)
	at eu.isas.peptideshaker.gui.PeptideShakerGUI.<init>(PeptideShakerGUI.java:538)
	at eu.isas.peptideshaker.gui.PeptideShakerGUI.main(PeptideShakerGUI.java:479)
jshortcut.dll loaded via tmp generated pathname: C:\Users\\AppData\Local\Temp\jshortcut-6332083266215404298.dll
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.8.0_111
os.name: Windows 8
memory: 50.7/163.1
processors available: 4
useCommandThread: false
Reindexing: uniprot-human-reviewed-trypsin-april-2016_concatenated_target_decoy.fasta. (changes in the file detected)
Reindexing: uniprot-human-reviewed-trypsin-april-2016_concatenated_target_decoy.fasta.
Reindexing: qExactive01819.mgf. (changes in the file detected)
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 10 >= 1
	at java.util.Vector.elementAt(Unknown Source)
	at javax.swing.table.DefaultTableColumnModel.getColumn(Unknown Source)
	at javax.swing.plaf.basic.BasicTableHeaderUI.paint(Unknown Source)
	at javax.swing.plaf.synth.SynthTableHeaderUI.paint(Unknown Source)
	at javax.swing.plaf.synth.SynthTableHeaderUI.update(Unknown Source)
	at javax.swing.JComponent.paintComponent(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintToOffscreen(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
	at javax.swing.RepaintManager.paint(Unknown Source)
	at javax.swing.JComponent._paintImmediately(Unknown Source)
	at javax.swing.JComponent.paintImmediately(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.access$1200(Unknown Source)
	at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.WaitDispatchSupport$2.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

Mon Nov 21 12:10:50 CET 2016: PeptideShaker version 1.13.6.
Memory given to the Java virtual machine: 3817865216.
Total amount of memory in the Java virtual machine: 128974848.
Free memory: 102103480.
Java version: 1.8.0_111.
[Fatal Error] 161116_LC003.t.xml:7607:72: An invalid XML character (Unicode: 0x3) was found in the element content of the document.
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.compomics.util.experiment.io.identifications.IdfileReaderFactory.getFileReader(IdfileReaderFactory.java:137)
	at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importPsms(FileImporter.java:675)
	at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importFiles(FileImporter.java:488)
	at eu.isas.peptideshaker.fileimport.FileImporter.importFiles(FileImporter.java:158)
	at eu.isas.peptideshaker.PeptideShaker.importFiles(PeptideShaker.java:234)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.createProject(PeptideShakerCLI.java:732)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:220)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:945)
Caused by: org.xml.sax.SAXParseException; systemId: file:/C:/Users//Desktop/uni/TESI%20MAGISTRALE/Protocolli%20e%20relativi%20articoli/004/lcmsms%20files/.PeptideShaker_unzip_temp/searchgui_out_PeptideShaker_temp/161116_LC003.t.xml; lineNumber: 7607; columnNumber: 72; An invalid XML character (Unicode: 0x3) was found in the element content of the document.
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at javax.xml.parsers.DocumentBuilder.parse(Unknown Source)
	at de.proteinms.xtandemparser.parser.XTandemParser.parseXTandemFile(XTandemParser.java:158)
	at de.proteinms.xtandemparser.parser.XTandemParser.<init>(XTandemParser.java:116)
	at de.proteinms.xtandemparser.xtandem.XTandemFile.<init>(XTandemFile.java:98)
	at de.proteinms.xtandemparser.parser.XTandemIdfileReader.<init>(XTandemIdfileReader.java:66)
	... 12 more

Mon Nov 21 12:16:11 CET 2016: PeptideShaker version 1.13.6.
Memory given to the Java virtual machine: 3817865216.
Total amount of memory in the Java virtual machine: 163053568.
Free memory: 132569880.
Java version: 1.8.0_111.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.8.0_111
os.name: Windows 8
memory: 50.3/163.1
processors available: 4
useCommandThread: false

Mon Nov 21 12:20:33 CET 2016: PeptideShaker version 1.13.6.
Memory given to the Java virtual machine: 3817865216.
Total amount of memory in the Java virtual machine: 163053568.
Free memory: 132639776.
Java version: 1.8.0_111.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.8.0_111
os.name: Windows 8
memory: 49.8/163.1
processors available: 4
useCommandThread: false
[Fatal Error] 161116_LC003.t.xml:7607:72: An invalid XML character (Unicode: 0x3) was found in the element content of the document.
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.compomics.util.experiment.io.identifications.IdfileReaderFactory.getFileReader(IdfileReaderFactory.java:137)
	at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importPsms(FileImporter.java:675)
	at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importFiles(FileImporter.java:488)
	at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.doInBackground(FileImporter.java:442)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.xml.sax.SAXParseException; systemId: file:/C:/Users//Desktop/uni/TESI%20MAGISTRALE/Protocolli%20e%20relativi%20articoli/004/lcmsms%20files/.PeptideShaker_unzip_temp/searchgui_out_PeptideShaker_temp/161116_LC003.t.xml; lineNumber: 7607; columnNumber: 72; An invalid XML character (Unicode: 0x3) was found in the element content of the document.
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at javax.xml.parsers.DocumentBuilder.parse(Unknown Source)
	at de.proteinms.xtandemparser.parser.XTandemParser.parseXTandemFile(XTandemParser.java:158)
	at de.proteinms.xtandemparser.parser.XTandemParser.<init>(XTandemParser.java:116)
	at de.proteinms.xtandemparser.xtandem.XTandemFile.<init>(XTandemFile.java:98)
	at de.proteinms.xtandemparser.parser.XTandemIdfileReader.<init>(XTandemIdfileReader.java:66)
	... 14 more

**Comment by hbarsnes** [comment]
Hi,

It seems like you have some non-standard characters in your file names (or in the folders containing the files)? This results in search engine result files that cannot be parsed. Try removing any non-standard characters and redo the processing. Hopefully this will fix the problem.

If this is not the case, it would be great if you could make the X! Tandem output file available to us so that we can try to locate the problem that way?

Best regards,
Harald

**Comment by thandie777** [comment]
Thank you for replying so fast!

You mean I should attach the  searchGUI.log? I'll attach it right away here at the bottom. I couldn't locate a specific X!Tandem log. Could you let me know, in case, where it is?

I'm not sure how to locate the character in the XML that interrupts the process. How should I proceed?

jshortcut.dll loaded via tmp generated pathname: C:\Users\lucia\AppData\Local\Temp\jshortcut-749722158155610012.dll
Reindexing: aox1-fasta.fasta.
Reindexing: aox1-fasta_concatenated_target_decoy.fasta.


makeblastdb command: 
C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\software\SearchGUI-3.1.4\resources\makeblastdb\windows\makeblastdb -in aox1-fasta_concatenated_target_decoy.fasta -dbtype prot 



tide index command: 
C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\software\SearchGUI-3.1.4\resources\Tide\windows\windows_64bit\crux tide-index C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\Proteomica\aox1-fasta_concatenated_target_decoy.fasta fasta-index --overwrite T --decoy-format none --missed-cleavages 2 --output-dir crux-output --peptide-list F --verbosity 30 --min-length 6 --max-length 30 --min-mass 200.0 --max-mass 7200.0 --isotopic-mass mono --clip-nterm-methionine F --enzyme trypsin --digestion full-digest 



msconvert command: 
"C:\Program Files\ProteoWizard\ProteoWizard 3.0.10200\msconvert" "C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\Protocolli e relativi articoli\004\lcmsms files\161116_LC003.mzML" --mgf -o "C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\Protocolli e relativi articoli\004\lcmsms files" --outfile 161116_LC003.mgf -v --filter "peakPicking " 



xtandem command: 
C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\software\SearchGUI-3.1.4\resources\XTandem\windows\windows_64bit\tandem C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\software\SearchGUI-3.1.4\resources\XTandem\windows\windows_64bit\input_searchGUI.xml 



myrimatch command: 
C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\software\SearchGUI-3.1.4\resources\MyriMatch\windows\windows_64bit\myrimatch -cpus 4 -ProteinDatabase "C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\Proteomica\aox1-fasta_concatenated_target_decoy.fasta" "C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\Protocolli e relativi articoli\004\lcmsms files\161116_LC003.mgf" -OutputFormat mzIdentML -workdir "C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\Protocolli e relativi articoli\004\lcmsms files\.SearchGUI_temp" -OutputSuffix .myrimatch -DecoyPrefix "" -MinPeptideLength 8 -MaxPeptideLength 30 -MaxResultRank 10 -SpectrumListFilters "" -FragmentMzTolerance "2.0 daltons" -MonoPrecursorMzTolerance "20.0 ppm" -PrecursorMzToleranceRule "mono" -MaxDynamicMods 2 -StatusUpdateFrequency 10 -NumChargeStates 4+ -TicCutoffPercentage 0.98 -MinPeptideMass 600.0 -MaxPeptideMass 5000.0 -UseSmartPlusThreeModel true -ComputeXCorr false -NumIntensityClasses 3 -ClassSizeMultiplier 2 -NumBatches 50 -MaxPeakCount 300 -MonoisotopeAdjustmentSet [0,1] -FragmentationAutoRule false -FragmentationRule "cid" -CleavageRules "Trypsin" -MinTerminiCleavages 2 -MaxMissedCleavages 2 



ms amanda command: 
C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\software\SearchGUI-3.1.4\resources\MS Amanda\windows\MSAmanda.exe "C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\Protocolli e relativi articoli\004\lcmsms files\161116_LC003.mgf" "C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\Proteomica\aox1-fasta_concatenated_target_decoy.fasta" "C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\software\SearchGUI-3.1.4\resources\MS Amanda\windows\settings_SearchGUI.xml" "C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\Protocolli e relativi articoli\004\lcmsms files\.SearchGUI_temp\161116_LC003.ms-amanda.csv" 



ms-gf+ command: 
"C:\Program Files\Java\jre1.8.0_111\bin\java" -Xms128M -Xmx4096M -jar "C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\software\SearchGUI-3.1.4\resources\MS-GF+\MSGFPlus.jar" -s "C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\Protocolli e relativi articoli\004\lcmsms files\161116_LC003.mgf" -d "C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\Proteomica\aox1-fasta_concatenated_target_decoy.fasta" -o "C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\Protocolli e relativi articoli\004\lcmsms files\.SearchGUI_temp\161116_LC003.msgf.mzid" -t 20.0ppm -tda 0 -mod "C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\software\SearchGUI-3.1.4\resources\MS-GF+\params\Mods.txt" -minCharge 2 -maxCharge 4 -inst 3 -thread 4 -m 3 -e 1 -ntt 2 -protocol 0 -minLength 8 -maxLength 30 -n 10 -addFeatures 0 -ti "0,1" 



omssa command: 
C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\software\SearchGUI-3.1.4\resources\OMSSA\windows\omssacl -w -to 2.0 -te 20.0 -teppm -e 0 -zl 2 -zh 4 -zt 3 -ti 1 -tex 1446.94 -cl 0.0 -ch 0.2 -ci 5.0E-4 -w1 27 -w2 14 -h1 2 -h2 2 -hl 30 -hc 30 -hm 2 -hs 4 -ht 6 -mm 128 -zoh 2 -z1 0.95 -pc 1 -sb1 0 -sp 100 -scorp 0.5 -is 0.0 -ir 0.0 -ii 0.01 -v 2 -he 100.0 -tez 1 -zcc 2 -cp 0 -no 8 -nox 30 -tom 0 -tem 0 -i 1,4 -d aox1-fasta_concatenated_target_decoy.fasta -fm C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\Protocolli e relativi articoli\004\lcmsms files\161116_LC003.mgf -ox "C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\Protocolli e relativi articoli\004\lcmsms files\.SearchGUI_temp\161116_LC003.omx" -nt 4 



comet command: 
C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\software\SearchGUI-3.1.4\resources\Comet\windows\windows_64bit\comet.exe C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\Protocolli e relativi articoli\004\lcmsms files\161116_LC003.mgf 



tide search command: 
C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\software\SearchGUI-3.1.4\resources\Tide\windows\windows_64bit\crux tide-search --compute-sp F C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\software\SearchGUI-3.1.4\resources\temp\peak_lists\161116_LC003.ms2 fasta-index --overwrite T --top-match 10 --precursor-window 20.0 --precursor-window-type ppm --fileroot 161116_LC003 --exact-p-value F --output-dir crux-output --spectrum-min-mz 0.0 --min-peaks 20 --spectrum-charge all --max-precursor-charge 4 --remove-precursor-peak F --remove-precursor-tolerance 1.5 --print-search-progress 1000 --use-flanking-peaks F --use-neutral-loss-peaks F --mz-bin-width 0.02 --mz-bin-offset 0.0 --num-threads 4 --concat F --txt-output T --sqt-output F --pepxml-output F --mzid-output F --pin-output F --verbosity 30 



andromeda command: 
C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\software\SearchGUI-3.1.4\resources\Andromeda\windows\AndromedaCmd.exe -i C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\software\SearchGUI-3.1.4\resources\temp\peak_lists\161116_LC003.apl -p C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\software\SearchGUI-3.1.4\resources\Andromeda\windows\temp\trypsin digest.apar -f C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\software\SearchGUI-3.1.4\resources\Andromeda\windows\temp -n 4 -s FALSE 



PeptideShaker command: 
"C:\Program Files\Java\jre1.8.0_111\bin\java" -Xms128M -Xmx4096M -cp PeptideShaker-1.13.6.jar eu.isas.peptideshaker.cmd.PeptideShakerCLI -experiment digest aox1 -sample aox-1 digest 2th ptotocol -replicate 0 -identification_files "C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\Protocolli e relativi articoli\004\lcmsms files\searchgui_out.zip" -spectrum_files "C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\Protocolli e relativi articoli\004\lcmsms files\161116_LC003.mgf" -id_params "C:\Users\lucia\.compomics\identification_parameters\trypsin digest.par" -out "C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\Protocolli e relativi articoli\004\lcmsms files\PeptideShaker_output.cpsx" -gui 1 



makeblastdb command: 
C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\software\SearchGUI-3.1.4\resources\makeblastdb\windows\makeblastdb -in aox1-fasta_concatenated_target_decoy.fasta -dbtype prot 



xtandem command: 
C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\software\SearchGUI-3.1.4\resources\XTandem\windows\windows_64bit\tandem C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\software\SearchGUI-3.1.4\resources\XTandem\windows\windows_64bit\input_searchGUI.xml 



omssa command: 
C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\software\SearchGUI-3.1.4\resources\OMSSA\windows\omssacl -w -to 2.0 -te 20.0 -teppm -e 0 -zl 2 -zh 4 -zt 3 -ti 1 -tex 1446.94 -cl 0.0 -ch 0.2 -ci 5.0E-4 -w1 27 -w2 14 -h1 2 -h2 2 -hl 30 -hc 30 -hm 2 -hs 4 -ht 6 -mm 128 -zoh 2 -z1 0.95 -pc 1 -sb1 0 -sp 100 -scorp 0.5 -is 0.0 -ir 0.0 -ii 0.01 -v 2 -he 100.0 -tez 1 -zcc 2 -cp 0 -no 8 -nox 30 -tom 0 -tem 0 -i 1,4 -d aox1-fasta_concatenated_target_decoy.fasta -fm C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\Protocolli e relativi articoli\004\lcmsms files\161116_LC003.mgf -ox "C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\Protocolli e relativi articoli\004\lcmsms files\.SearchGUI_temp\161116_LC003.omx" -nt 4 



andromeda command: 
C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\software\SearchGUI-3.1.4\resources\Andromeda\windows\AndromedaCmd.exe -i C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\software\SearchGUI-3.1.4\resources\temp\peak_lists\161116_LC003.apl -p C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\software\SearchGUI-3.1.4\resources\Andromeda\windows\temp\trypsin digest.apar -f C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\software\SearchGUI-3.1.4\resources\Andromeda\windows\temp -n 4 -s FALSE 



xtandem command: 
C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\software\SearchGUI-3.1.4\resources\XTandem\windows\windows_64bit\tandem C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\software\SearchGUI-3.1.4\resources\XTandem\windows\windows_64bit\input_searchGUI.xml 



omssa command: 
C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\software\SearchGUI-3.1.4\resources\OMSSA\windows\omssacl -w -to 2.0 -te 20.0 -teppm -e 0 -zl 2 -zh 4 -zt 3 -ti 1 -tex 1446.94 -cl 0.0 -ch 0.2 -ci 5.0E-4 -w1 27 -w2 14 -h1 2 -h2 2 -hl 30 -hc 30 -hm 2 -hs 4 -ht 6 -mm 128 -zoh 2 -z1 0.95 -pc 1 -sb1 0 -sp 100 -scorp 0.5 -is 0.0 -ir 0.0 -ii 0.01 -v 2 -he 100.0 -tez 1 -zcc 2 -cp 0 -no 8 -nox 30 -tom 0 -tem 0 -i 1,4 -d aox1-fasta_concatenated_target_decoy.fasta -fm C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\Protocolli e relativi articoli\004\lcmsms files\161116_LC003.mgf -ox "C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\Protocolli e relativi articoli\004\lcmsms files\.SearchGUI_temp\161116_LC003.omx" -nt 4 



andromeda command: 
C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\software\SearchGUI-3.1.4\resources\Andromeda\windows\AndromedaCmd.exe -i C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\software\SearchGUI-3.1.4\resources\temp\peak_lists\161116_LC003.apl -p C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\software\SearchGUI-3.1.4\resources\Andromeda\windows\temp\trypsin digest.apar -f C:\Users\lucia\Desktop\uni\TESI MAGISTRALE\software\SearchGUI-3.1.4\resources\Andromeda\windows\temp -n 4 -s FALSE 

Thank you so much for your help.

**Comment by hbarsnes** [comment]
> I'm not sure how to locate the character in the XML that interrupts the process. How should I proceed?

Try opening the X! Tandem results file called 161116_LC003.t.xml in a text editor that has line numbers. The error occurs on line 7607 at character 72:

> 161116_LC003.t.xml:7607:72: An invalid XML character (Unicode: 0x3) was found in the element content of the document.

You could also send me the file and I can try to locate the problem for you.

Best regards,
Harald

**Comment by thandie777** [comment]
I didn't think of using a text editor! I spotted the character and corrected it and then reimported the file. Everything worked like a charm.

Thank you so much for your help!

**Comment by hbarsnes** [comment]
> I didn't think of using a text editor! I spotted the character and corrected it and then reimported the file. Everything worked like a charm.

Great! Happy to help.

Best regards,
Harald
