### ISSUE TITLE
More sites than PTMs on peptide 

### ISSUE THREAD

**Issue by vladie0** [compomics/peptide-shaker#231]
Dear Developers, 

Using PeptideShaker I've encoutered the folowing issue when processing output from searchGUI:
I can supply the search GUI and project files if necessary

10% 20% 30% 40% 50% 60%<CompomicsError>PeptideShaker processing failed. See the PeptideShaker log for details.</CompomicsError>

Thu Dec 01 14:56:34 CET 2016 An error occurred while loading the identification files:
Thu Dec 01 14:56:34 CET 2016 More sites than PTMs on peptide MSINQKVSYIQSFIVK_42.0105646837_42.0105646837-ATAA-1 for PTM of mass 42.0105646837.
java.lang.IllegalArgumentException: More sites than PTMs on peptide MSINQKVSYIQSFIVK_42.0105646837_42.0105646837-ATAA-1 for PTM of mass 42.0105646837.
        at eu.isas.peptideshaker.ptm.PtmScorer.scorePTMs(PtmScorer.java:952)
        at eu.isas.peptideshaker.ptm.PtmScorer.scorePeptidePtms(PtmScorer.java:1482)
        at eu.isas.peptideshaker.PeptideShaker.processIdentifications(PeptideShaker.java:496)
        at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importFiles(FileImporter.java:559)
        at eu.isas.peptideshaker.fileimport.FileImporter.importFiles(FileImporter.java:158)
        at eu.isas.peptideshaker.PeptideShaker.importFiles(PeptideShaker.java:234)
        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.createProject(PeptideShakerCLI.java:732)
        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:220)
        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:945)

Is there a way to fix this issue ? 
Thanks in advance, 
Volodimir Olexiouk

**Comment by mvaudel** [comment]
Hi Volodimir,

sorry to hear that you are encountering an issue with the tool. This error generally comes from conflicting PTM sites during localization scoring, where the tool gets confused and tries to assign multiple sites to the same ptm. Here it seems that the tool is struggling with possible acetylation sites, most likely attempting to create a peptide and protein terminal acetylation at the same time. It should prioritize one over the other but somehow fails on your dataset.

If the project is not too big it would be great if you could share it with us so that I can look into it.

Best regards,

Marc

**Comment by vladie0** [comment]
Thank you for your quick reply,
The following zip file should contain all files to process the project with peptideshaker
[peptideshaker_error.zip](https://github.com/compomics/peptide-shaker/files/627050/peptideshaker_error.zip)

Regards, 
Volodimir Olexiouk

**Comment by hbarsnes** [comment]
Hi Volodimir,

Loading your data works fine in the latest PeptideShaker release. Please update to the latest version and see if that solves the problem on your end as well? If not, please let us know and we'll reopen the issue.

Best regards,
Harald
