### ISSUE TITLE
Duplicate peptide Error

### ISSUE THREAD

**Issue by Thys3Potgieter** [compomics/peptide-shaker#232]
Hi Marc and Harald,

Sorry for the duplicate post, I realize here is a better place for this than the google group.

We are  attempting to process 60 raw files with SearchGUI (3.1.4) and PeptideShaker (1.13.6).

Only two MGF's wont process, however we have managed to process all the files with a previous version. We are using a metaproteomics database with UniProt entries.

I am doing a semi-tryptic search at 5% FDR for each sample separately.
Your help will be appreciated,
Kind regards
Thys

Here is standard output:
Wed Nov 30 14:53:34 SAST 2016 Scoring Peptide PTMs. Please Wait...

10% 20%<CompomicsError>PeptideShaker processing failed. See the PeptideShaker log for details.</CompomicsError>

Wed Nov 30 14:53:35 SAST 2016 An error occurred while loading the identification files:

Wed Nov 30 14:53:35 SAST 2016 Attempting to create duplicate peptide key: AMKDEEKMEIQEMQIK_15.99491461956_15.99491461956-ATAA-13 from peptide AMKDEEKMEIQEMQIK_15.99491461956-ATAA-13_15.99491461956-ATAA-8.

Wed Nov 30 14:53:37 SAST 2016 PeptideShaker Processing Canceled.

<CompomicsError>PeptideShaker processing canceled. See the PeptideShaker log for details.</CompomicsError>

Here is standard error:
java.lang.IllegalArgumentException: Query error: Query ERROR: caught BioMart::Exception::Usage: WITHIN Virtual Schema : default, Dataset pgraminisug99_eg_gene NOT FOUND

        at com.compomics.util.experiment.biology.genes.GeneFactory.queryEnsembl(GeneFactory.java:487)

        at com.compomics.util.experiment.biology.genes.GeneFactory.downloadGoMappings(GeneFactory.java:382)

        at com.compomics.util.experiment.biology.genes.GeneFactory.downloadMappings(GeneFactory.java:923)

        at com.compomics.util.experiment.biology.genes.GeneFactory.getGeneMaps(GeneFactory.java:167)

        at eu.isas.peptideshaker.fileimport.FileImporter.importGenes(FileImporter.java:282)

        at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importFiles(FileImporter.java:465)

        at eu.isas.peptideshaker.fileimport.FileImporter.importFiles(FileImporter.java:158)

        at eu.isas.peptideshaker.PeptideShaker.importFiles(PeptideShaker.java:234)

        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.createProject(PeptideShakerCLI.java:732)

        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:220)

        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:945)

java.lang.IllegalArgumentException: Attempting to create duplicate peptide key: AMKDEEKMEIQEMQIK_15.99491461956_15.99491461956-ATAA-13 from peptide AMKDEEKMEIQEMQIK_15.99491461956-ATAA-13_15.99491461956-ATAA-8.

        at eu.isas.peptideshaker.ptm.PtmScorer.scorePTMs(PtmScorer.java:974)

        at eu.isas.peptideshaker.ptm.PtmScorer.scorePeptidePtms(PtmScorer.java:1482)

        at eu.isas.peptideshaker.PeptideShaker.processIdentifications(PeptideShaker.java:496)

        at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importFiles(FileImporter.java:559)

        at eu.isas.peptideshaker.fileimport.FileImporter.importFiles(FileImporter.java:158)

        at eu.isas.peptideshaker.PeptideShaker.importFiles(PeptideShaker.java:234)

        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.createProject(PeptideShakerCLI.java:732)

        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:220)

        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:945)

**Comment by mvaudel** [comment]
Hi Thys,

The first error seems to be related to the query of some species in Biomart, I will improve the handling of the error. The second is one I am struggling with since quite some time (see https://github.com/compomics/peptide-shaker/issues/56). I will keep you updated if I find a fix. In the meantime you can try to edit your identification parameters and set _-ptm_alignment_ to 0. If it does not work you can try to remove the PTM probabilistic scoring altogether using _-ptm_score 2_. Hopefully this will circumvent the problem until I come up with a proper fix.

Apologies for the inconvenience,

Marc

**Comment by Thys3Potgieter** [comment]
Hi Marc, no problem, thanks for the fast response! Il try those settings. 
Kind regards,
Thys

**Comment by hbarsnes** [comment]
Hi Thys,

The BioMart issue should be fixed in the latest PeptideShaker release. As mentioned above, the "Attempting to create duplicate peptide key" as a known problem, so please see #56 for further followup on this one.

Best regards,
Harald
