### ISSUE TITLE
ERROR: more sites than PTM's 

### ISSUE THREAD

**Issue by vladie0** [compomics/peptide-shaker#256]
Dear developers, 

The following error (or a similar one) occures in several project I tried to process:

10% 20% 30%<CompomicsError>PeptideShaker processing failed. See the PeptideShaker log for details.</CompomicsError>

Mon Mar 27 10:23:17 CEST 2017 An error occurred while loading the identification files:
Mon Mar 27 10:23:17 CEST 2017 More sites than PTMs on peptide MVDDWDEEFDRGK_42.0105646837-ATAA-1 for PTM of mass 42.0105646837.
java.lang.IllegalArgumentException: More sites than PTMs on peptide MVDDWDEEFDRGK_42.0105646837-ATAA-1 for PTM of mass 42.0105646837.
        at eu.isas.peptideshaker.ptm.PtmScorer.scorePTMs(PtmScorer.java:936)
        at eu.isas.peptideshaker.ptm.PtmScorer.scorePeptidePtms(PtmScorer.java:1466)
        at eu.isas.peptideshaker.PeptideShaker.processIdentifications(PeptideShaker.java:490)
        at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importFiles(FileImporter.java:548)
        at eu.isas.peptideshaker.fileimport.FileImporter.importFiles(FileImporter.java:152)
        at eu.isas.peptideshaker.PeptideShaker.importFiles(PeptideShaker.java:229)
        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.createProject(PeptideShakerCLI.java:750)
        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:221)
        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:950)
Free memory: 13850775672

I have created a zip file containing all the necessary files to reproduce the error, available here:
https://drive.google.com/open?id=0B3z-MmiBk77oTkdkMzFxZFBXQnc

The command line arguments I use are:
java -Xmx70G -cp software/PeptideShaker-1.16.3/PeptideShaker-1.16.3.jar eu.isas.peptideshaker.cmd.PeptideShakerCLI -experiment 63415 -sample 63415 -replicate 0 -identification_files temp/searchgui_out.zip -spectrum_files temp/export_mgf/ -id_params temp/second_search.par -threads 25 -out temp/secondSearch.cpsx

Note:
This error occurs with PeptideShaker version 1.16.2 and 1.16.3, HOWEVER, it does not occurs in PeptideShaker version 1.14.4. I assume that this error has been re-introduces as it occured prior to peptideshaker 1.14

**Comment by mvaudel** [comment]
Hi Volodimir,

Sorry for the delay of my answer. It seems that the tool is having issues localizing your PTM (acetylation). I will try to reproduce it on my side and come up with a fix.

Apologies for the inconvenience,

Marc

**Comment by vladie0** [comment]
Thank you for looking into this !
I'm also (quite frequently ) encountering the following error:
Fri Apr 07 05:33:33 CEST 2017 Unzipping searchgui_out.zip.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%

Fri Apr 07 05:34:03 CEST 2017 Import process for 18485 (Sample: 18485, Replicate: 0)

Fri Apr 07 05:34:03 CEST 2017 Importing sequences from Uni_sorfs_target_decoy.fasta.
<CompomicsError>PeptideShaker processing failed. See the PeptideShaker log for details.</CompomicsError>
Fri Apr 07 05:34:05 CEST 2017 An error occurred while loading the identification files:
Fri Apr 07 05:34:05 CEST 2017 null
java.lang.UnsupportedOperationException
        at com.compomics.util.experiment.identification.protein_inference.fm_index.FMIndex.<init>(FMIndex.java:305)
        at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.getDefaultPeptideMapper(SequenceFactory.java:1437)
        at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.getDefaultPeptideMapper(SequenceFactory.java:1371)
        at eu.isas.peptideshaker.fileimport.FileImporter.importSequences(FileImporter.java:208)
        at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importFiles(FileImporter.java:442)
        at eu.isas.peptideshaker.fileimport.FileImporter.importFiles(FileImporter.java:151)
        at eu.isas.peptideshaker.PeptideShaker.importFiles(PeptideShaker.java:229)
        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.createProject(PeptideShakerCLI.java:731)
        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:219)
        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:931)
Free memory: 1502129432
Fri Apr 07 05:34:06 CEST 2017 PeptideShaker Processing Canceled.

Do you recognize this error ? It may be caused by using an older PeptideShaker version (1.14.4), so i'll wait till the error above is fixed before investigating further.

Thank you,
Volodimir Olexiouk

**Comment by hbarsnes** [comment]
Hi Volodimir,

> Do you recognize this error ? It may be caused by using an older PeptideShaker version (1.14.4), so i'll wait till the error above is fixed before investigating further.

This looks like an issue that was solved in more recent versions of PeptideShaker. Would be great if you could test with the latest version to see if you still get the error?

Best regards,
Harald

**Comment by vladie0** [comment]
Sorry for the late reply, 
The issue seems to be fixed, thank you

**Comment by lcscs12345** [comment]
Hi, I got this error only when parsing the X! Tandem search results (SearchGUI-3.2.20) using PeptideShaker-1.16.12. No problem using Comet and MSGF+ search results of the same mgf files (~300MB each).

`More sites than PTMs on peptide MQIQVAIIAKKY_42.0105646837_42.0105646837-ATAA-1 for PTM of mass 42.0105646837`

**Comment by hbarsnes** [comment]
> Hi, I got this error only when parsing the X! Tandem search results (SearchGUI-3.2.20) using PeptideShaker-1.16.12. No problem on Comet and MSGF+ search results of the same mgf files (~300MB each).
More sites than PTMs on peptide MQIQVAIIAKKY_42.0105646837_42.0105646837-ATAA-1 for PTM of mass 42.0105646837

We are currently refactoring this part of the code. Please check back when the new version becomes available in the (hopefully) not too distant future.

Best regards,
Harald
