### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by wenbostar** [compomics/peptide-shaker#263]
Hi,

When I tried to import an mzid file from MS-GF+ into PeptideShake, I got the error as shown below. Does anyone know what the problem is?
`
<CompomicsError>PeptideShaker processing failed. See the PeptideShaker log for details.</CompomicsError>
java.lang.NullPointerException
	at com.compomics.util.db.ObjectsCache.addObject(ObjectsCache.java:313)
	at com.compomics.util.db.ObjectsDB.loadObjects(ObjectsDB.java:843)
	at com.compomics.util.db.ObjectsDB.loadObjects(ObjectsDB.java:737)
	at com.compomics.util.experiment.identification.IdentificationDB.loadSpectrumMatches(IdentificationDB.java:858)
	at com.compomics.util.experiment.identification.Identification.loadSpectrumMatches(Identification.java:241)
	at com.compomics.util.experiment.identification.matches_iterators.PsmIterator.checkBuffer(PsmIterator.java:280)
	at com.compomics.util.experiment.identification.matches_iterators.PsmIterator.next(PsmIterator.java:241)
	at eu.isas.peptideshaker.PeptideShaker.attachAssumptionsProbabilities(PeptideShaker.java:680)
	at eu.isas.peptideshaker.PeptideShaker.processIdentifications(PeptideShaker.java:324)
	at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importFiles(FileImporter.java:548)
	at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.doInBackground(FileImporter.java:432)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Free memory: 432921848
`
Best regards!
Bo

**Comment by hbarsnes** [comment]
Hi Bo,

Does the MS-GF+ mzid file come from SearchGUI or has the search been run independently? And does it happen with only this files or with other MS-GF+ mzid files as well?

Would it be possible for you to make the mzid file (plus the other files required to load the data in PeptideShaker, i.e. FASTA, mgf and search settings) available to us so that we can try to reproduce the issue on our end?

Best regards,
Harald

**Comment by hbarsnes** [comment]
Issue assume resolved. If this is not the case, please let us know and we'll reopen the issue.
