### ISSUE TITLE
Re-occuring peptideshaker error

### ISSUE THREAD

**Issue by vladie0** [compomics/peptide-shaker#265]
Dear Developers, 

I'm processing a large batch of projects from PRIDE and found an reoccuring error in >10% of all datasets (projects). The error message is pasted below:

Tue May 23 11:02:01 CEST 2017 Importing sequences from Uni_sorfs_target_decoy.fasta.
<CompomicsError>PeptideShaker processing failed. See the PeptideShaker log for details.</CompomicsError>
Tue May 23 11:02:03 CEST 2017 An error occurred while loading the identification files:
Tue May 23 11:02:03 CEST 2017 Index: 0, Size: 0
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at com.compomics.util.experiment.identification.protein_inference.fm_index.FMIndex.init(FMIndex.java:472)
        at com.compomics.util.experiment.identification.protein_inference.fm_index.FMIndex.<init>(FMIndex.java:386)
        at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.getDefaultPeptideMapper(SequenceFactory.java:1448)
        at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.getDefaultPeptideMapper(SequenceFactory.java:1381)
        at eu.isas.peptideshaker.fileimport.FileImporter.importSequences(FileImporter.java:209)
        at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importFiles(FileImporter.java:443)
        at eu.isas.peptideshaker.fileimport.FileImporter.importFiles(FileImporter.java:152)
        at eu.isas.peptideshaker.PeptideShaker.importFiles(PeptideShaker.java:229)
        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.createProject(PeptideShakerCLI.java:735)
        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:218)
        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:935)
Free memory: 2031690344
Tue May 23 11:02:04 CEST 2017 PeptideShaker Processing Canceled.
<CompomicsError>PeptideShaker processing canceled. See the PeptideShaker log for details.</CompomicsError>

Processing with searchGUI was succesful, however, in more than 10% of cases this error pops up when attempting to run peptideshaker.

Would you happen to know the underlying cause of this ? 
Thank you in advance

**Comment by dominik-kopczynski** [comment]
Hi Volodimir,

Thank you for your massage and sorry that the error occurs during your computation. Its seems to me, that the indexing has some problems either with your fasta file or with your parameters. Is it possible to provide me both the *.fasta and *.par file, so I can check quickly, what is going wrong? Thank you and sorry for inconvenience.

Cheers,
Dominik

**Comment by vladie0** [comment]
I will rerun a particular project where this error occurs and provide all the files. This may take me a couple of days, I will keep you up to date

**Comment by hbarsnes** [comment]
Hi Volodimir,

Any progress on this one? Has the problem been resolved so that we can close the issue?

Best regards,
Harald

**Comment by hbarsnes** [comment]
Issue assumed resolved. If this is not the case, please let us know and we'll reopen the issue.
