### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by kimstellies** [compomics/peptide-shaker#266]
Hi

When it try to load search results from searchGUI into peptide shaker i get this error and it won't load any data.  Any ideas how i should proceed?

Thanks
Kim

Wed May 24 15:09:50 CAT 2017: PeptideShaker version 1.16.9.
Memory given to the Java virtual machine: 1037959168.
Total amount of memory in the Java virtual machine: 129761280.
Free memory: 95251760.
Java version: 1.8.0_131.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.8.0_131
os.name: Windows 7
memory: 21.8/129.9
processors available: 8
useCommandThread: false
<CompomicsError>PeptideShaker processing failed. See the PeptideShaker log for details.</CompomicsError>
java.lang.NullPointerException
	at com.compomics.util.db.ObjectsCache.addObject(ObjectsCache.java:313)
	at com.compomics.util.db.ObjectsDB.loadObjects(ObjectsDB.java:843)
	at com.compomics.util.db.ObjectsDB.loadObjects(ObjectsDB.java:737)
	at com.compomics.util.experiment.identification.IdentificationDB.loadSpectrumMatches(IdentificationDB.java:858)
	at com.compomics.util.experiment.identification.Identification.loadSpectrumMatches(Identification.java:241)
	at com.compomics.util.experiment.identification.matches_iterators.PsmIterator.checkBuffer(PsmIterator.java:280)
	at com.compomics.util.experiment.identification.matches_iterators.PsmIterator.next(PsmIterator.java:241)
	at eu.isas.peptideshaker.PeptideShaker.attachAssumptionsProbabilities(PeptideShaker.java:680)
	at eu.isas.peptideshaker.PeptideShaker.processIdentifications(PeptideShaker.java:324)
	at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importFiles(FileImporter.java:548)
	at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.doInBackground(FileImporter.java:432)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Free memory: 448625896
<CompomicsError>PeptideShaker processing failed. See the PeptideShaker log for details.</CompomicsError>
java.lang.NullPointerException
	at com.compomics.util.db.ObjectsCache.addObject(ObjectsCache.java:313)
	at com.compomics.util.db.ObjectsDB.loadObjects(ObjectsDB.java:843)
	at com.compomics.util.db.ObjectsDB.loadObjects(ObjectsDB.java:737)
	at com.compomics.util.experiment.identification.IdentificationDB.loadSpectrumMatches(IdentificationDB.java:858)
	at com.compomics.util.experiment.identification.Identification.loadSpectrumMatches(Identification.java:241)
	at com.compomics.util.experiment.identification.matches_iterators.PsmIterator.checkBuffer(PsmIterator.java:280)
	at com.compomics.util.experiment.identification.matches_iterators.PsmIterator.next(PsmIterator.java:241)
	at eu.isas.peptideshaker.PeptideShaker.attachAssumptionsProbabilities(PeptideShaker.java:680)
	at eu.isas.peptideshaker.PeptideShaker.processIdentifications(PeptideShaker.java:324)
	at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importFiles(FileImporter.java:548)
	at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.doInBackground(FileImporter.java:432)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Free memory: 450240912

**Comment by hbarsnes** [comment]
Hi Kim,

Thanks for telling us about this. Would it be possible for you to share the data your are trying to load in PeptideShaker so that we can try to reproduce the error on our side? We'll need the SearchGUI output, plus the mgf and FASTA file.

Best regards,
Harald

**Comment by kimstellies** [comment]
Hi Harald
See fasta database file.

[uniprot-taxonomyGmoniliformisexpand_crap_24052017.txt](https://github.com/compomics/peptide-shaker/files/1025842/uniprot-taxonomyGmoniliformisexpand_crap_24052017.txt)

**Comment by kimstellies** [comment]
Hi Harald

Thanks for your quick response.  I am unable to email you the mgf (75 MB) and searchGUI (37 MB) output even though they are zipped.  I also tried to upload to github but it won’t work.  I did upload the fasta database file. How else can I send them?

Regards,
Kim

**Comment by hbarsnes** [comment]
Hi Kim,

>  I am unable to email you the mgf (75 MB) and searchGUI (37 MB) output even though they are zipped.

I would recommend using something like DropBox and share the link. Is that an option for you?

Best regards,
Harald

**Comment by kimstellies** [comment]
https://www.dropbox.com/sh/on7fzm4imhi1v84/AABJVTZiX-HtqoRNEpjjxqC0a?dl=0

**Comment by hbarsnes** [comment]
Hi Kim,

Thanks for the data. I can load them without any problems on my end though. Could you try reloading the data to see if that solves the problem? In other words, if it's a reproducible issue or not?

Also, is there anything special with the setup of the computer your are using to load the data? For example, do you have any of the data on a network drive?

Best regards,
Harald

**Comment by kimstellies** [comment]
Hi Harald

I tried to load the data twice before contacting you. Same outcome. I am not at work tomorrow but will retry on Friday. All files on local disc. 

Thanks 
Kim

**Comment by kimstellies** [comment]
Hi Harald

I tried to load the data twice before contacting you. Same outcome. I am not at work tomorrow but will retry on Friday. All files on local disc. 

Thanks 
Kim

**Comment by kimstellies** [comment]
Hi Harald
I thought it might be resolved after restarting the computer but i still have had no luck - importing cancelled.  I again tried twice.  I pasted the logs below.  I will try it on another sample so long.

Kim

Fri May 26 11:55:33 CAT 2017        Import process for lmdatan (Sample: e1, Replicate: 0)

Fri May 26 11:55:33 CAT 2017        Importing sequences from uniprot-taxonomyGmoniliformisexpand_crap_24052017_concatenated_target_decoy.fasta.
Fri May 26 11:56:02 CAT 2017        FASTA file import completed.
Fri May 26 11:56:02 CAT 2017        Importing gene mappings.
Fri May 26 11:56:02 CAT 2017            Maize ear and stalk rot fungus (Gibberella moniliformis) not available in Ensembl. Gene and GO annotation for this species will not be available.
Fri May 26 11:56:04 CAT 2017        Establishing local database connection.
Fri May 26 11:56:06 CAT 2017        Reading identification files.
Fri May 26 11:56:06 CAT 2017        Parsing ML_2017-03-02_E1_14.msgf.mzid.
Fri May 26 11:56:28 CAT 2017        Loading spectra for ML_2017-03-02_E1_14.msgf.mzid.
Fri May 26 11:56:28 CAT 2017        Importing ML_2017-03-02_E1_14.mgf
Fri May 26 11:56:28 CAT 2017        ML_2017-03-02_E1_14.mgf imported.
Fri May 26 11:56:28 CAT 2017        Importing PSMs from ML_2017-03-02_E1_14.msgf.mzid
Fri May 26 11:57:39 CAT 2017        Parsing ML_2017-03-02_E1_14.t.xml.
Fri May 26 11:59:03 CAT 2017        Loading spectra for ML_2017-03-02_E1_14.t.xml.
Fri May 26 11:59:03 CAT 2017        Importing PSMs from ML_2017-03-02_E1_14.t.xml
Fri May 26 11:59:19 CAT 2017        PeptideShaker is encountering memory issues! See http://compomics.github.io/projects/peptide-shaker.html for help.
Fri May 26 11:59:19 CAT 2017        Reducing Memory Consumption.
Fri May 26 12:00:22 CAT 2017        4213 identified spectra (15.9%) did not present a valid peptide.
Fri May 26 12:00:22 CAT 2017        5973 of the best scoring peptides were excluded by the import filters:
Fri May 26 12:00:22 CAT 2017            - 29.4% peptide length less than 8 or greater than 30.
Fri May 26 12:00:22 CAT 2017            - 69.2% peptide presenting high mass or isotopic deviation.
Fri May 26 12:00:22 CAT 2017            - 1.3% unrecognized modifications.
Fri May 26 12:00:22 CAT 2017        File import completed. 49391 first hits imported (236230 secondary) from 38252 spectra.
Fri May 26 12:00:22 CAT 2017        [43464 first hits passed the initial filtering]
Fri May 26 12:00:22 CAT 2017        Computing assumptions probabilities.
Fri May 26 12:00:22 CAT 2017        Saving assumptions probabilities.

Fri May 26 12:00:23 CAT 2017        Importing Data Canceled!
Fri May 26 12:00:23 CAT 2017        An error occurred while loading the identification files.
Fri May 26 12:00:23 CAT 2017        Please see the error log (Help Menu > Bug Report) for details.


Fri May 26 11:21:13 CAT 2017: PeptideShaker version 1.16.9.
Memory given to the Java virtual machine: 1037959168.
Total amount of memory in the Java virtual machine: 129761280.
Free memory: 94655208.
Java version: 1.8.0_131.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.8.0_131
os.name: Windows 7
memory: 21.8/129.9
processors available: 8
useCommandThread: false
<CompomicsError>PeptideShaker processing failed. See the PeptideShaker log for details.</CompomicsError>
java.lang.NullPointerException
	at com.compomics.util.db.ObjectsCache.addObject(ObjectsCache.java:313)
	at com.compomics.util.db.ObjectsDB.loadObjects(ObjectsDB.java:843)
	at com.compomics.util.db.ObjectsDB.loadObjects(ObjectsDB.java:737)
	at com.compomics.util.experiment.identification.IdentificationDB.loadSpectrumMatches(IdentificationDB.java:858)
	at com.compomics.util.experiment.identification.Identification.loadSpectrumMatches(Identification.java:241)
	at com.compomics.util.experiment.identification.matches_iterators.PsmIterator.checkBuffer(PsmIterator.java:280)
	at com.compomics.util.experiment.identification.matches_iterators.PsmIterator.next(PsmIterator.java:241)
	at eu.isas.peptideshaker.PeptideShaker.attachAssumptionsProbabilities(PeptideShaker.java:680)
	at eu.isas.peptideshaker.PeptideShaker.processIdentifications(PeptideShaker.java:324)
	at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importFiles(FileImporter.java:548)
	at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.doInBackground(FileImporter.java:432)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Free memory: 600633472
<CompomicsError>PeptideShaker processing failed. See the PeptideShaker log for details.</CompomicsError>
java.lang.NullPointerException
	at com.compomics.util.db.ObjectsCache.addObject(ObjectsCache.java:313)
	at com.compomics.util.db.ObjectsDB.loadObjects(ObjectsDB.java:843)
	at com.compomics.util.db.ObjectsDB.loadObjects(ObjectsDB.java:737)
	at com.compomics.util.experiment.identification.IdentificationDB.loadSpectrumMatches(IdentificationDB.java:858)
	at com.compomics.util.experiment.identification.Identification.loadSpectrumMatches(Identification.java:241)
	at com.compomics.util.experiment.identification.matches_iterators.PsmIterator.checkBuffer(PsmIterator.java:280)
	at com.compomics.util.experiment.identification.matches_iterators.PsmIterator.next(PsmIterator.java:241)
	at eu.isas.peptideshaker.PeptideShaker.attachAssumptionsProbabilities(PeptideShaker.java:680)
	at eu.isas.peptideshaker.PeptideShaker.processIdentifications(PeptideShaker.java:324)
	at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importFiles(FileImporter.java:548)
	at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.doInBackground(FileImporter.java:432)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Free memory: 522084256

**Comment by kimstellies** [comment]
I tried it with the compomics resource searchgui output file and it works.

**Comment by hbarsnes** [comment]
Hi Kim,

Thanks for the update. One thing I note above is this line: "PeptideShaker is encountering memory issues". It seems like you are only giving PeptideShaker 1 GB of memory? Are you perhaps using Java 32 bit? I would recommend checking out our [Java help](http://compomics.github.io/projects/compomics-utilities/wiki/javatroubleshooting.html) to ensure that you are optimizing your Java usage, in particular the memory settings.

PeptideShaker should run fine even on lower memory (it will be a lot slower though), but it could be that there are some extreme case we haven't tested. So please try to install 64 bit Java and increases the memory provided to PeptideShaker as much as possible. Hopefully this will solve the problem.

Best regards,
Harald

**Comment by kimstellies** [comment]
Hi Harald

It finally worked.  Thanks very much.

Regards,
Kim

**Comment by hbarsnes** [comment]
Hi Kim,

Great! I will now close the issue, but please open a new one if you experience other problems.

Best regards,
Harald
