### ISSUE TITLE
FileNotFound exception when saving results

### ISSUE THREAD

**Issue by iustin94** [compomics/peptide-shaker#297]
Hi, 

I was running an identification process with the following parameters : 

java -cp PeptideShaker-1.16.15/PeptideShaker-1.16.15.jar eu.isas.peptideshaker.cmd.PeptideShakerCLI -experiment "Malarya" 
-sample "Natalia" 
-replicate "1" 
-identification_files "searchgui_out.zip" 
-out "PeptideShaker_results" 
-spectrum_files "Natalia_TMT6_1_240m_1pt5.mgf, Natalia_TMT6_2_240min_1pt5.mgf" 
-zip "PeptideShaker_results"

And I get a .FileNotFound exception: 

java.io.FileNotFoundException: PeptideShaker_results (Is a directory)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
        at com.compomics.util.io.compression.TarUtils.tarFolderContent(TarUtils.java:72)
        at eu.isas.peptideshaker.export.CpsExporter.saveAs(CpsExporter.java:119)
        at eu.isas.peptideshaker.utils.CpsParent.saveProject(CpsParent.java:310)
        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:243)
        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:935)

At this point, I am not sure if the problem is in the -out parameter or in the -zip parameter.

My issue/suggestion is wouldn't it be better for the parameter values to be checked before running the Identification process? In my case I used 5 minutes to run this but my process failed because I was not aware that I made a mistake, but others might miss more than 5 minutes :) Hope it helps

**Comment by iustin94** [comment]
Ok, so I've removed the -zip parameter and left only the -out parameter, yet I still get the same error. The folder that I specify exists but I still get the .FileNotFound.

**Comment by hbarsnes** [comment]
Hi,

You have to use complete paths when referring to files and folders from the command line. So if you replace all the relative paths in your command line with complete paths it should work.

And yes, it would be better if we added a check for if the provided files and folders exist before trying to execute the command line. We'll see what we can do for the next release.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Issue assumed resolved by using complete paths. If this is not the case, please let us know and we'll reopen the issue.
