### ISSUE TITLE
Specificity Semi-Specific not supported

### ISSUE THREAD

**Issue by vladie0** [compomics/peptide-shaker#302]
Dear Developers, 

Executing PeptideShaker from command line generates the following error:
Thu Mar 29 11:48:43 CEST 2018 An error occurred while creating the PeptideShaker project.                                                                                                                                                                                      
java.lang.UnsupportedOperationException: Specificity Semi-Specific not supported.                                                                                                                                                                                              
        at com.compomics.cli.identification_parameters.IdentificationParametersInputBean.updateIdentificationParameters(IdentificationParametersInputBean.java:2254)                                                                                                           
        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.createProject(PeptideShakerCLI.java:650)                                                                                                                                                                                 
        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:218)                                                                                                                                                                                          
        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:938)   

This error is absent when running PeptideShaker from GUI, at least on one file. I'm unable to process al files on my personal computer manually, how can I fix this issue?

Kind Regards,
Volodimir Olexiouk

**Comment by vladie0** [comment]
Update:
A previous version, 1.16.15 does not generate this error

**Comment by mvaudel** [comment]
Hi Volodimir,

Thank you for reporting this, there was a typo in our command line parsing code. I have now corrected it in the dev branch (https://github.com/compomics/compomics-utilities/commit/0ef58b92558d7b089f806394e46e0c718de5de0a). We are finishing a quite big update of our code so I cannot give an eta for the release of a new version, but if it is something that you need urgently I can send you a snapshot of the current version containing the fix?

Apologies for the inconvenience,

Marc

**Comment by hbarsnes** [comment]
Hi Volodimir,

We've just released PeptideShaker v1.16.20 which should solve this issue. If this is not the case, please let us know and we'll reopen the issue.

Best regards,
Harald
