### ISSUE TITLE
PeptideShakerCLI: Conversion of SearchGUI.zip to PeptideShaker .cpsx fail

### ISSUE THREAD

**Issue by Steynd08** [compomics/peptide-shaker#303]
Hi team,

My SearchGUI run data failed to import into peptide shake- it just said "cancelled import" (sorry can't recall exact message), after completing the entire run. Last few lines of report here:

Tue Apr 10 00:52:37 CAT 2018        Comet finished for HLCA_Rep1_5_TC100.mgf (1 hour 23 minutes 55.0 seconds).

Tue Apr 10 00:52:37 CAT 2018        Zipping output files.

Tue Apr 10 00:53:20 CAT 2018        Processing identification files with PeptideShaker.
Reindexing: target-decoy_shuffled_nocRAP.fasta.

So I read a few threads and saw that I had the **wrong Java** and **memory allocation** for PeptideShaker (32bit and 1 GB). Which I have now updated to 64 bit java and assigned 10.3 GB of memory. I ran the data processing step in command line to convert the searchgui_out.zip of the run to a .cpsx project with the following error:

Tue Apr 10 08:37:45 CAT 2018 Project successfully created.
Tue Apr 10 08:37:45 CAT 2018 Saving results.
Tue Apr 10 08:37:45 CAT 2018 An exception occurred while saving the project.
**java.lang.NullPointerException**
        at eu.isas.peptideshaker.utils.CpsParent.saveProject(CpsParent.java:312)
        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:243)
        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:938)

PeptideShaker process failed!

Any assistance would be much appreciated. Please let me know if more info/data is required.
Thanks, D

**Comment by hbarsnes** [comment]
Hi Denise,

Could you send me the command line you are trying to run? Seems like one of the parameters is not set correctly?

Best regards,
Harald

**Comment by Steynd08** [comment]
Hi Harald,

Thanks for getting back to me. Yes, it is very likely that the parameters are not set correctly. This was my "noob" attempt at command line, apologies.

The command line script I entered was:

java -cp PeptideShaker-1.16.17.jar eu.isas.peptideshaker.cmd.PeptideShakerCLI -experiment Rep1_A1_TC100_NP -sample Rep1_TC100_HLCA -replicate 1 -identification_files G:\Users\Denise\Desktop\PhD\12Software\PeptideShaker-1.16.17\HLCA_Rep1_TC100.zip -out G:\Users\Denise\Desktop\PhD\12Software\PeptideShaker-1.16.17\ps_output_test.cpsx

I didn't adjust any other parameters assuming that the .par file in the HLCA_Rep1_TC100.zip folder would be adequate.

Thank you, 
Denise

**Comment by hbarsnes** [comment]
Hi Denise,

Are the spectrum files also included in the zip file output of SearchGUI? If not, you would need to provide them via the -spectrum_files option. Other than that your command line looks ok to me.

Best regards,
Harald

**Comment by Steynd08** [comment]
![image](https://user-images.githubusercontent.com/38237671/38597275-f05924b4-3d56-11e8-9db4-c0e739c12795.png)

The original spectrum files were not in the file, only the X!Tandem, MSGF+ and Comet output files. Are the originals also required?

Thanks, Denise

**Comment by hbarsnes** [comment]
Hi Denise,

Yes, if using the -identification_files option with the SearchGUI zip file as input the mgf files have to be in the zip file, or you have to provide them via the -spectrum_files option, as we need the mgf files to read the spectrum data during the processing and use of PeptideShaker.

Best regards,
Harald

**Comment by Steynd08** [comment]
Awesome, will rerun and see how it goes! Thank you for the help.

Regards,
Denise

**Comment by Steynd08** [comment]
Hi Harald,
Yes thank you.
Regards,
Denise
