### ISSUE TITLE
Standard reports export fails via CLI

### ISSUE THREAD

**Issue by tivdnbos** [compomics/peptide-shaker#320]
Dear,

When using the CLI of PeptideShaker, the export of standard reports fails.

Used command:
`java -cp /home/compomics/Programs/PeptideShaker-1.16.26/PeptideShaker-1.16.26.jar eu.isas.peptideshaker.cmd.ReportCLI -in ./1234_test_output/test.cpsx -out_reports ./1234_test_output -reports "3, 5, 7" -temp_folder ./1234_test_temp -log ./1234_test_output
`

I have tried to add the temp_folder and log (as a possible solution from other issues with custom reports), but without result. This is what's in the log file:

> java.io.FileNotFoundException: ./1234_test_output/test_/test_1_Default_PSM_Report.txt (No such file or directory)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:299)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:238)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:188)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:90)
	at com.compomics.util.io.export.writers.TextWriter.<init>(TextWriter.java:48)
	at com.compomics.util.io.export.ExportWriter.getExportWriter(ExportWriter.java:193)
	at eu.isas.peptideshaker.export.PSExportFactory.writeExport(PSExportFactory.java:272)
	at eu.isas.peptideshaker.cmd.CLIExportMethods.exportReport(CLIExportMethods.java:300)
	at eu.isas.peptideshaker.cmd.ReportCLI.call(ReportCLI.java:216)
	at eu.isas.peptideshaker.cmd.ReportCLI.main(ReportCLI.java:350)
java.io.FileNotFoundException: ./1234_test_output/test_/test_1_Default_Peptide_Report.txt (No such file or directory)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:299)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:238)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:188)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:90)
	at com.compomics.util.io.export.writers.TextWriter.<init>(TextWriter.java:48)
	at com.compomics.util.io.export.ExportWriter.getExportWriter(ExportWriter.java:193)
	at eu.isas.peptideshaker.export.PSExportFactory.writeExport(PSExportFactory.java:272)
	at eu.isas.peptideshaker.cmd.CLIExportMethods.exportReport(CLIExportMethods.java:300)
	at eu.isas.peptideshaker.cmd.ReportCLI.call(ReportCLI.java:216)
	at eu.isas.peptideshaker.cmd.ReportCLI.main(ReportCLI.java:350)
java.io.FileNotFoundException: ./1234_test_output/test_/test_1_Default_Protein_Report.txt (No such file or directory)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:299)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:238)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:188)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:90)
	at com.compomics.util.io.export.writers.TextWriter.<init>(TextWriter.java:48)
	at com.compomics.util.io.export.ExportWriter.getExportWriter(ExportWriter.java:193)
	at eu.isas.peptideshaker.export.PSExportFactory.writeExport(PSExportFactory.java:272)
	at eu.isas.peptideshaker.cmd.CLIExportMethods.exportReport(CLIExportMethods.java:300)
	at eu.isas.peptideshaker.cmd.ReportCLI.call(ReportCLI.java:216)
	at eu.isas.peptideshaker.cmd.ReportCLI.main(ReportCLI.java:350)

Can you help me out?

Best,
Tim

**Comment by hbarsnes** [comment]
Hi Tim,

Please change from relative to absolute paths. That should solve the problem.

Best regards,
Harald

**Comment by tivdnbos** [comment]
Hi Harald, 

When changing it to the absolute path:
`java -cp /home/compomics/Programs/PeptideShaker-1.16.26/PeptideShaker-1.16.26.jar eu.isas.peptideshaker.cmd.ReportCLI -in /home/compomics/Documents/novofeed/WP1/1234_test_output/test.cpsx -out_reports /home/compomics/Documents/novofeed/WP1/1234_test_output -reports "3, 5, 7" -temp_folder /home/compomics/Documents/novofeed/WP1/1234_test_temp -log /home/compomics/Documents/novofeed/WP1/1234_test_output`

I got the same error:

> java.io.FileNotFoundException: /home/compomics/Documents/novofeed/WP1/1234_test_output/test_/test_1_Default_PSM_Report.txt (No such file or directory)
...

Best,
Tim

**Comment by hbarsnes** [comment]
Hi Tim,

Strange. I don't understand the last part of that path, namely "test_/test_1_Default_PSM_Report.txt". The file name should be "[Project Reference]_[Sample Name]_[Replicate]_Default_PSM_Report.txt", i.e. based on the information provided when creating the project. The above file name seems to indicate that your sample name is "/test"? If this is the case it would explain why the path cannot be found? Choosing a different sample name should then hopefully fix the problem.

Best regards,
Harald

**Comment by tivdnbos** [comment]
Indeed, there was a mistake in the sample name! 
Thanks for the help,
Tim
