### ISSUE TITLE
Spectral library building for Skyline using mzid export from Peptide Shaker

### ISSUE THREAD

**Issue by SStoychev01** [compomics/peptide-shaker#323]
Hi Guys,

I'm trying to build a spectral library in Skyline from mzid export generated by Peptide Shaker. However Skyline can not find the spectrum file since in the mzid export it has been renamed i.e. the original file name is "HILIC_50mM ABC-HILIC.mzML" whilst in the mzid export it is "HILIC_50mM%20ABC-HILIC.mgf".

Hence Skyline can not find the .mgf file and gives the following error:
System.IO.IOException: ERROR: Could not find spectrum file HILIC_50mM 0X0.007FEDP-1022BC-HILIC[.MGF|.mzXML|.mzML] in current directory,.
ERROR:

at pwiz.Common.SystemUtil.ProcessRunner.Run(ProcessStartInfo psi, String stdin, IProgressMonitor progress, IProgressStatus& status, TextWriter writer) in c:\proj\pwiz_x64\pwiz_tools\Shared\Common\SystemUtil\ProcessRunner.cs:line 59
at pwiz.BiblioSpec.BlibBuild.BuildLibrary(LibraryBuildAction libraryBuildAction, IProgressMonitor progressMonitor, IProgressStatus& status, String[]& ambiguous) in c:\proj\pwiz_x64\pwiz_tools\Shared\BiblioSpec\BlibBuild.cs:line 171
at pwiz.Skyline.Model.Lib.BiblioSpecLiteBuilder.BuildLibrary(IProgressMonitor progress) in c:\proj\pwiz_x64\pwiz_tools\Skyline\Model\Lib\BiblioSpecLiteBuilder.cs:line 128

**Comment by mvaudel** [comment]
Hi,

I think that the escaping of spaces is a requirement of the mzId format. As a general rule in informatics you should avoid spaces and special characters in file paths and names. This should solve your problem and will save you a lot of debugging time.

Hope this helps,

Marc

**Comment by SStoychev01** [comment]
Thanks Marc will rename mzML without spaces and give this another go

**Comment by SStoychev01** [comment]
Thanks Mar, without spaces can build the Skyline library just need to have
mzid file in same folder as mzml spectra files.

Regards,

Stoyan
