### ISSUE TITLE
java.io.IOException: This archives contains unclosed entries.

### ISSUE THREAD

**Issue by vladie0** [compomics/peptide-shaker#324]
Dear developers, 

I've processed a project using SearchGUI and search engines X!tandem, MSGF+ & Comet, which did not provide any errors.
Using Peptideshaker, The following error occurs:

Fri Jul 20 15:46:33 CEST 2018 Project successfully created.
Fri Jul 20 15:46:33 CEST 2018 Saving results.
10% 20% 30% 40% 50% 60% 70% 80% 90%
Fri Jul 20 17:28:51 CEST 2018 An exception occurred while saving the project.
java.io.IOException: This archives contains unclosed entries.
        at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.finish(TarArchiveOutputStream.java:219)
        at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.close(TarArchiveOutputStream.java:235)
        at com.compomics.util.io.compression.TarUtils.tarFolderContent(TarUtils.java:90)
        at eu.isas.peptideshaker.export.CpsExporter.saveAs(CpsExporter.java:119)
        at eu.isas.peptideshaker.utils.CpsParent.saveProject(CpsParent.java:310)
        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:243)
        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:938)
How can I solve this issue ? 
Thank you

**Comment by mvaudel** [comment]
Hi Volodimir,

Like your other issue it looks like another process is using the file or that an IO issue occurred causing a stream to stay open. I am not sure how this could happen, usually we see this when multiple instances of PeptideShaker are running on the same file.

Hope this helps,

Marc

**Comment by hbarsnes** [comment]
Issue assumed resolved. If this is not the case, please let us know and we'll reopen the issue.
