### ISSUE TITLE
java.sql.SQLException: The conglomerate (1,936) requested does not exist.

### ISSUE THREAD

**Issue by vladie0** [compomics/peptide-shaker#325]
Dear developers, 

I've processed a (indepentent from the previous reported issue) project using SearchGUI and search engines X!tandem, MSGF+ & Comet, which did not provide any errors.
Using Peptideshaker, The following error occurs:

10%java.sql.SQLException: The conglomerate (1,936) requested does not exist.
        at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
        at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
        at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
        at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
        at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedStatement.execute(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedStatement.executeQuery(Unknown Source)
        at com.compomics.util.db.ObjectsDB.getTableContentFromDBNoMutex(ObjectsDB.java:1198)
        at com.compomics.util.db.ObjectsDB.insertObjects(ObjectsDB.java:407)
        at com.compomics.util.db.ObjectsCache.saveObjects(ObjectsCache.java:452)
        at com.compomics.util.db.ObjectsCache.saveObjects(ObjectsCache.java:361)
        at com.compomics.util.db.ObjectsCache.updateCacheSynchronized(ObjectsCache.java:609)
        at com.compomics.util.db.ObjectsCache.updateCache(ObjectsCache.java:581)
        at com.compomics.util.db.ObjectsCache.addObject(ObjectsCache.java:333)
        at com.compomics.util.db.ObjectsDB.insertObject(ObjectsDB.java:322)
        at com.compomics.util.experiment.identification.IdentificationDB.addAssumptions(IdentificationDB.java:455)
        at com.compomics.util.experiment.identification.Identification.addAssumptions(Identification.java:1299)
        at com.compomics.util.experiment.identification.Identification.addAssumptions(Identification.java:1344)
        at eu.isas.peptideshaker.fileimport.PsmImporter.importAssumptions(PsmImporter.java:638)
        at eu.isas.peptideshaker.fileimport.PsmImporter.importPsm(PsmImporter.java:331)
        at eu.isas.peptideshaker.fileimport.PsmImporter.access$000(PsmImporter.java:69)
        at eu.isas.peptideshaker.fileimport.PsmImporter$PsmImporterRunnable.run(PsmImporter.java:1415)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.sql.SQLException: The conglomerate (1,936) requested does not exist.
        at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
        at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
        ... 28 more
Caused by: ERROR XSAI2: The conglomerate (1,936) requested does not exist.
        at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
        at org.apache.derby.impl.store.access.heap.HeapConglomerateFactory.readConglomerate(Unknown Source)
        at org.apache.derby.impl.store.access.CacheableConglomerate.setIdentity(Unknown Source)
        at org.apache.derby.impl.services.cache.ConcurrentCache.find(Unknown Source)
        at org.apache.derby.impl.store.access.RAMAccessManager.conglomCacheFind(Unknown Source)
        at org.apache.derby.impl.store.access.RAMTransaction.findConglomerate(Unknown Source)
        at org.apache.derby.impl.store.access.RAMTransaction.findExistingConglomerate(Unknown Source)
        at org.apache.derby.impl.store.access.RAMTransaction.openStoreCost(Unknown Source)
        at org.apache.derby.impl.sql.compile.CompilerContextImpl.getStoreCostController(Unknown Source)
        at org.apache.derby.impl.sql.compile.FromBaseTable.getStoreCostController(Unknown Source)
        at org.apache.derby.impl.sql.compile.FromBaseTable.estimateCost(Unknown Source)
        at org.apache.derby.impl.sql.compile.OptimizerImpl.estimateTotalCost(Unknown Source)
        at org.apache.derby.impl.sql.compile.OptimizerImpl.costBasedCostOptimizable(Unknown Source)

How can I solve this issue ? 
Thank you

**Comment by mvaudel** [comment]
Hi Volodimir,

It looks like a rather odd IO issue. Is there anything special with your setup that could be the reason for it? Also, are you sure that a single instance of PeptideShaker is running?

Apologies for the inconvenience,

Marc

**Comment by hbarsnes** [comment]
Issue assumed resolved. If this is not the case, please let us know and we'll reopen the issue.
