### ISSUE TITLE
peptide shaker error

### ISSUE THREAD

**Issue by bernt-matthias** [compomics/peptide-shaker#342]
A colleague just SearchGUI/Peptideshaker using the latest Galaxy wrapper and got:  

```
java.lang.IllegalArgumentException: Only one site found in peptide score to position map when estimating the A-score for spectrum 20180613_HP_ChloroMeOH_C8_InSolution.6778.6778.3 File:"20180613_HP_ChloroMeOH_C8_InSolution.raw", NativeID:"controllerType=0 controllerNumber=1 scan=6778" in file 20180613_HP_ChloroMeOH_C8_InSolution.mgf for modification Acetylation of peptide N-term on peptide EGAAPDPIITIR.
	at com.compomics.util.experiment.identification.ptm.ptmscores.AScore.getAScore(AScore.java:162)
	at eu.isas.peptideshaker.ptm.PtmScorer.attachProbabilisticScore(PtmScorer.java:307)
	at eu.isas.peptideshaker.ptm.PtmScorer.scorePTMs(PtmScorer.java:412)
	at eu.isas.peptideshaker.ptm.PtmScorer$PsmPtmScorerRunnable.run(PtmScorer.java:2355)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

The command line was 

```
peptide-shaker -Djava.awt.headless=true eu.isas.peptideshaker.cmd.PeptideShakerCLI --exec_dir="$cwd/bin" -gui 0 -temp_folder $cwd/PeptideShakerCLI -experiment 'Galaxy_Experiment_2019010714431546868599' -sample 'Sample_2019010714431546868599' -replicate 1 -identification_files $cwd/searchgui_input.zip -id_params $cwd/SEARCHGUI_IdentificationParameters.par -out $cwd/peptideshaker_output.cpsx -threads "${GALAXY_SLOTS:-12}"  -protein_fdr "5.0" -peptide_fdr "5.0" -psm_fdr "5.0" -ptm_score "0" -ptm_alignment "1" -ptm_sequence_matching_type "1" -protein_fraction_mw_confidence "95.0"  -import_peptide_length_min "6" -import_peptide_length_max "30" -import_precurosor_mz "10.0" -import_precurosor_mz_ppm "1" -exclude_unknown_ptms "1"   -output_file $cwd/output.mzid -include_sequences 0 -contact_first_name "Proteomics" -contact_last_name "Galaxy" -contact_email "galaxyp@umn.edu" -contact_address "galaxyp@umn.edu" -organization_name "University of Minnesota" -organization_email "galaxyp@umn.edu" -organization_address "Minneapolis, MN 55455, Vereinigte Staaten"  -out_reports $cwd/output_reports -reports 9
```

Peptideshaker seems to work with default options (in the above example FDR was changed to 5.0). A working command line was: 

```
peptide-shaker -Djava.awt.headless=true eu.isas.peptideshaker.cmd.PeptideShakerCLI --exec_dir="$cwd/bin" -gui 0 -temp_folder $cwd/PeptideShakerCLI -experiment 'Galaxy_Experiment_2019010212581546430297' -sample 'Sample_2019010212581546430297' -replicate 1 -identification_files $cwd/searchgui_input.zip -id_params $cwd/SEARCHGUI_IdentificationParameters.par -out $cwd/peptideshaker_output.cpsx -threads "${GALAXY_SLOTS:-12}"      -out_reports $cwd/output_reports -reports 9
```

It seems to work when `-ptm_sequence_matching_type "0"` is omitted (0 is the default chosen in the Galaxy tool but the Peptideshaker default seems to be 1 .. this should be fixed in the tool?). 

Furthermore two exceptions (which seem to be ignored) are raised during: 

```
peptide-shaker eu.isas.peptideshaker.cmd.PathSettingsCLI --exec_dir="$cwd/bin" -temp_folder $cwd/PathSettingsCLI -log $cwd/peptideshaker.log 
```

```
org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: -species
	at org.apache.commons.cli.Parser.processOption(Parser.java:363)
	at org.apache.commons.cli.Parser.parse(Parser.java:199)
	at org.apache.commons.cli.Parser.parse(Parser.java:85)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:917)
```

```
org.apache.commons.cli.MissingArgumentException: Missing argument for option: experiment
	at org.apache.commons.cli.Parser.processArgs(Parser.java:343)
	at org.apache.commons.cli.Parser.processOption(Parser.java:393)
	at org.apache.commons.cli.Parser.parse(Parser.java:199)
	at org.apache.commons.cli.Parser.parse(Parser.java:85)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:917)
```

**Comment by CarlosHorro** [comment]
Hi Matthias,

Managing this in parts, and just related to the 2 last exceptions you mention, it seems that the PS version you are executing is not the last one, due to -species option is no longer supported and I think the line of the exception (PeptideShakerCLI.java:917) does not correspond with the code of the current PS version...

**Comment by bernt-matthias** [comment]
Hi Carlos

thanks for your feedback. Since I'm running the latest version of the galaxy tool I can confirm, that I run version 1.16.36 (installed via conda) which seems to be the latest. 

The odd thing is that the command line uses neither of the two options ... ?

**Comment by CarlosHorro** [comment]
Hi Matthias,

I think I found out what is happening in relation with those 2 errors: it seems that the Conda package itself has been created with PeptideShaker.log (in my case, it's located at /home/parallels/GitHub/galaxy/database/dependencies/_conda/envs/__peptide-shaker@1.16.36/share/peptide-shaker-1.16.36-0/resources) containing this old content:

```
Thu Dec 13 13:54:45 CET 2018: PeptideShaker version 1.16.36.
Memory given to the Java virtual machine: 3776970752.

Total amount of memory in the Java virtual machine: 255328256.
Free memory: 245965872.
Java version: 1.8.0_191.
org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: -species
	at org.apache.commons.cli.Parser.processOption(Parser.java:363)
	at org.apache.commons.cli.Parser.parse(Parser.java:199)
	at org.apache.commons.cli.Parser.parse(Parser.java:85)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:917)

Thu Dec 13 13:55:30 CET 2018: PeptideShaker version 1.16.36.
Memory given to the Java virtual machine: 3776970752.
Total amount of memory in the Java virtual machine: 255328256.
Free memory: 244672648.
Java version: 1.8.0_191.


Thu Dec 13 13:55:51 CET 2018: PeptideShaker version 1.16.36.
Memory given to the Java virtual machine: 3776970752.
Total amount of memory in the Java virtual machine: 255328256.
Free memory: 245934232.
Java version: 1.8.0_191.

Thu Dec 13 13:56:02 CET 2018: PeptideShaker version 1.16.36.
Memory given to the Java virtual machine: 3776970752.
Total amount of memory in the Java virtual machine: 255328256.
Free memory: 245965872.
Java version: 1.8.0_191.
org.apache.commons.cli.MissingArgumentException: Missing argument for option: experiment
	at org.apache.commons.cli.Parser.processArgs(Parser.java:343)
	at org.apache.commons.cli.Parser.processOption(Parser.java:393)
	at org.apache.commons.cli.Parser.parse(Parser.java:199)
	at org.apache.commons.cli.Parser.parse(Parser.java:85)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:917)

```
They are old error traces probably due to some local testing, previous to the launch of the final PeptideShaker 1.16.36 release (they are dated on Thu Dec 13), and they can be ignored. I've checked that executing current tool with your exact params just adds this to the log file:

```

Thu Jan 10 11:49:36 CET 2019: PeptideShaker version 1.16.36.
Memory given to the Java virtual machine: 4294967296.
Total amount of memory in the Java virtual machine: 132120576.
Free memory: 120751776.
Java version: 11.0.1.
```

without those weird error traces.

**Comment by bernt-matthias** [comment]
Sounds reasonable and I can verify that the conda package that is installed on our system contains PeptideShaker.log at the analogous path. So only the first error remains which occurs if we switch to non-default options.

**Comment by CarlosHorro** [comment]
About the first problem, Harald has looked into it and it seems a problem in the current backend which will be solved in the new one, so temporarily using PS default option is recommended.

By the way, looking at the PS galaxy tool ptm_sequence_matching_type code:

```
<param name="ptm_sequence_matching_type" type="select" label="The PTM to peptide sequence matching type">
                     <option value="0">Character Sequence</option>
                     <option value="1" selected="true">Amino Acids</option>
                     <option value="2">Indistinguishable Amino Acids</option>
</param>

```
So the default value in the tool should also be 1...

**Comment by bernt-matthias** [comment]
I'm sorry. Actually I meant the `-ptm_score` parameter. It defaults to 0 in the Galaxy tool (A-score), but PeptideShaker's default seems to be 1 (PhosphoRS). The error that I mentioned above occurs for the Galaxy default value of 0 .. which should be changed in the tool (I opened an issue https://github.com/galaxyproteomics/tools-galaxyp/issues/334 in order to not forget it).

**Comment by bernt-matthias** [comment]
The error that happened when selecting the (now non-default) option "A-score" would be still of interest...

**Comment by CarlosHorro** [comment]
> The error that happened when selecting the (now non-default) option "A-score" would be still of interest...

You're right, closing it will have to wait until new backend is launched and tested.

**Comment by hbarsnes** [comment]
Issue assume resolved in newer versions. If this is not the case, please let us know and we'll reopen the issue.
