### ISSUE TITLE
PeptideShaker 1.16.37 .mzid export failure

### ISSUE THREAD

**Issue by lienchi1711** [compomics/peptide-shaker#344]
I used PeptideShaker the newest version (1.16.37) to export the cspx analysis file to mzid for submission on PRIDE. However, the exported file was not complete, eventhough there was no error message from peptideshaker.
regards

**Comment by hbarsnes** [comment]
Hi,

Have you checked the content of the PeptideShaker log file? You can find it via the PeptideShaker Welcome dialog > Settings & Help > Help > Bug Report.

Best regards,
Harald

**Comment by lienchi1711** [comment]
Hi Harald,
The analysis was done with version 1.9.0. And I tried to use the newest version 1.16.37 to export mzid file. That might be the reason. So I used the same version of peptideshaker as before (1.9.0) to export and it seems to work fine. 
Anyway I pasted the bug report of version 1.16.37 below, if you are interested in.
regards
Chi


Thu Jan 24 12:22:38 CET 2019: PeptideShaker version 1.16.37.
Memory given to the Java virtual machine: 37283168256.
Total amount of memory in the Java virtual machine: 128974848.
Free memory: 81161960.
Java version: 1.8.0_161.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.8.0_161
os.name: Windows Server 2012
memory: 65.0/163.1
processors available: 8
useCommandThread: false
Reindexing: U507_human_TD_2015_07_22.fasta.
java.io.FileNotFoundException: \\do2-mascot.isas.de\sequence\U507_human_TD\current\U507_human_TD_2015_07_22.fasta.cui (Zugriff verweigert)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at com.compomics.util.io.SerializationUtils.writeObject(SerializationUtils.java:23)
	at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.writeIndex(SequenceFactory.java:935)
	at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.getFastaIndex(SequenceFactory.java:717)
	at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.getFastaIndex(SequenceFactory.java:641)
	at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.loadFastaFile(SequenceFactory.java:582)
	at eu.isas.peptideshaker.utils.CpsParent.loadFastaFile(CpsParent.java:362)
	at eu.isas.peptideshaker.gui.PeptideShakerGUI$104.run(PeptideShakerGUI.java:5473)
java.lang.IndexOutOfBoundsException: Index: 0, Size: 1
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at eu.isas.peptideshaker.gui.tabpanels.OverviewPanel.updateSpectrum(OverviewPanel.java:4784)
	at eu.isas.peptideshaker.gui.tabpanels.OverviewPanel.psmTableMouseReleased(OverviewPanel.java:2032)
	at eu.isas.peptideshaker.gui.tabpanels.OverviewPanel.updateSelection(OverviewPanel.java:5936)
	at eu.isas.peptideshaker.gui.tabpanels.OverviewPanel.updatePsmSelection(OverviewPanel.java:4969)
	at eu.isas.peptideshaker.gui.tabpanels.OverviewPanel.peptideTableMouseReleased(OverviewPanel.java:2210)
	at eu.isas.peptideshaker.gui.tabpanels.OverviewPanel.updateSelection(OverviewPanel.java:5923)
	at eu.isas.peptideshaker.gui.tabpanels.OverviewPanel.updatePsmSelection(OverviewPanel.java:4969)
	at eu.isas.peptideshaker.gui.tabpanels.OverviewPanel.peptideTableMouseReleased(OverviewPanel.java:2210)
	at eu.isas.peptideshaker.gui.tabpanels.OverviewPanel.updateSelection(OverviewPanel.java:5923)
	at eu.isas.peptideshaker.gui.tabpanels.OverviewPanel$96.run(OverviewPanel.java:5070)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
java.lang.NullPointerException
	at com.compomics.util.experiment.biology.Peptide.estimateTheoreticMass(Peptide.java:1802)
	at com.compomics.util.experiment.biology.Peptide.getMass(Peptide.java:188)
	at com.compomics.util.experiment.identification.spectrum_assumptions.PeptideAssumption.getTheoreticMass(PeptideAssumption.java:89)
	at com.compomics.util.experiment.identification.SpectrumIdentificationAssumption.getTheoreticMz(SpectrumIdentificationAssumption.java:143)
	at eu.isas.peptideshaker.export.MzIdentMLExport.writeSpectrumIdentificationResult(MzIdentMLExport.java:1475)
	at eu.isas.peptideshaker.export.MzIdentMLExport.writeDataAnalysis(MzIdentMLExport.java:1278)
	at eu.isas.peptideshaker.export.MzIdentMLExport.writeDataCollection(MzIdentMLExport.java:1235)
	at eu.isas.peptideshaker.export.MzIdentMLExport.createMzIdentMLFile(MzIdentMLExport.java:347)
	at eu.isas.peptideshaker.gui.exportdialogs.MzIdentMLExportDialog$15.run(MzIdentMLExportDialog.java:690)
