### ISSUE TITLE
Exporting Identification features

### ISSUE THREAD

**Issue by tivdnbos** [compomics/peptide-shaker#349]
Hi,

When I'm trying to export the identification features (Default PSM report and Extended PSM report), I got the error that "An error occurred while generating the output", without additional information. I searched one mgf against a target-decoy database using SearchGUI and imported the zip-file in PeptideShaker.

Best wishes,
Tim

**Comment by hbarsnes** [comment]
Hi Tim,

Have you checked the PeptideShaker log file? You'll find it via the Welcome dialog > Settings & Help > Help >Bug Report.

Best regards,
Harald

**Comment by tivdnbos** [comment]
Yes:

Mon Apr 01 13:32:21 CEST 2019: PeptideShaker version 1.16.38.
Memory given to the Java virtual machine: 199246217216.
Total amount of memory in the Java virtual machine: 637534208.
Free memory: 515276288.
Java version: 10.0.2.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 10.0.2
os.name: Linux
memory: 155.4/637.5
processors available: 16
useCommandThread: false
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 0 >= 0
	at java.base/java.util.Vector.elementAt(Vector.java:496)
	at java.desktop/javax.swing.table.DefaultTableColumnModel.getColumn(DefaultTableColumnModel.java:295)
	at java.desktop/javax.swing.JTable.getCellRect(JTable.java:2980)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI.createTableSize(BasicTableUI.java:1734)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI.getPreferredSize(BasicTableUI.java:1773)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1680)
	at java.desktop/javax.swing.ViewportLayout.layoutContainer(ViewportLayout.java:143)
	at java.desktop/java.awt.Container.layout(Container.java:1535)
	at java.desktop/java.awt.Container.doLayout(Container.java:1524)
	at java.desktop/java.awt.Container.validateTree(Container.java:1720)
	at java.desktop/java.awt.Container.validateTree(Container.java:1729)
	at java.desktop/java.awt.Container.validate(Container.java:1655)
	at java.desktop/javax.swing.RepaintManager$3.run(RepaintManager.java:737)
	at java.desktop/javax.swing.RepaintManager$3.run(RepaintManager.java:735)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:734)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1879)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
java.lang.IllegalArgumentException: The maximum length of cell contents (text) is 32,767 characters
	at org.apache.poi.hssf.usermodel.HSSFCell.setCellValue(HSSFCell.java:548)
	at org.apache.poi.hssf.usermodel.HSSFCell.setCellValue(HSSFCell.java:522)
	at com.compomics.util.io.export.writers.ExcelWriter.addSeparator(ExcelWriter.java:226)
	at com.compomics.util.io.export.ExportWriter.addSeparator(ExportWriter.java:136)
	at eu.isas.peptideshaker.export.sections.PsPsmSection.writeSection(PsPsmSection.java:208)
	at eu.isas.peptideshaker.export.PSExportFactory.writeExport(PSExportFactory.java:304)
	at eu.isas.peptideshaker.gui.exportdialogs.FeaturesPreferencesDialog$16.run(FeaturesPreferencesDialog.java:802)
java.lang.IllegalArgumentException: The maximum length of cell contents (text) is 32,767 characters
	at org.apache.poi.hssf.usermodel.HSSFCell.setCellValue(HSSFCell.java:548)
	at org.apache.poi.hssf.usermodel.HSSFCell.setCellValue(HSSFCell.java:522)
	at com.compomics.util.io.export.writers.ExcelWriter.addSeparator(ExcelWriter.java:226)
	at com.compomics.util.io.export.ExportWriter.addSeparator(ExportWriter.java:136)
	at eu.isas.peptideshaker.export.sections.PsPsmSection.writeSection(PsPsmSection.java:208)
	at eu.isas.peptideshaker.export.PSExportFactory.writeExport(PSExportFactory.java:304)
	at eu.isas.peptideshaker.gui.exportdialogs.FeaturesPreferencesDialog$16.run(FeaturesPreferencesDialog.java:802)


Mon Apr 01 14:35:08 CEST 2019: PeptideShaker version 1.16.38.
Memory given to the Java virtual machine: 199246217216.
Total amount of memory in the Java virtual machine: 402653184.
Free memory: 234954056.
Java version: 10.0.2.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 10.0.2
os.name: Linux
memory: 105.1/402.7
processors available: 16
useCommandThread: false

**Comment by tivdnbos** [comment]
Update:

I received an additional error when trying to open the Spectrum IDs tab: "An error occured: java.desktop/javax.swing.plaf.FontUIResource cannot be cast to java.desktop/java.awt.Color."

**Comment by hbarsnes** [comment]
Hi Tim,

The problem is this line:
"java.lang.IllegalArgumentException: The maximum length of cell contents (text) is 32,767 characters"

Try switching from Excel output to just tab separated text files and I think it should be ok.

> I received an additional error when trying to open the Spectrum IDs tab: "An error occured: java.desktop/javax.swing.plaf.FontUIResource cannot be cast to java.desktop/java.awt.Color."

Strange. Where/when did this happen? And was there more to the stacktrace than that single line?

Best regards,
Harald

**Comment by tivdnbos** [comment]
The problem is fixed by switching it to text files, thanks!
The second error didn't occur anymore after restarting PeptideShaker, so no idea what happened there..

Thanks!
Tim
