### ISSUE TITLE
MzidCLI: 'an error occurred while reading filename.cpsx'

### ISSUE THREAD

**Issue by TessaGillett** [compomics/peptide-shaker#352]
Hello,

I'm having some trouble converting certain .cpsx files to .mzid (see command and error message below) - any idea what might be causing this? I get this for about 8% of the files I'm trying to convert. 

Thank you!
Tessa

Command:
`java -Xms128M -Xmx60G -cp ./ext_tools/PeptideShaker-1.16.36/PeptideShaker-1.16.36.jar eu.isas.peptideshaker.cmd.MzidCLI -in /home/path/mod_TT1_111130_TY_BN3_LysC_SCX_20percent_F39_recal_371_445_searchgui_out.cpsx -output_file /home/path/mod_TT1_111130_TY_BN3_LysC_SCX_20percent_F39_recal_371_445_searchgui_out.mzid -include_sequences 1 -contact_first_name x -contact_last_name x -contact_email x -contact_address x -organization_name x -organization_email x -organization_address x`

Error:
`Wed Apr 17 01:47:03 CEST 2019 An error occurred while reading: /home/path/mod_TT1_111130_TY_BN3_LysC_SCX_20percent_F39_recal_371_445_searchgui_out.cpsx.`

From the log:
`Wed Apr 17 01:46:46 CEST 2019: PeptideShaker version 1.16.36.
Memory given to the Java virtual machine: 57266405376.
Total amount of memory in the Java virtual machine: 128974848.
Free memory: 116672656.
Java version: 1.8.0_201.
java.io.OptionalDataException
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1593)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
        at java.util.HashMap.readObject(HashMap.java:1410)
        at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1170)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2178)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
        at java.util.HashMap.readObject(HashMap.java:1412)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1170)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2178)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
        at java.util.HashMap.readObject(HashMap.java:1412)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1170)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2178)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
        at java.util.HashMap.readObject(HashMap.java:1412)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1170)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2178)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
        at java.util.HashMap.readObject(HashMap.java:1412)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1170)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2178)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
        at com.compomics.util.io.SerializationUtils.readObject(SerializationUtils.java:58)
        at com.compomics.util.experiment.io.ExperimentIO.loadExperiment(ExperimentIO.java:44)
        at eu.isas.peptideshaker.fileimport.CpsFileImporter.<init>(CpsFileImporter.java:57)
        at eu.isas.peptideshaker.utils.CpsParent.loadCpsFile(CpsParent.java:205)
        at eu.isas.peptideshaker.cmd.MzidCLI.call(MzidCLI.java:91)
        at eu.isas.peptideshaker.cmd.MzidCLI.main(MzidCLI.java:296)
`

**Comment by hbarsnes** [comment]
Hi Tessa,

Seems like there is a problem reading the content of the cpsx file. Have you checked that these files can be opened in PeptideShaker and that they are not corrupt? And do you see any difference between the files that work and the ones that do not?

Are you opening the cpsx file in the same PeptideShaker version as the one used to create the cpsx file in the first place? That is always recommended.

Finally, note that if you know that you want to create the mzid file when processing the data in PeptideShaker you can consider adding the mzid parameters directly to the PeptideShakerCLI command line. That could potentially also get rid of these sorts of problems.

Best regards,
Harald

**Comment by TessaGillett** [comment]
Hi Harald, thank you for your reply! 

You are right, when I try to open the files in the GUI I get a message telling me my file is corrupted, even if it's the version of PeptideShaker that I generated the file with. In terms of filesizes the corrupted and non-corrupted files seem similar. Looking at the content, there are some lines with a lot of whitespace in the tail of the corrupted files that I haven't found in the non-corrupted ones I've looked at, such as those below which are the last 5 lines of the file. (I haven't found a .cpsx format specification yet though, so I'm not sure what's normal variation and what's not supposed to be there.)

If that's the problem, then I guess the question remains how it got that way and whether it's preventable. Like I said this is about 8% of files and as far as I know these files haven't been touched since generating them, which I did in a few batches of shared parameters for SearchGUI (where the bad files are spread over the different batches, not parameter dependent) and afterwards ran PeptideShaker.

And thanks for that last note! I'll make sure to do it that way in the future.

```?q?
   q?
     q?
       q?
         q?
           q?
             q?
               q?
                 q?
                  q?
                    	q?

q?

  q?

    q?
q?
  q?
    q?
      q?
        q?
          q?
            q?
              q?
                q?
                  q?
                    q?
                      q?
                        q?
                          q?
                            ?
                             q?
                               q?
                                 q?
                                   q?
                                      q?
                                        !q?
                                           "q?
                                              #q?
                                                 $q?
                                                    %q?
                                                       &q?
                                                          'q?
                                                             (q?
                                                                )q?
                                                                   *q?
                                                                      +q?
                                                                         ,q?
                                                                            -q?
                                                                               .q?
                                                                                  /q?
                                                                                     0q?
                                                                                        1q?
                                                                                           2q?
                                                                                              3q?
  4q?
     5q?
        6q?
           7q?
              8q?
                 9q?
                    :q?
                       ;q?
                          <q?
                             =q?
                                >q?
                                   ?q?
                                      @q?
                                         Aq?
                                            Bq?
                                               Cq?
                                                  Dq?
                                                     Eq?
                                                        Fq?
                                                           Gq?
                                                              Hq?
                                                                 Iq?
                                                                    Jq?
                                                                       Kq?
                                                                          Lq?
                                                                             Mq?
                                                                                Nq?
                                                                                   Oq?
                                                                                      Pq?
                                                                                         Qq?
                                                                                            Rq?
                                                                                              Sq?
  Tq?
     Uq?
        Vq?
           Wq?
              Xq?
                 Yq?
                    Zq?
                       [q?
                          \q?
                             ]q?
                                ^q?
                                   _q?
                                      `q?
                                         aq?
                                            bq?
                                               cq?
                                                  dq?
                                                     eq?
                                                        fq?
                                                           gq?
                                                              hq?
                                                                 iq?
                                                                    jq?
                                                                       kq?
                                                                          lq?
                                                                             mq?
                                                                                nq?
                                                                                   oq?
                                                                                      pq?
                                                                                         qq?
                                                                                            rq?
                                                                                              sq?
  tq?
     uq?
        vq?
           wq?
              xq?
                 yq?
                    zq?
                       {q?
                          |q?
                             }q?
                                ~q?
                                   q?
                                     ?q?
                                        ?q?
                                           ?q?
                                              ?q?
                                                 ?q?
                                                    ?q?
                                                       ?q?
                                                          ?q?
                                                             ?q?
                                                                ?q?
                                                                   ?q?
                                                                      ?q?
                                                                         ?q?
                                                                            ?q?
                                                                               ?q?
                                                                                  ?q?
                                                                                     ?q?
                                                                                        ?q?
                                                                                           ?q?
                                                                                              ?q?
  ?q?
     ?q?
        ?q?
           ?q?
              ?q?
                 ?q?
                    ?q?
                       ?q?
                          ?q?
                             ?q?
                                ?q?
                                   ?q?
                                      ?q?
                                         ?q?
                                            ?q?
                                               ?q?
                                                  ?q?
                                                     ?q?
                                                        ?q?
                                                           ?q?
                                                              ?q?
                                                                 ?q?
                                                                    ?q?
                                                                       ?q?
                                                                          ?q?
                                                                             ?q?
                                                                                ?q?
                                                                                   ?q?
                                                                                      ?q?
                                                                                         ?q?
                                                                                            ?q?
                                                                                              ?q?
  ?q?
     ?q?
        ?q?
           ?q?
              ?q?
                 ?q?
                    ?q?
                       ?q?
                          ?q?
                             ?q?
                                ?q?
                                   ?q?
                                      ?q?
                                         ?q?
                                            ?q?
                                               ?q?
                                                  ?q?
                                                     ?q?
                                                        ?q?
                                                           ?q?
                                                              ?q?
                                                                 ?q?
                                                                    ?q?
                                                                       ?q?
                                                                          ?q?
                                                                             ?q?
                                                                                ?q?
                                                                                   ?q?
                                                                                      ?q?
                                                                                         ?q?
                                                                                            ?q?
                                                                                              ?q?
  ?q?
     ?q?
        ?q?
           ?q?
              ?q?
                 ?q?
                    ?q?
                       ?q?
                          ?q?
                             ?q?
                                ?q?
                                   ?q?
                                      ?q?
                                         ?q?
                                            ?q?
                                               ?q?
                                                  ?q?
                                                     ?q?
                                                        ?q?
                                                           ?q?
                                                              ?q?
                                                                 ?q?
                                                                    ?q?
                                                                       ?q?
                                                                          ?q?
                                                                             ?q?
                                                                                ?q?
                                                                                   ?q?
                                                                                      ?q?
                                                                                         ?q?
                                                                                            ?q?
                                                                                              ?q?
  ?q?
     ?q?
        ?q?
           ?q?
              ?q?
                 ?q?
                    ?q?
                       ?q?
                          ?q?
                             ?q?
                                ?q?
                                   ?q?
                                      q?
                                        q?
                                          q?
                                            q?
                                              q?
                                                q?
                                                  q?
                                                    q?
                                                     q?
                                                       	q?

q?

  q?

    q?
q?
  q?
    q?
      q?
        q?
          q?
            q?
              q?
                q?
                  q?
                    q?
                      q?
                        q?
                          q?
                            ?
                             q?
                               q?
                                 q?
                                   q?
                                      q?
                                        !q?
                                           "q?
                                              #q?
                                                 $q?
                                                    %q?
                                                       &q?
                                                          'q?
                                                             (q?
                                                                )q?
                                                                   *q?
                                                                      +q?
                                                                         ,q?
                                                                            -q?
                                                                               .q?
                                                                                  /q?
                                                                                     0q?
                                                                                        1q?
                                                                                           2q?
                                                                                              3q?
  4q?
     5q?
        6q?
           7q?
              8q?
                 9q?
                    :q?
                       ;q?
                          <q?
                             =q?
                                >q?
                                   ?q?
                                      @q?
                                         Aq?
                                            Bq?
                                               Cq?
                                                  Dq?
                                                     Eq?
                                                        Fq?
                                                           Gq?
                                                              Hq?
                                                                 Iq?
                                                                    Jq?
                                                                       Kq?
                                                                          Lq?
                                                                             Mq?
                                                                                Nq?
                                                                                   Oq?
                                                                                      Pq?
                                                                                         Qq?
                                                                                            Rq?
                                                                                              Sq?
  Tq?
     Uq?
        Vq?
           Wq?
              Xq?
                 Yq?
                    Zq?
                       [q?
                          \q?
                             ]q?
                                ^q?
                                   _q?
                                      `q?
                                         aq?
                                            bq?
                                               cq?
                                                  dq?
                                                     eq?
                                                        fq?
                                                           gq?
                                                              hq?
                                                                 iq?
                                                                    jq?
                                                                       kq?
                                                                          lq?
                                                                             mq?
                                                                                nq?
                                                                                   oq?
                                                                                      pq?
                                                                                         qq?
                                                                                            rq?
                                                                                              sq?
  tq?
     uq?
        vq?
           wq?
              xq?
                 yq?
                    zq?
                       {q?
                          |q?
                             }q?
                                ~q?
                                   q?
                                     ?q?
                                        ?q?
                                           ?q?
                                              ?q?
                                                 ?q?
                                                    ?q?
                                                       ?q?
                                                          ?q?
                                                             ?q?
                                                                ?q?
                                                                   ?q?
                                                                      ?q?
                                                                         ?q?
                                                                            ?q?
                                                                               ?q?
                                                                                  ?q?
                                                                                     ?q?
                                                                                        ?q?
                                                                                           ?q?
                                                                                              ?q?
  ?q?
     ?q?
        ?q?
           ?q?
              ?q?
                 ?q?
                    ?q?
                       ?q?
                          ?q?
                             ?q?
                                ?q?
                                   ?q?
                                      ?q?
                                         ?q?
                                            ?q?
                                               ?q?
                                                  ?q?
                                                     ?q?
                                                        ?q?
                                                           ?q?
                                                              ?q?
                                                                 ?q?
                                                                    ?q?
                                                                       ?q?
                                                                          ?q?
                                                                             ?q?
                                                                                ?q?
                                                                                   ?q?
                                                                                      ?q?
                                                                                         ?q?
                                                                                            ?q?
                                                                                              ?q?
  ?q?
     ?q?
        ?q?
           ?q?
              ?q?
                 ?q?
                    ?q?
                       ?q?
                          ?q?
                             ?q?
                                ?q?
                                   ?q?
                                      ?q?
                                         ?q?
                                            ?q?
                                               ?q?
                                                  ?q?
                                                     ?q?
                                                        ?q?
                                                           ?q?
                                                              ?q?
                                                                 ?q?
                                                                    ?q?
                                                                       ?q?
                                                                          ?q?
                                                                             ?q?
                                                                                ?q?
                                                                                   ?q?
                                                                                      ?q?
                                                                                         ?q?
                                                                                            ?q?
                                                                                              ?q?
  ?q?
     ?q?
        ?q?
           ?q?
              ?q?
                 ?q?
                    ?q?
                       ?q?
                          ?q?
                             ?q?
                                ?q?
                                   ?q?
                                      ?q?
                                         ?q?
                                            ?q?
                                               ?q?
                                                  ?q?
                                                     ?q?
                                                        ?q?
                                                           ?q?
                                                              ?q?
                                                                 ?q?
                                                                    ?q?
                                                                       ?q?
                                                                          ?q?
                                                                             ?q?
                                                                                ?q?
                                                                                   ?q?
                                                                                      ?q?
                                                                                         ?q?
                                                                                            ?q?
                                                                                              ?q?
  ?q?
     ?q?
        ?q?
           ?q?
              ?q?
                 ?q?
                    ?q?
                       ?q?
                          ?q?
                             ?q?
                                ?q?
q?      q?                         ?q?
q?
q?
:xxxsq~?@xxqxt
experimentsq~?@
               q~qx```

**Comment by hbarsnes** [comment]
Hi Tessa,

Yes, there is clearly something wrong with these cpsx files. In terms of the expected content, cpsx files are just the serialized version of the Java objects. So there's not really any easy way to validate the content by inspecting the file itself. I guess either something went wrong during the saving or the file was corrupted at a later point.

I assume there were no error messages when saving the files in the first place? Would be great if you could recreate one of the failing files and try to open it directly after saving? That way we could perhaps figure out when the corruption happens?

Best regards,
Harald

**Comment by TessaGillett** [comment]
Hi Harald,

Alright, good to know. As far as I remember there were no error messages the first time round, but I'm afraid I deleted my log file since then, so I can't go back to check.

I reran PeptideShaker and MzidCLI for one of these corrupted files actually and somehow it now all works out. No idea why, as everything is exactly the same, but I guess that I'll just go and do it for all of them now and hope the problem doesn't repeat itself. If it does, I'll be sure to let you know though so we can figure out what happened.

Thanks again!
Tessa
