### ISSUE TITLE
Error when exporting reports

### ISSUE THREAD

**Issue by naomi-u** [compomics/peptide-shaker#373]
Hi, 

I am trying to export reports with Export > Export Features. It works for some of my files but for others I am getting the error "An error occurred while generating the output".

Thank you in advance,
Naomi

**Comment by hbarsnes** [comment]
Hi Naomi,

Please have a look at the PeptideShaker log. You will find it via the Welcome dialog > Settings & Help > Help > Bug Report. (Or via Help > Bug Report on the main menu after opening a project.) It should hopefully tell you/us more about the source of the issue.

Best regards.
Harald

**Comment by naomi-u** [comment]
Hi Harald, 

Here is the log:

Mon Sep 09 14:25:22 CEST 2019: PeptideShaker version 1.16.42.
Memory given to the Java virtual machine: 5592580096.
Total amount of memory in the Java virtual machine: 128974848.
Free memory: 106487512.
Java version: 1.8.0_221.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.8.0_221
os.name: Windows 10
memory: 54.9/163.1
processors available: 8
useCommandThread: false
java.lang.IllegalArgumentException: The maximum length of cell contents (text) is 32,767 characters
	at org.apache.poi.hssf.usermodel.HSSFCell.setCellValue(HSSFCell.java:548)
	at org.apache.poi.hssf.usermodel.HSSFCell.setCellValue(HSSFCell.java:522)
	at com.compomics.util.io.export.writers.ExcelWriter.addSeparator(ExcelWriter.java:226)
	at com.compomics.util.io.export.ExportWriter.addSeparator(ExportWriter.java:136)
	at eu.isas.peptideshaker.export.sections.PsPeptideSection.writeSection(PsPeptideSection.java:179)
	at eu.isas.peptideshaker.export.PSExportFactory.writeExport(PSExportFactory.java:295)
	at eu.isas.peptideshaker.gui.exportdialogs.FeaturesPreferencesDialog$16.run(FeaturesPreferencesDialog.java:802)

Thank you, 
Naomi

**Comment by hbarsnes** [comment]
Hi Naomi,

The problem is the maximum amount of characters allowed in a cell in Excel workbooks. If you change the format to "Tab separated text file" the exports should work fine. This is done via the "Files of Type" option at the bottom of the export dialog.

Best regards,
Harald

**Comment by naomi-u** [comment]
Hi Harald, 

This worked, thank you!

Naomi
