### ISSUE TITLE
File input error

### ISSUE THREAD

**Issue by mavino** [compomics/peptide-shaker#377]
I am running SearchGUI-3.3.16 with 4 different search engines (X! Tandem, MS-GF+, OMSSA and Comet), my fasta file has around 140,000 entries and my spectrum file is around 60 MB. I am not running this analysis command line. The analysis calls by itself peptideshaker 1.16.42.
My computer is an Ubuntu 18.
By the moment peptide shaker opens up it throws a file input error: 
"the end of file was reached unexpectedly. The files seem to be corrupt and cannot be opened. I a file is a copy, make sure it is identical to the original"

This is the derbi.log
```
Wed Oct 16 11:38:17 EDT 2019:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.10.1.1 - (1458268): instance a816c00e-016d-d538-4373-000032714b78 
on database directory /home/mariano/Downloads/PeptideShaker-1.16.42/resources/matches/Uniprot_2017-9_Exp2_fdr1_0_id with class loader jdk.internal.loader.ClassLoaders$AppClassLoader@1affbebc 
Loaded from file:/home/mariano/Downloads/PeptideShaker-1.16.42/lib/derby-10.10.1.1.jar
java.vendor=Ubuntu
java.runtime.version=11.0.4+11-post-Ubuntu-1ubuntu218.04.3
user.dir=/home/mariano/Downloads/PeptideShaker-1.16.42
os.name=Linux
os.arch=amd64
os.version=4.15.0-65-generic
derby.system.home=null
Database Class Loader started - derby.database.classpath=''
----------------------------------------------------------------
Wed Oct 16 11:45:22 EDT 2019: Shutting down Derby engine
----------------------------------------------------------------
Wed Oct 16 11:45:22 EDT 2019:
Shutting down instance a816c00e-016d-d538-4373-000032714b78 on database directory /home/mariano/Downloads/PeptideShaker-1.16.42/resources/matches/Uniprot_2017-9_Exp2_fdr1_0_id with class loader jdk.internal.loader.ClassLoaders$AppClassLoader@1affbebc 
```

Here is my peptideshaker.log

```
Wed Oct 16 11:45:24 EDT 2019: PeptideShaker version 1.16.42.
Memory given to the Java virtual machine: 4294967296.
Total amount of memory in the Java virtual machine: 136314880.
Free memory: 69749248.
Java version: 11.0.4.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Ubuntu
java.version: 11.0.4
os.name: Linux
memory: 50.4/136.3
processors available: 12
useCommandThread: false
java.io.OptionalDataException
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1614)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:430)
	at java.base/java.util.HashMap.readObject(HashMap.java:1458)
	at java.base/jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1160)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2216)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2087)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1594)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2355)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2249)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2087)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1594)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2355)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2249)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2087)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1594)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:430)
	at java.base/java.util.HashMap.readObject(HashMap.java:1460)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1160)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2216)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2087)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1594)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2355)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2249)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2087)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1594)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:430)
	at java.base/java.util.HashMap.readObject(HashMap.java:1460)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1160)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2216)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2087)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1594)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2355)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2249)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2087)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1594)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:430)
	at java.base/java.util.HashMap.readObject(HashMap.java:1460)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1160)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2216)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2087)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1594)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2355)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2249)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2087)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1594)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:430)
	at java.base/java.util.HashMap.readObject(HashMap.java:1460)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1160)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2216)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2087)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1594)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2355)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2249)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2087)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1594)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:430)
	at com.compomics.util.io.SerializationUtils.readObject(SerializationUtils.java:58)
	at com.compomics.util.experiment.io.ExperimentIO.loadExperiment(ExperimentIO.java:44)
	at eu.isas.peptideshaker.fileimport.CpsFileImporter.<init>(CpsFileImporter.java:57)
	at eu.isas.peptideshaker.utils.CpsParent.loadCpsFile(CpsParent.java:205)
	at eu.isas.peptideshaker.gui.PeptideShakerGUI$104.run(PeptideShakerGUI.java:5448)
```

Would you please help me out...
Thank you very much

**Comment by hbarsnes** [comment]
Hi Mariano,

It indeed seems like your PeptideShaker file has gotten corrupted. Have you tried repeating the process to check whether the error is reproducible? This kind of error may occur if the underlying files are altered during the saving of the PeptideShaker, for example by automatic backup systems or similar.

Can you also share the SearchGUI log? It should reveal if something went wrong during the creation of the PeptideShaker project.

Best regards,
Harald

**Comment by mavino** [comment]
No I was not able to reproduce this error and I do not have that specific log...if happens I will post here again.
Thanks a lot.

**Comment by mavino** [comment]
just happened again:
SearchGUI log
```
makeblastdb command: 
/home/mariano/Downloads/SearchGUI-3.3.16/resources/makeblastdb/linux/linux_64bit/makeblastdb -in human-openprot-r1_3-refprots-grch38.83+grch38.p7+uniprot2017_09_27_mod_concatenated_target_decoy.fasta -dbtype prot 



xtandem command: 
/home/mariano/Downloads/SearchGUI-3.3.16/resources/XTandem/linux/linux_64bit/tandem /home/mariano/Downloads/SearchGUI-3.3.16/resources/XTandem/linux/linux_64bit/input_searchGUI.xml 



ms-gf+ command: 
/usr/lib/jvm/java-11-openjdk-amd64/bin/java -Xms128M -Xmx4096M -jar /home/mariano/Downloads/SearchGUI-3.3.16/resources/MS-GF+/MSGFPlus.jar -s /home/mariano/Documents/Roucou/proteogenomic/Exp2_786O_nox_scr.mgf -d /home/mariano/Documents/Roucou/proteogenomic/RefProts_OpenProt v1.3/human-openprot-r1_3-refprots-grch38.83+grch38.p7+uniprot2017_09_27_mod_concatenated_target_decoy.fasta -o /home/mariano/Documents/Roucou/proteogenomic/RefProts_OpenProt v1.3/.SearchGUI_temp/Exp2_786O_nox_scr.msgf.mzid -t 5.0ppm -tda 0 -mod /home/mariano/Downloads/SearchGUI-3.3.16/resources/MS-GF+/params/Mods.txt -minCharge 2 -maxCharge 4 -inst 3 -thread 12 -m 3 -e 1 -ntt 2 -protocol 0 -minLength 8 -maxLength 30 -n 10 -addFeatures 0 -ti 0,1 



omssa command: 
/home/mariano/Downloads/SearchGUI-3.3.16/resources/OMSSA/linux/omssacl -w -to 0.02 -te 5.0 -teppm -e 0 -v 1 -zl 2 -zh 4 -zt 3 -ti 1 -tex 1446.94 -cl 0.0 -ch 0.2 -ci 5.0E-4 -w1 27 -w2 14 -h1 2 -h2 2 -hl 30 -hc 30 -hm 2 -hs 4 -ht 6 -mm 128 -zoh 2 -z1 0.95 -pc 1 -sb1 0 -sp 100 -scorp 0.5 -is 0.0 -ir 0.0 -ii 0.01 -he 100.0 -tez 1 -zcc 2 -cp 0 -no 8 -nox 30 -tom 0 -tem 0 -i 1,4 -mf 119 -mv 120 -d human-openprot-r1_3-refprots-grch38.83+grch38.p7+uniprot2017_09_27_mod_concatenated_target_decoy.fasta -fm /home/mariano/Documents/Roucou/proteogenomic/Exp2_786O_nox_scr.mgf -ox /home/mariano/Documents/Roucou/proteogenomic/RefProts_OpenProt v1.3/.SearchGUI_temp/Exp2_786O_nox_scr.omx -nt 12 



comet command: 
/home/mariano/Downloads/SearchGUI-3.3.16/resources/Comet/linux/comet.exe /home/mariano/Documents/Roucou/proteogenomic/Exp2_786O_nox_scr.mgf 



PeptideShaker command: 
/usr/lib/jvm/java-11-openjdk-amd64/bin/java -Xms128M -Xmx4096M -cp PeptideShaker-1.16.42.jar eu.isas.peptideshaker.cmd.PeptideShakerCLI -experiment RefsProt -sample exp2_fdr1 -replicate 0 -identification_files /home/mariano/Documents/Roucou/proteogenomic/RefProts_OpenProt v1.3/searchgui_out.zip -spectrum_files /home/mariano/Documents/Roucou/proteogenomic/Exp2_786O_nox_scr.mgf -id_params /home/mariano/.compomics/identification_parameters/RefsProt_exp2_fdr1.par -out /home/mariano/Documents/Roucou/proteogenomic/RefProts_OpenProt v1.3/PeptideShaker_RefsProt_exp2_fdr1.cpsx -gui 1 



PeptideShaker command: 
/usr/lib/jvm/java-11-openjdk-amd64/bin/java -Xms128M -Xmx4096M -jar PeptideShaker-1.16.42.jar -cps /home/mariano/Documents/Roucou/proteogenomic/RefProts_OpenProt v1.3/PeptideShaker_RefsProt_exp2_fdr1.cpsx 
```
derby.log
```
----------------------------------------------------------------
Mon Oct 21 11:25:52 EDT 2019:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.10.1.1 - (1458268): instance a816c00e-016d-eeec-b27f-00003afaead0 
on database directory /home/mariano/Downloads/PeptideShaker-1.16.42/resources/matches/RefsProt_exp2_fdr1_0_id with class loader jdk.internal.loader.ClassLoaders$AppClassLoader@1affbebc 
Loaded from file:/home/mariano/Downloads/PeptideShaker-1.16.42/lib/derby-10.10.1.1.jar
java.vendor=Ubuntu
java.runtime.version=11.0.4+11-post-Ubuntu-1ubuntu218.04.3
user.dir=/home/mariano/Downloads/PeptideShaker-1.16.42
os.name=Linux
os.arch=amd64
os.version=4.15.0-65-generic
derby.system.home=null
Database Class Loader started - derby.database.classpath=''
----------------------------------------------------------------
Mon Oct 21 11:27:06 EDT 2019: Shutting down Derby engine
----------------------------------------------------------------
Mon Oct 21 11:27:06 EDT 2019:
Shutting down instance a816c00e-016d-eeec-b27f-00003afaead0 on database directory /home/mariano/Downloads/PeptideShaker-1.16.42/resources/matches/RefsProt_exp2_fdr1_0_id with class loader jdk.internal.loader.ClassLoaders$AppClassLoader@1affbebc 
----------------------------------------------------------------
```
peptideshaker.log
```
Mon Oct 21 11:27:08 EDT 2019: PeptideShaker version 1.16.42.
Memory given to the Java virtual machine: 4294967296.
Total amount of memory in the Java virtual machine: 136314880.
Free memory: 117463040.
Java version: 11.0.4.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Ubuntu
java.version: 11.0.4
os.name: Linux
memory: 51.2/136.3
processors available: 12
useCommandThread: false
java.io.OptionalDataException
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1614)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:430)
	at java.base/java.util.HashMap.readObject(HashMap.java:1458)
	at java.base/jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1160)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2216)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2087)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1594)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2355)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2249)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2087)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1594)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2355)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2249)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2087)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1594)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:430)
	at java.base/java.util.HashMap.readObject(HashMap.java:1460)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1160)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2216)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2087)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1594)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2355)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2249)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2087)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1594)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:430)
	at java.base/java.util.HashMap.readObject(HashMap.java:1460)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1160)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2216)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2087)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1594)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2355)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2249)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2087)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1594)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:430)
	at java.base/java.util.HashMap.readObject(HashMap.java:1460)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1160)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2216)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2087)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1594)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2355)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2249)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2087)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1594)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:430)
	at java.base/java.util.HashMap.readObject(HashMap.java:1460)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1160)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2216)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2087)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1594)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2355)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2249)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2087)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1594)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:430)
	at com.compomics.util.io.SerializationUtils.readObject(SerializationUtils.java:58)
	at com.compomics.util.experiment.io.ExperimentIO.loadExperiment(ExperimentIO.java:44)
	at eu.isas.peptideshaker.fileimport.CpsFileImporter.<init>(CpsFileImporter.java:57)
	at eu.isas.peptideshaker.utils.CpsParent.loadCpsFile(CpsParent.java:205)
	at eu.isas.peptideshaker.gui.PeptideShakerGUI$104.run(PeptideShakerGUI.java:5448)
```

**Comment by mavino** [comment]
So I closed the old and opened a new instance of SearchGUI and everything worked out

**Comment by hbarsnes** [comment]
I guess the only tip I have is to make sure that you are not having more than one PeptideShaker instances running at the same time. Also, I'd recommend not using OpenJDK if possible.

**Comment by mavino** [comment]
Unfortunately this error is still happening sporadically even with the newer version SearchGUI-3.3.17, and I am sure i have just one version of PeptideShaker opened, what do you mean when you say do not use OpenJDK?...another crazy thing that happens sporadically is checking for Comet search while the analysis does not actually perform it...the config file for comet stays false...

**Comment by hbarsnes** [comment]
> what do you mean when you say do not use OpenJDK?

It is recommended to use the Oracle version of Java as it is more stable and have less issues than the OpenJDK version. Not sure of that is the problem here, but it could make a difference.

> another crazy thing that happens sporadically is checking for Comet search while the analysis does not actually perform it...the config file for comet stays false...

Sounds very strange indeed. Are you running more than one search at the same time from the same SearchGUI jar file? Let me know if you manage to figure out if you do anything different when this happens.

**Comment by mavino** [comment]
these are the version of java I have on my machine:
/usr/lib/jvm/java-11-openjdk-amd64/bin/java
/usr/local/java/jdk1.8.0_202/bin/java

I used them both but I still have the problem

**Comment by hbarsnes** [comment]
> these are the version of java I have on my machine:
> java-11-openjdk-amd64
> jdk1.8.0_202
> jre1.8.0_202
> I used all of them but I still have the problem...

Ok. So that is not the problem in this case then. Should hopefully be fixed in the upcoming new release of PeptideShaker, as there we have replaced the database backend. I'll let you know as soon as it is available for testing.

> regarding Comet problem, I have checked 4 different search engines in the same instance...

That should not be an issue. Can you tell me which four search engines so that I can try to reprodue the error on my end?

**Comment by mavino** [comment]
The error is sporadic, it happens once in a while...
anyways these are the engines:
X! Tandem, MS-GF+, OMSSA and Comet.

Thank you very much for everything

**Comment by mavino** [comment]
So this is the thing to be more precise
I let peptideshaker directly be called by searchgui...
so searchgiu runs and at the end calls peptideshaker...I get my stuff from it like exporting features then I close peptideshaker, re using the same searchgui that I had open originally...
I run the analysis for another sample, peptideshaker opens again and so on.
This lasts between 4 or 5 times reusing the same instance of searchgui with 4, 5 different samples, then suddenly while opening peptideshaker I get the file configuration error...

**Comment by hbarsnes** [comment]
> This lasts between 4 or 5 times reusing the same instance of searchgui with 4, 5 different samples, then suddenly while opening peptideshaker I get the file configuration error...

If running that many instances of SearchGUI/PeptideShaker in a row, you may consider using the command lines instead? See https://github.com/compomics/searchgui/wiki/SearchCLI and https://github.com/compomics/peptide-shaker/wiki/PeptideShakerCLI.

**Comment by hbarsnes** [comment]
This issue should hopefully be solved in the new beta releases of SearchGUI and PeptideShaker. Please see https://groups.google.com/forum/#!topic/peptide-shaker/1ecY0IyMOBM for more details.

If the issue still exists in the beta releases, please open a new issue at https://github.com/compomics/peptide-shaker-2.0-issue-tracker/issues.

If the issue has been solved, it would also be great of you could let us know by replying to this original issue and letting us know. :)

**Comment by mavino** [comment]
OK I will test those when I have the opportunity.
Thank you very much for everything.
