### ISSUE TITLE
Unknown error in peptide shaker

### ISSUE THREAD

**Issue by jpcouturepbs** [compomics/peptide-shaker#382]
Hi guys,

I have the following error while performing a peptideshaker project:

Tue Nov 26 10:02:44 EST 2019: PeptideShaker version 1.16.42.
Memory given to the Java virtual machine: 3817865216.
Total amount of memory in the Java virtual machine: 163053568.
Free memory: 123867144.
Java version: 1.8.0_231.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.8.0_231
os.name: Windows 10
memory: 53.6/163.1
processors available: 16
useCommandThread: false
<CompomicsError>PeptideShaker processing failed. See the PeptideShaker log for details.</CompomicsError>
java.lang.NullPointerException
	at eu.isas.peptideshaker.parameters.PSPtmScores.changeRepresentativeSite(PSPtmScores.java:227)
	at eu.isas.peptideshaker.ptm.PtmScorer.peptideInference(PtmScorer.java:1862)
	at eu.isas.peptideshaker.PeptideShaker.processIdentifications(PeptideShaker.java:387)
	at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importFiles(FileImporter.java:547)
	at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.doInBackground(FileImporter.java:431)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Free memory: 1325044184

Would you happen to know what could be the issue?

Thanks a ton!

JP

**Comment by hbarsnes** [comment]
Hi JP,

This issue should hopefully be solved in the new beta releases of SearchGUI and PeptideShaker. See https://groups.google.com/forum/#!topic/peptide-shaker/1ecY0IyMOBM for more details.

If the issue still exists in the beta releases, please open a new issue at https://github.com/compomics/peptide-shaker-2.0-issue-tracker/issues.

Best regards,
Harald

**Comment by jpcouturepbs** [comment]
Will do. 
Thanks for the quick answer Harald!
JP

**Comment by hbarsnes** [comment]
This issue should hopefully be fixed in the new release that is available now. If not, please let us know by opening a new issue.
