### ISSUE TITLE
Error while running peptide shaker from command line 

### ISSUE THREAD

**Issue by MohmedSoudy** [compomics/peptide-shaker#392]
Wed Feb 26 09:30:40 EET 2020: PeptideShaker version 1.16.44.
Memory given to the Java virtual machine: 15271460864.
Total amount of memory in the Java virtual machine: 1029177344.
Free memory: 973130168.
Java version: 1.8.0_231.
java.io.FileNotFoundException: C:\Softwares\PeptideShaker-1.16.44\resources\matches\200211-S24_200211-S24_1_id\log\log2.dat (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at com.compomics.util.io.compression.TarUtils.addFile(TarUtils.java:181)
	at com.compomics.util.io.compression.TarUtils.addFolderContent(TarUtils.java:139)
	at com.compomics.util.io.compression.TarUtils.addFolderContent(TarUtils.java:137)
	at com.compomics.util.io.compression.TarUtils.addFolderContent(TarUtils.java:113)
	at com.compomics.util.io.compression.TarUtils.tarFolderContent(TarUtils.java:83)
	at eu.isas.peptideshaker.export.CpsExporter.saveAs(CpsExporter.java:119)
	at eu.isas.peptideshaker.utils.CpsParent.saveProject(CpsParent.java:310)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:207)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:957)

**Comment by hbarsnes** [comment]
Can you share the command line you are running?

Also, please make sure that you are only running one PeptideShaker instance at the time.

**Comment by javanOkendo** [comment]
@MohmedSoudy I also got this error and it is because I was running more than once instance of PeptideShaker

**Comment by hbarsnes** [comment]
Issue assumed resolved. If this is not the case, please let us know and we'll reopen the issue.
