### ISSUE TITLE
java.sql.SQLException: Container 3,440 not found.

### ISSUE THREAD

**Issue by javanOkendo** [compomics/peptide-shaker#395]
What could be causing this problem
ava.sql.SQLException: Container 3,440 not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.execute(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeQuery(Unknown Source)
	at com.compomics.util.db.ObjectsDB.getTableContentFromDBNoMutex(ObjectsDB.java:1198)
	at com.compomics.util.db.ObjectsDB.insertObjects(ObjectsDB.java:407)
	at com.compomics.util.db.ObjectsCache.saveObjects(ObjectsCache.java:452)
	at com.compomics.util.db.ObjectsCache.saveObjects(ObjectsCache.java:361)
	at com.compomics.util.db.ObjectsCache.updateCacheSynchronized(ObjectsCache.java:609)
	at com.compomics.util.db.ObjectsCache.updateCache(ObjectsCache.java:581)
	at com.compomics.util.db.ObjectsCache.addObject(ObjectsCache.java:333)
	at com.compomics.util.db.ObjectsDB.retrieveObject(ObjectsDB.java:1049)
	at com.compomics.util.db.ObjectsDB.retrieveObject(ObjectsDB.java:927)
	at com.compomics.util.db.ObjectsDB.retrieveObject(ObjectsDB.java:889)
	at com.compomics.util.experiment.identification.IdentificationDB.getAssumptions(IdentificationDB.java:436)
	at com.compomics.util.experiment.identification.Identification.getAssumptions(Identification.java:982)
	at com.compomics.util.experiment.identification.Identification.getAssumptions(Identification.java:1002)
	at eu.isas.peptideshaker.validation.MatchesValidator$PsmValidatorRunnable.run(MatchesValidator.java:1485)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: Container 3,440 not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 27 more
Caused by: ERROR XSCH1: Container 3,440 not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.store.access.heap.Heap.openStoreCost(Unknown Source)
	at org.apache.derby.impl.store.access.RAMTransaction.openStoreCost(Unknown Source)
	at org.apache.derby.impl.sql.compile.CompilerContextImpl.getStoreCostController(Unknown Source)
	at org.apache.derby.impl.sql.compile.FromBaseTable.getStoreCostController(Unknown Source)
	at org.apache.derby.impl.sql.compile.FromBaseTable.estimateCost(Unknown Source)
	at org.apache.derby.impl.sql.compile.OptimizerImpl.estimateTotalCost(Unknown Source)
	at org.apache.derby.impl.sql.compile.OptimizerImpl.costBasedCostOptimizable(Unknown Source)
	at org.apache.derby.impl.sql.compile.OptimizerImpl.costOptimizable(Unknown Source)
	at org.apache.derby.impl.sql.compile.FromBaseTable.optimizeIt(Unknown Source)
	at org.apache.derby.impl.sql.compile.ProjectRestrictNode.optimizeIt(Unknown Source)
	at org.apache.derby.impl.sql.compile.OptimizerImpl.costPermutation(Unknown Source)
	at org.apache.derby.impl.sql.compile.SelectNode.optimize(Unknown Source)
	at org.apache.derby.impl.sql.compile.DMLStatementNode.optimizeStatement(Unknown Source)
	at org.apache.derby.impl.sql.compile.CursorNode.optimizeStatement(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepMinion(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepare(Unknown Source)
	at org.apac

**Comment by hbarsnes** [comment]
I'm afraid you've come across an error with our backend that we have been trying to solve for a long time. There are beta versions you can test: https://groups.google.com/forum/#!topic/peptide-shaker/1ecY0IyMOBM. However, when we were close to releasing these versions we found an error in opening saved projects, resulting in that we had to make even more changes. With the beta releases you should be able to process the data and export the results though.

**Comment by javanOkendo** [comment]
@hbarsnes Do I have rerun the SearchGUI again and then run the PeptideShaker afterwards?

**Comment by hbarsnes** [comment]
> Do I have rerun the SearchGUI again and then run the PeptideShaker afterwards?

Yes, that is probably recommended. Although it should be possible to load the old SearchGUI results if you set up a new parameter file when loading the data in PeptideShaker.

**Comment by javanOkendo** [comment]
Hi,

Thanks I will generate a new parameter file and let you know

**Comment by javanOkendo** [comment]
Dear Compomics/Peptide-Shaker team,

Is the new the beta version of the searchGUI supporing the PEFF database
search?

**Comment by hbarsnes** [comment]
> Is the new the beta version of the searchGUI supporing the PEFF database search?

No, I'm afraid not. But it is on our list of things to look into. Actually, the challenge is not so much in adding the support in SearchGUI, but rather in how to display such results in PeptideShaker, which will probably require a rethinking of how we handle PTMs.

**Comment by hbarsnes** [comment]
This issue should hopefully be fixed in the new release that is available now. If not, please let us know by opening a new issue.
