### ISSUE TITLE
Error while reading *.cpsx file

### ISSUE THREAD

**Issue by VladimirRoudko** [compomics/peptide-shaker#417]
Hello,

I am encounter issue while generating reports using PeptideShaker eu.isas.peptideshaker.cmd.ReportCLI, run from command line.
Configuration: Linux, Java version: 11.0.7., Total amount of memory in the Java virtual machine: 2155872256

I generate the PeptideShaker *.cpsx file first: 
java $JAVA_OPTS -cp $peptideshaker eu.isas.peptideshaker.cmd.PeptideShakerCLI \
-experiment myExperiment \
-sample "${INPUT}" \
-replicate 1 \
     -identification_files "$PWD/search" \
      -spectrum_files "$PWD/mgf" \
      -id_params "$PWD/identification.par" \
      -out "$PWD/peptideshaker/${fn}.cpsx" \
       -threads ${THREADS}

After I generate the reports:

java $JAVA_OPTS -cp $peptideshaker eu.isas.peptideshaker.cmd.ReportCLI \
        -in "$PWD/peptideshaker/${INPUT}.cpsx" \
        -out_reports "$PWD/report" \
        -reports "0, 3, 6, 9" \
        -documentation "0, 3, 6, 9"

I got the following error in PeptideShaker.log file:

Fri Sep 18 11:37:26 EDT 2020: PeptideShaker version 1.16.45.
Memory given to the Java virtual machine: 32178700288.
Total amount of memory in the Java virtual machine: 2155872256.
Free memory: 2127882240.
Java version: 11.0.7.
java.io.OptionalDataException
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1669)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:464)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at java.base/java.util.HashMap.readObject(HashMap.java:1458)
	at java.base/jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
     .......................

Thank you for help!

Vladimir

**Comment by VladimirRoudko** [comment]
Sorry, I just got the fix for the problem, thank you!
