### ISSUE TITLE
SearchGUI4.0.1 ERROR

### ISSUE THREAD

**Issue by vipulbatra1985** [compomics/peptide-shaker#427]
I am trying to analyses 8 .raw files on Search GUI 4.0.1 using Comet search engine and getting following in the bug report within a second :

comet command: 
D:\SearchGUI-4.0.1\resources\Comet\windows\windows_64bit\comet.exe D:\demo_searchGUI\raw_hf\A1-1.mzml 

java.io.FileNotFoundException: Source 'D:\demo_searchGUI\raw_hf\A1-1.comet.pep.xml' does not exist
	at org.apache.commons.io.FileUtils.moveFile(FileUtils.java:2995)
	at eu.isas.searchgui.SearchHandler$SearchWorker.doInBackground(SearchHandler.java:2936)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Similarly, while using andromeda : 
makeblastdb command: 
D:\SearchGUI-4.0.1\resources\makeblastdb\windows\makeblastdb -in uniprot-proteome_UP000009136_concatenated_target_decoy.fasta -dbtype prot 

java.io.FileNotFoundException: D:\SearchGUI-4.0.1\resources\Andromeda\windows\temp\uniprot-proteome_UP000009136_concatenated_target_decoy.fasta (The system cannot find the path specified)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileWriter.<init>(Unknown Source)
	at com.compomics.util.experiment.io.biology.protein.converters.GenericFastaConverter.convertFile(GenericFastaConverter.java:40)
	at eu.isas.searchgui.processbuilders.AndromedaProcessBuilder.createGenericFastaFile(AndromedaProcessBuilder.java:224)
	at eu.isas.searchgui.SearchHandler$SearchWorker.doInBackground(SearchHandler.java:2303)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Please Help to resolve.

**Comment by hbarsnes** [comment]
The Andromeda issues was due to a missing temp folder. This problem has now been fixed an a new version has been deployed.

I'm not able to reproduce the issue you are having with Comet though. Do you have any other information from Comet itself? Is it actually completing the search?
