### ISSUE TITLE
paths.txt is always written where .jar is located no matter temp settings

### ISSUE THREAD

**Issue by CarlosHorro** [compomics/peptide-shaker#445]
When running PS in Galaxy it uses "-temp_folder" option, but still paths.txt is always written into the same folder than the .jar is located:
```

java.lang.RuntimeException: java.io.FileNotFoundException: /usr/local/share/peptide-shaker-2.0.15-0/resources/conf/paths.txt (Permission denied)
at com.compomics.util.io.flat.SimpleFileWriter.(SimpleFileWriter.java:59)
at eu.isas.peptideshaker.preferences.PeptideShakerPathParameters.writeConfigurationToFile(PeptideShakerPathParameters.java:391)
at eu.isas.peptideshaker.cmd.PathSettingsCLI.setPathSettings(PathSettingsCLI.java:110)
at eu.isas.peptideshaker.cmd.PathSettingsCLI.extractAndUpdatePathOptions(PathSettingsCLI.java:269)
at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:1366)
Caused by: java.io.FileNotFoundException: /usr/local/share/peptide-shaker-2.0.15-0/resources/conf/paths.txt (Permission denied)
at java.base/java.io.FileOutputStream.open0(Native Method)
at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
at java.base/java.io.FileOutputStream.(FileOutputStream.java:237)
at java.base/java.io.FileOutputStream.(FileOutputStream.java:187)
at java.base/java.io.FileWriter.(FileWriter.java:96)
at com.compomics.util.io.flat.SimpleFileWriter.(SimpleFileWriter.java:53)
... 4 more


```

UtilitiesPathParameters.configurationFileName have to be properly managed in PathSettingsCLI.

**Comment by bernt-matthias** [comment]
This still happens in the latest version .. (2.0.25)

**Comment by hbarsnes** [comment]
> This still happens in the latest version .. (2.0.25)

I know. It has not been looked into yet. Hence the reason why the issue is still open. ;)

**Comment by bernt-matthias** [comment]
I stumbled over this problem again. Since we are now using containers the error message looks slighly different (`resources/conf/paths.txt (Read-only file system)`) which made the Galaxy tool fail again. 

Is there any chance to implement solution for this problem? 

For instance could you check for the presence of an environment variable that we could use to define a path before resorting to the jar path?  This seems rather trivial to do and non-intrusive to other installations.

**Comment by hbarsnes** [comment]
I'm afraid that PeptideShaker is no longer in active development but if you implement your own fix and provide a pull request I can always have a quick look at it and then release a new version if that would help.

**Comment by bernt-matthias** [comment]
Thanks I will try to update SG and PS Galaxy tools to the latest verison first.
