### ISSUE TITLE
exportFactory problem

### ISSUE THREAD

**Issue by bernt-matthias** [compomics/peptide-shaker#448]
On PS 2.0.15 (via Galaxy) we observe:

```
java.io.FileNotFoundException: /work/songalax/galaxy/database/jobs_directory/000/107/107722/working/PeptideShakerCLI/exportFactory.json (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at com.compomics.util.io.json.JsonMarshaller.getJsonStringFromFile(JsonMarshaller.java:227)
	at com.compomics.util.io.json.JsonMarshaller.fromJson(JsonMarshaller.java:142)
	at eu.isas.peptideshaker.export.PSExportFactory.loadFromFile(PSExportFactory.java:158)
	at eu.isas.peptideshaker.export.PSExportFactory.getInstance(PSExportFactory.java:99)
	at eu.isas.peptideshaker.cmd.ReportCLIParams.<clinit>(ReportCLIParams.java:17)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLIParams.createOptionsCLI(PeptideShakerCLIParams.java:76)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:1370)
```

The odd thing is that the file is there (I checked its existence before and after the run):

`file /work/songalax/galaxy/database/jobs_directory/000/107/107722/working/PeptideShakerCLI/exportFactory.json`:

```
/work/songalax/galaxy/database/jobs_directory/000/107/107722/working/PeptideShakerCLI/exportFactory.json: ASCII text
```
Content is:

```
{
  "userSchemes": {}
}
```

**Comment by CarlosHorro** [comment]
Hi @bernt-matthias ,

Just to mention that this exception does not imply any malfunctioning but it clarifies that the exportFactory.json does not exist and it will be created. However, after managing some other bugs we will improve it in order to avoid any confusion.

Greetings,
Carlos

**Comment by bernt-matthias** [comment]
Thanks for the info. Then we should think about if we should

- remove this https://github.com/galaxyproteomics/tools-galaxyp/blob/2d431b6ee383f3013d6de3cce64349d51642c33b/tools/peptideshaker/macros_basic.xml#L6 from the wrapper
- or make SG/PS indicate such things in a different way.

**Comment by hbarsnes** [comment]
> or make SG/PS indicate such things in a different way.

@bernt-matthias It will be replaced by a normal text message in the next release.

**Comment by hbarsnes** [comment]
A new version has just been deployed where the stack trace is no longer being printed.
