### ISSUE TITLE
PeptideShaker error when loading SearchGui output

### ISSUE THREAD

**Issue by kromer-m** [compomics/peptide-shaker#479]
Hello,
I ran SearchGui search using ThermoRaw converter and MS-GF+. When some files are processed, the loading in PeptideShaker is aborted with following error (from log):

`Wed Feb 09 12:31:03 CET 2022: PeptideShaker version 2.2.5.
Memory given to the Java virtual machine: 3817865216.
Total amount of memory in the Java virtual machine: 128974848.
Free memory: 113782192.
Java version: 1.8.0_311.
java.lang.ArrayIndexOutOfBoundsException: 63193
	at com.compomics.util.experiment.io.identification.idfilereaders.MzIdentMLIdfileReader.parsePsm(MzIdentMLIdfileReader.java:757)
	at com.compomics.util.experiment.io.identification.idfilereaders.MzIdentMLIdfileReader.parseFile(MzIdentMLIdfileReader.java:301)
	at com.compomics.util.experiment.io.identification.idfilereaders.MzIdentMLIdfileReader.getAllSpectrumMatches(MzIdentMLIdfileReader.java:202)
	at eu.isas.peptideshaker.fileimport.FileImporter.importPsms(FileImporter.java:466)
	at eu.isas.peptideshaker.fileimport.FileImporter.importFiles(FileImporter.java:277)
	at eu.isas.peptideshaker.PeptideShaker.importFiles(PeptideShaker.java:219)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.createProject(PeptideShakerCLI.java:1249)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:245)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:1465)`

Do you have by any chance, what is going on? Most files are processed without any errors. Thank you!

**Comment by hbarsnes** [comment]
Hi! Seems like there is an error when parsing the spectrum titles for some of your MS-GF+ mzIdentML files. Any chance you can share one of these files so that we can try to figure out why?

**Comment by hbarsnes** [comment]
Oh, and I would also need the corresponding spectrum file (in order to be able to load the data and reproduce the issue).

**Comment by kromer-m** [comment]
Great, 
here is
mzid: [https://cloud.uochb.cas.cz/owncloud/index.php/s/RYs33Z0StpPu17j](url)
ThermoRAW [https://cloud.uochb.cas.cz/owncloud/index.php/s/f0hSyOHpJXKxtWD](url)

Thanks!

**Comment by hbarsnes** [comment]
Did you do the raw file conversion separately outside of SearchGUI? As the mzid file you shared indicates that mgf was used as input, while SearchGUI's internal conversion (using ThermoRawFileParser) rather converts the raw file to mzml with regards to input to MS-GF+.

**Comment by kromer-m** [comment]
I always did the conversion using SearchGUI to either mzML or mgf. Both formats gave the same error. If I'm not mistaken, MS-GF+ should accept both files.

**Comment by hbarsnes** [comment]
Aha, I see. Forgot that we implemented this option directly in SearchGUI. :)

And yes, MS-GF+ does accept both mzml and mgf.

I have no issues loading the shared mzid file though. Perhaps you can also share the converted mgf file just to make sure that there are no differences there? It should be located next to your raw file.

**Comment by hbarsnes** [comment]
Thanks for sharing the mgf file. It is however identical do mine. Hence I still have no problems loading your mzid file...

Can you delete the file called 220202_MBH_538.cms that should be in the same folder as your mgf file? It contains an index of the spectra in the mgf file and will be regenerated the next time you select the same mgf file in PeptideShaker (or SearchGUI). After deleting the cms file, try loading the data in PeptideShaker again.

**Comment by carolinelennartsson** [comment]
I am also encountering errors while importing identify files using ms-gf+ in searchGUI. I'm posting this here because it sounds relevant to this thread. 

<img width="798" alt="Screenshot 2022-10-03 at 17 15 35" src="https://user-images.githubusercontent.com/70753896/194291721-54d90d77-8571-4894-b0d8-59f996e6b643.png">

**Comment by hbarsnes** [comment]
@carolinelennartsson I'm not sure if this is the same issue after all. Perhaps best of you set up a new issue and share the PeptideShaker log file there?
