### ISSUE TITLE
Peptideshaker run issues 

### ISSUE THREAD

**Issue by carolinelennartsson** [compomics/peptide-shaker#495]
I have been having some issues processing files with peptideshaker and would appreciate some help figuring out the problem. I'm not sure what's the issue here, if I put anything incorrect in the input. Can you help me? 
 
This is the error from the peptideshaker.log;
com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 95
Serialization trace:
peptideAssumptionsMap (com.compomics.util.experiment.identification.matches.SpectrumMatch)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:159)
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:758)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:869)
	at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:235)
	at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:42)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:799)
	at com.esotericsoftware.kryo.serializers.ReflectField.read(ReflectField.java:123)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:129)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:777)
	at com.compomics.util.db.object.ObjectsDB.loadFromDB(ObjectsDB.java:352)
	at com.compomics.util.db.object.ObjectsDB.retrieveObject(ObjectsDB.java:477)
	at com.compomics.util.experiment.identification.Identification.retrieveObject(Identification.java:243)
	at com.compomics.util.experiment.identification.Identification.getSpectrumMatch(Identification.java:258)
	at eu.isas.peptideshaker.processing.PsmProcessorRunnable.processPsm(PsmProcessorRunnable.java:191)
	at eu.isas.peptideshaker.processing.PsmProcessorRunnable.run(PsmProcessorRunnable.java:151)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
com.esotericsoftware.kryo.KryoException: java.lang.IllegalArgumentException: Can not set java.util.HashMap field com.compomics.util.experiment.identification.matches.SpectrumMatch.tagAssumptionsMap to java.lang.String
Serialization trace:

**Comment by hbarsnes** [comment]
I'm afraid this is a known backend issue to which the only known solution is to increase the amount of memory provided to PeptideShaker. You can do this via the PeptideShaker Welcome Dialog > Settings & Help > Settings > Java Settings > Memory. Can you try increasing the memory and see if that solves the problem?

**Comment by carolinelennartsson** [comment]
I'm afraid that I've allowed almost my ram for this preprocessing, over 30gb. Anything else I can try?

**Comment by hbarsnes** [comment]
Another option you can try is to use only one thread/core. This will however dramatically slow down the processing. But could be worth it if it allows you to complete the processing. You can change this via the Processing option at the bottom of the New Project dialog.
