### ISSUE TITLE
NullPointerException in Peptideshaker (searchGUI runs fine)

### ISSUE THREAD

**Issue by lukethompson16** [compomics/peptide-shaker#497]
I've used SearchGUI/Peptideshaker successfully several times with several datasets, but when I switched to a new database for a different organism, I have not been able to solve this issue that comes up when I move into peptideshaker. 

Wed Nov 09 11:29:39 EST 2022: PeptideShaker version 2.2.17.
Memory given to the Java virtual machine: 3817865216.
Total amount of memory in the Java virtual machine: 128974848.
Free memory: 86654120.
Java version: 1.8.0_333.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.8.0_333
os.name: Windows 10
memory: 62.8/163.1
processors available: 24
useCommandThread: false

Wed Nov 09 14:57:25 EST 2022: PeptideShaker version 2.2.17.
Memory given to the Java virtual machine: 3817865216.
Total amount of memory in the Java virtual machine: 128974848.
Free memory: 85966504.
Java version: 1.8.0_333.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.8.0_333
os.name: Windows 10
memory: 63.1/163.1
processors available: 24
useCommandThread: false
<CompomicsError>PeptideShaker processing failed. See the PeptideShaker log for details.</CompomicsError>
java.lang.NullPointerException
	at com.compomics.util.experiment.identification.protein_inference.fm_index.FMIndex.addDataToIndex(FMIndex.java:1493)
	at com.compomics.util.experiment.identification.protein_inference.fm_index.FMIndex.init(FMIndex.java:1204)
	at com.compomics.util.experiment.identification.protein_inference.fm_index.FMIndex.<init>(FMIndex.java:590)
	at eu.isas.peptideshaker.fileimport.FileImporter.importSequences(FileImporter.java:957)
	at eu.isas.peptideshaker.fileimport.FileImporter.importFiles(FileImporter.java:219)
	at eu.isas.peptideshaker.PeptideShaker.importFiles(PeptideShaker.java:219)
	at eu.isas.peptideshaker.gui.NewDialog$20.run(NewDialog.java:736)
	at java.lang.Thread.run(Unknown Source)
Free memory: 624791328

Thu Nov 10 10:28:23 EST 2022: PeptideShaker version 2.2.17.
Memory given to the Java virtual machine: 3817865216.
Total amount of memory in the Java virtual machine: 128974848.
Free memory: 86600216.
Java version: 1.8.0_333.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.8.0_333
os.name: Windows 10
memory: 63.3/163.1
processors available: 24
useCommandThread: false

Thu Nov 10 11:26:30 EST 2022: PeptideShaker version 2.2.17.
Memory given to the Java virtual machine: 3817865216.
Total amount of memory in the Java virtual machine: 163053568.
Free memory: 118720328.
Java version: 1.8.0_351.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.8.0_351
os.name: Windows 10
memory: 63.5/163.1
processors available: 24
useCommandThread: false
<CompomicsError>PeptideShaker processing failed. See the PeptideShaker log for details.</CompomicsError>
java.lang.NullPointerException
	at com.compomics.util.experiment.identification.protein_inference.fm_index.FMIndex.addDataToIndex(FMIndex.java:1493)
	at com.compomics.util.experiment.identification.protein_inference.fm_index.FMIndex.init(FMIndex.java:1204)
	at com.compomics.util.experiment.identification.protein_inference.fm_index.FMIndex.<init>(FMIndex.java:590)
	at eu.isas.peptideshaker.fileimport.FileImporter.importSequences(FileImporter.java:957)
	at eu.isas.peptideshaker.fileimport.FileImporter.importFiles(FileImporter.java:219)
	at eu.isas.peptideshaker.PeptideShaker.importFiles(PeptideShaker.java:219)
	at eu.isas.peptideshaker.gui.NewDialog$20.run(NewDialog.java:736)
	at java.lang.Thread.run(Unknown Source)
Free memory: 604892832

Tue Nov 15 15:21:53 EST 2022: PeptideShaker version 2.2.17.
Memory given to the Java virtual machine: 3817865216.
Total amount of memory in the Java virtual machine: 163053568.
Free memory: 118871576.
Java version: 1.8.0_351.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.8.0_351
os.name: Windows 10
memory: 64.0/163.1
processors available: 24
useCommandThread: false
<CompomicsError>PeptideShaker processing failed. See the PeptideShaker log for details.</CompomicsError>
java.lang.NullPointerException
	at com.compomics.util.experiment.identification.protein_inference.fm_index.FMIndex.addDataToIndex(FMIndex.java:1493)
	at com.compomics.util.experiment.identification.protein_inference.fm_index.FMIndex.init(FMIndex.java:1204)
	at com.compomics.util.experiment.identification.protein_inference.fm_index.FMIndex.<init>(FMIndex.java:590)
	at eu.isas.peptideshaker.fileimport.FileImporter.importSequences(FileImporter.java:957)
	at eu.isas.peptideshaker.fileimport.FileImporter.importFiles(FileImporter.java:219)
	at eu.isas.peptideshaker.PeptideShaker.importFiles(PeptideShaker.java:219)
	at eu.isas.peptideshaker.gui.NewDialog$20.run(NewDialog.java:736)
	at java.lang.Thread.run(Unknown Source)
Free memory: 728298728

**Comment by hbarsnes** [comment]
Would it be possible for you to share the FASTA file so that we can try to figure out what the problem is?

**Comment by lukethompson16** [comment]
Sure, FASTA is here: https://drive.google.com/file/d/1rJvoDHb6Z1FvJLTCA7mQLAjhKq3Sob3n/view?usp=sharing

**Comment by hbarsnes** [comment]
The problem is these two headers:

```
>prf||764671A vespakinin M
GRPXGFSPFRID

>prf||764671A_REVERSED vespakinin M_REVERSED
DIRFPSFGXPRG
```

Simply replacing "||" with "|" solves the problem.

In other words, replace the above with

```
>prf|764671A vespakinin M
GRPXGFSPFRID

>prf|764671A_REVERSED vespakinin M_REVERSED
DIRFPSFGXPRG
```

and you should be able to use the FASTA file without any issues.

**Comment by lukethompson16** [comment]
Yep, that was the issue. Guess part of an annotation was missing. Works fine now.

Thanks!
