### ISSUE TITLE
Fails to start up completely after initially did

### ISSUE THREAD

**Issue by bujar-klaiqi** [compomics/peptide-shaker#502]
PeptideShaker-2.2.17 and SearchGUI-4.1.24 fails to open with starting log:
`Cannot invoke "com.compomics.util.parameters.UtilitiesUserParameters.getMemoryParameter()" because "this.userParameters" is null`

cmd gives more info about it:
```
java -jar PeptideShaker-2.2.17.jar
java.lang.NullPointerException: Cannot invoke "com.compomics.util.parameters.UtilitiesUserParameters.getMemoryParameter()" because "this.userParameters" is null
        at com.compomics.software.CompomicsWrapper.launchTool(CompomicsWrapper.java:163)
        at eu.isas.peptideshaker.PeptideShakerWrapper.<init>(PeptideShakerWrapper.java:60)
        at eu.isas.peptideshaker.PeptideShakerZipFileChecker.<init>(PeptideShakerZipFileChecker.java:58)
        at eu.isas.peptideshaker.PeptideShakerZipFileChecker.main(PeptideShakerZipFileChecker.java:71)
```

After uninstalling jdk19 clicking in the file doesn't do anything while the cmd shows the following error:
```
java -jar PeptideShaker-2.2.17.jar
java.lang.NullPointerException
        at com.compomics.software.CompomicsWrapper.launchTool(CompomicsWrapper.java:163)
        at eu.isas.peptideshaker.PeptideShakerWrapper.<init>(PeptideShakerWrapper.java:60)
        at eu.isas.peptideshaker.PeptideShakerZipFileChecker.<init>(PeptideShakerZipFileChecker.java:58)
        at eu.isas.peptideshaker.PeptideShakerZipFileChecker.main(PeptideShakerZipFileChecker.java:71)
Exception in thread "main" java.lang.NullPointerException
        at java.io.Writer.write(Unknown Source)
        at com.compomics.software.CompomicsWrapper.launchTool(CompomicsWrapper.java:209)
        at eu.isas.peptideshaker.PeptideShakerWrapper.<init>(PeptideShakerWrapper.java:60)
        at eu.isas.peptideshaker.PeptideShakerZipFileChecker.<init>(PeptideShakerZipFileChecker.java:58)
        at eu.isas.peptideshaker.PeptideShakerZipFileChecker.main(PeptideShakerZipFileChecker.java:71)
```

Peptide Shaker first opened and then when trying to add the SearchGUI failed with this message and now whatever I do I get that message.

Already tried:
Getting a new download of PeptideShaker.
Uninstalled and reinstalled Java.
Removed all the java registry and installed it again.
Tried the new beta version 2.2.18beta.

Whatever I do, I keep getting that message. I believe it changed something in my computer but can't reverse and make it work again.

**Comment by hbarsnes** [comment]
It seems like your user parameters file has been corrupted. Please go to your user home folder and the subfolder ".compomics" and simply delete the file "userparameters.cup". This should allow you to again start the tools.

**Comment by bujar-klaiqi** [comment]
That fixed the error indeed. I didn't expect the app to create files in there. But it didn't fix the complete issue. Actually searchGUI now works well, but PeptideShaker gets stuck in the splashing screen. First time asked for the shortcut in Desktop and now just gets stuck in loading screen. I'll try to identify the issue more and respond here about my findings.

**Comment by hbarsnes** [comment]
Have a look at the PeptideShaker error log (PeptideShaker-2.2.17\resources\PeptideShaker.log), maybe you will find something there?

**Comment by bujar-klaiqi** [comment]
Not really. It just gets stuck somehow. It starts the splash screen and then it keeps "loading" indefinitely.

```
Memory settings read from the user preferences: 4096
args: 
original java.home: C:\Program Files\Java\jdk-19\bin\
new java.home: C:\Program Files\Java\jdk-19\bin\
Java runtime version: 19.0.1+10-21

Command line: 
"C:\Program Files\Java\jdk-19\bin\java" -splash:resources\conf\peptide-shaker-splash.png -Xms128M -Xmx4096M -cp "D:\bio-info\PeptideShaker-2.2.17\PeptideShaker-2.2.17.jar" eu.isas.peptideshaker.gui.PeptideShakerGUI 

```

**Comment by hbarsnes** [comment]
The file above is the startup.log and indeed does not seem to indicate any issues. Did you also check log file mentioned above (PeptideShaker-2.2.17\resources\PeptideShaker.log)?

**Comment by bujar-klaiqi** [comment]
Oops, sorry. I misread you. Indeed there is some error there. It's a long file but it is one error in repeat. I'll include one instance of it.

`Mon Dec 19 15:12:57 CET 2022: PeptideShaker version 2.2.17.
Memory given to the Java virtual machine: 4294967296.
Total amount of memory in the Java virtual machine: 134217728.
Free memory: 88389464.
Java version: 19.0.1.
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "eu.isas.peptideshaker.preferences.UserParameters.showSliders()" because the return value of "eu.isas.peptideshaker.gui.PeptideShakerGUI.getUserParameters()" is null
	at eu.isas.peptideshaker.gui.tabpanels.OverviewPanel$76.run(OverviewPanel.java:2699)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)`

**Comment by bujar-klaiqi** [comment]
That finally fixed the issue. My corrupted settings file included this line only (if you need it).

`aced 0005 70`
