### ISSUE TITLE
Exporting Extended PSM Report failed 

### ISSUE THREAD

**Issue by ClaSofMag** [compomics/peptide-shaker#513]
Hello,

Thank you in advance for your great support on this software. I encountered an issue in PeptideShaker while trying to export the extended PSM Report. Here's the bug report:

java.lang.IllegalArgumentException: Two modifications found (Acetylation of peptide N-term and Pyrolidone from Q) at site 0 of peptide QYNRFMVQCHLELQLETVWSCHWYSMNSWK.
	at com.compomics.util.experiment.biology.proteins.Peptide.getIndexedVariableModifications(Peptide.java:413)
	at com.compomics.util.experiment.biology.proteins.Peptide.getTaggedModifiedSequence(Peptide.java:1306)
	at eu.isas.peptideshaker.export.sections.PsIdentificationAlgorithmMatchesSection.getPeptideAssumptionFeature(PsIdentificationAlgorithmMatchesSection.java:758)
	at eu.isas.peptideshaker.export.sections.PsPsmSection.writeSection(PsPsmSection.java:241)
	at eu.isas.peptideshaker.export.PSExportFactory.writeExport(PSExportFactory.java:493)
	at eu.isas.peptideshaker.gui.export.FeaturesExportDialog$13.run(FeaturesExportDialog.java:577)

I don't understand why are the modifications a problem for file exporting?

Thank you

**Comment by hbarsnes** [comment]
Hi! I'm afraid that this is a known issue with our modification mapping that can sometimes occur. It has however been fixed and a new version including this fix should be available soon. We just have to sort out some other related issues first. But @mvaudel will try to send you a beta version for testing as soon as possible.

**Comment by ClaSofMag** [comment]
That's great, thank you for clarifying me! I'll wait for the new version then :)

**Comment by hbarsnes** [comment]
A beta version that should fix this issue is now available for testing here: https://genesis.ugent.be/maven2/eu/isas/peptideshaker/PeptideShaker/3.0.0-beta/PeptideShaker-3.0.0-beta.zip

Note that you will have to reprocess the data in PeptideShaker, i.e. you cannot open old PeptideShaker projects directly.

Please let us know if this new version solves the modification issues you were experiencing?
