### ISSUE TITLE
Error when opening MS Amanda files: Two modifications found

### ISSUE THREAD

**Issue by elrubio** [compomics/peptide-shaker#526]
I receive this error when loading MS Amanda result files created with SearchGUI:

```
[...]
File import completed. 496590 first hits imported (6689561 total) from 579600 spectra.
[496177 first hits passed the initial filtering]
Computing assumptions probabilities.
Saving assumptions probabilities, selecting best match, scoring modification localization.

Importing Data Canceled!
An error occurred: Two modifications found (Acetylation of protein N-term and Formylation of T) at site 0 of peptide ENVLTQSPAIMSASPGEK.
Please contact the developers (https://github.com/compomics/peptide-shaker/issues).
```
Debug log:
```
Sat Sep 30 21:34:11 CEST 2023: PeptideShaker version 3.0.0.
Memory given to the Java virtual machine: 8489271296.
Total amount of memory in the Java virtual machine: 134217728.
Free memory: 113812400.
Java version: 20.0.2.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Amazon.com Inc.
java.version: 20.0.2
os.name: Windows 11
memory: 56.5/134.2
processors available: 12
useCommandThread: false
java.lang.IllegalArgumentException: Two modifications found (Acetylation of protein N-term and Formylation of T) at site 0 of peptide ENVLTQSPAIMSASPGEK.
	at com.compomics.util.experiment.biology.proteins.Peptide.getIndexedVariableModifications(Peptide.java:413)
	at com.compomics.util.experiment.biology.ions.IonFactory.getFragmentIons(IonFactory.java:241)
	at com.compomics.util.experiment.identification.modification.scores.PhosphoRS.getPossiblePeptideFragments(PhosphoRS.java:1036)
	at com.compomics.util.experiment.identification.modification.scores.PhosphoRS.getSequenceProbabilities(PhosphoRS.java:256)
	at eu.isas.peptideshaker.ptm.ModificationLocalizationScorer.attachProbabilisticScore(ModificationLocalizationScorer.java:287)
	at eu.isas.peptideshaker.ptm.ModificationLocalizationScorer.scorePTMs(ModificationLocalizationScorer.java:453)
	at eu.isas.peptideshaker.processing.PsmProcessorRunnable.processPsm(PsmProcessorRunnable.java:205)
	at eu.isas.peptideshaker.processing.PsmProcessorRunnable.run(PsmProcessorRunnable.java:151)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)
```

MS Amanda search settings:

```
  <search_settings>
    <enzyme specificity="FULL">Trypsin (no P rule)</enzyme>
    <missed_cleavages>2</missed_cleavages>
    <modifications>
      <modification nterm="True" protein="True" maxoccurrences="1">Acetyl( )</modification>
      <modification>Carbamidomethyl(C)</modification>
      <modification>Formyl(S)</modification>
      <modification>Formyl(T)</modification>
      <modification nterm="True" protein="True" maxoccurrences="1">Formyl( )</modification>
      <modification>Oxidation(M)</modification>
      <modification nterm="True" maxoccurrences="1">Glu->pyro-Glu(E)</modification>
      <modification nterm="True" maxoccurrences="1">Gln->pyro-Glu(Q)</modification>
    </modifications>
    <instrument>b, y</instrument>
    <ms1_tol unit="PPM">2</ms1_tol>
    <ms2_tol unit="DA">0.02</ms2_tol>
    <max_rank>10</max_rank>
    <generate_decoy>False</generate_decoy>
    <PerformDeisotoping>True</PerformDeisotoping>
    <MaxNoModifs>3</MaxNoModifs>
    <MaxNoDynModifs>5</MaxNoDynModifs>
    <MaxNumberModSites>6</MaxNumberModSites>
    <MaxNumberNeutralLoss>1</MaxNumberNeutralLoss>
    <MaxNumberNeutralLossModifications>2</MaxNumberNeutralLossModifications>
    <MinimumPepLength>7</MinimumPepLength>
    <MaximumPepLength>30</MaximumPepLength>
    <ReportBothBestHitsForTD>True</ReportBothBestHitsForTD>
    <MaxAllowedChargeState>+2</MaxAllowedChargeState>
    <MinimumPeakDepth>1</MinimumPeakDepth>
    <MaximumPeakDepth>10</MaximumPeakDepth>
  </search_settings>
```

I can provide the file(s) privately if required.

**Comment by mvaudel** [comment]
Hi,

Thank you for contacting us on this. It is unclear to me how the `Formylation of T` ends up on the N-terminus. Would it be possible to share the data with us? We will of course handle them privately.

Many thanks for your help,

Marc
