### ISSUE TITLE
PeptideShaker issue - failed to load SearchGUI results 

### ISSUE THREAD

**Issue by mryanshi** [compomics/peptide-shaker#527]
Hi, I am a new user of SearchGUI and PeptideShaker. I ran into issues with loading data to PeptideShaker lately. Here is what the log says:

# ------------------------------------------------------------------
# PeptideShaker 3.0.1 Report File
#
# Originally saved by: i116gast @ I116LAB07
#                  on: 03 Nov 2023, 11:17
#                  as: Importing data canceled
# ------------------------------------------------------------------

Fri Nov 03 11:14:58 CET 2023        Import process for T parva

Fri Nov 03 11:14:59 CET 2023        Importing sequences from NCBI_Theileria_parva_tx333668_8112_231103_concatenated_target_decoy.fasta.
Fri Nov 03 11:15:05 CET 2023        Importing gene mappings.
Fri Nov 03 11:15:06 CET 2023        Establishing local database connection.
Fri Nov 03 11:15:06 CET 2023        Reading identification files.
Fri Nov 03 11:15:06 CET 2023        Parsing 2303047_Tparva_AP.comet.pep.xml.gz.
Fri Nov 03 11:15:12 CET 2023        Checking spectra for 2303047_Tparva_AP.comet.pep.xml.gz.
Fri Nov 03 11:15:12 CET 2023        Spectrum with title '**controllerType=0 controllerNumber=1 scan=2422**' in file named '2303047_Tparva_AP' required to parse '2303047_Tparva_AP.comet.pep.xml.gz' not found.

Fri Nov 03 11:15:12 CET 2023        Importing Data Canceled!

This happened on results generated by different search engines of SearchGUI. Any solutions to fix it?

**Comment by mryanshi** [comment]
More detrails about this issue:


Thu Nov 02 19:08:29 CET 2023: PeptideShaker version 3.0.1.
Memory given to the Java virtual machine: 3817865216.
Total amount of memory in the Java virtual machine: 128974848.
Free memory: 86467352.
Java version: 1.8.0_391.
jshortcut.dll loaded via tmp generated pathname: C:\Users\i116gast\AppData\Local\Temp\jshortcut-2898279363260973678.dll
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.8.0_391
os.name: Windows 10
memory: 67.8/163.1
processors available: 4
useCommandThread: false
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at eu.isas.peptideshaker.gui.pride.ProjectsFilterDialog.<init>(ProjectsFilterDialog.java:72)
	at eu.isas.peptideshaker.gui.pride.PrideReshakeGUI.findMenuItemActionPerformed(PrideReshakeGUI.java:1583)
	at eu.isas.peptideshaker.gui.pride.PrideReshakeGUI.projectSearchLabelMouseReleased(PrideReshakeGUI.java:1753)
	at eu.isas.peptideshaker.gui.pride.PrideReshakeGUI.access$1800(PrideReshakeGUI.java:102)
	at eu.isas.peptideshaker.gui.pride.PrideReshakeGUI$11.mouseReleased(PrideReshakeGUI.java:896)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
https://www.ebi.ac.uk/pride/ws/archive/project/count
org.springframework.web.client.HttpClientErrorException$NotFound: 404 : "{<EOL>  "timestamp" : 1698948857867,<EOL>  "status" : 404,<EOL>  "error" : "Not Found",<EOL>  "message" : "No message available",<EOL>  "path" : "/pride/ws/archive/v2/project/count"<EOL>}"
	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:113)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:168)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:122)
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:819)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:777)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:711)
	at org.springframework.web.client.RestTemplate.getForEntity(RestTemplate.java:361)
	at eu.isas.peptideshaker.gui.pride.PrideReshakeGUI$33.run(PrideReshakeGUI.java:2523)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at eu.isas.peptideshaker.gui.pride.ProjectsFilterDialog.<init>(ProjectsFilterDialog.java:72)
	at eu.isas.peptideshaker.gui.pride.PrideReshakeGUI.findMenuItemActionPerformed(PrideReshakeGUI.java:1583)
	at eu.isas.peptideshaker.gui.pride.PrideReshakeGUI.projectSearchLabelMouseReleased(PrideReshakeGUI.java:1753)
	at eu.isas.peptideshaker.gui.pride.PrideReshakeGUI.access$1800(PrideReshakeGUI.java:102)
	at eu.isas.peptideshaker.gui.pride.PrideReshakeGUI$11.mouseReleased(PrideReshakeGUI.java:896)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
https://www.ebi.ac.uk/pride/ws/archive/project/count
org.springframework.web.client.HttpClientErrorException$NotFound: 404 : "{<EOL>  "timestamp" : 1698948884364,<EOL>  "status" : 404,<EOL>  "error" : "Not Found",<EOL>  "message" : "No message available",<EOL>  "path" : "/pride/ws/archive/v2/project/count"<EOL>}"
	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:113)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:168)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:122)
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:819)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:777)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:711)
	at org.springframework.web.client.RestTemplate.getForEntity(RestTemplate.java:361)
	at eu.isas.peptideshaker.gui.pride.PrideReshakeGUI$33.run(PrideReshakeGUI.java:2523)


Thu Nov 02 19:15:17 CET 2023: PeptideShaker version 3.0.1.
Memory given to the Java virtual machine: 3817865216.
Total amount of memory in the Java virtual machine: 128974848.
Free memory: 87067272.
Java version: 1.8.0_391.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.8.0_391
os.name: Windows 10
memory: 66.9/163.1
processors available: 4
useCommandThread: false
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 11 >= 3
	at java.util.Vector.elementAt(Unknown Source)
	at javax.swing.table.DefaultTableColumnModel.getColumn(Unknown Source)
	at javax.swing.plaf.basic.BasicTableHeaderUI.paint(Unknown Source)
	at javax.swing.plaf.synth.SynthTableHeaderUI.paint(Unknown Source)
	at javax.swing.plaf.synth.SynthTableHeaderUI.update(Unknown Source)
	at javax.swing.JComponent.paintComponent(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintToOffscreen(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
	at javax.swing.RepaintManager.paint(Unknown Source)
	at javax.swing.JComponent._paintImmediately(Unknown Source)
	at javax.swing.JComponent.paintImmediately(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.access$1200(Unknown Source)
	at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.WaitDispatchSupport$2.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)


Thu Nov 02 19:20:09 CET 2023: PeptideShaker version 3.0.1.
Memory given to the Java virtual machine: 3817865216.
Total amount of memory in the Java virtual machine: 128974848.
Free memory: 86449528.
Java version: 1.8.0_391.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.8.0_391
os.name: Windows 10
memory: 67.8/163.1
processors available: 4
useCommandThread: false


Thu Nov 02 19:42:51 CET 2023: PeptideShaker version 3.0.1.
Memory given to the Java virtual machine: 3817865216.
Total amount of memory in the Java virtual machine: 128974848.
Free memory: 86455104.
Java version: 1.8.0_391.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.8.0_391
os.name: Windows 10
memory: 66.1/163.1
processors available: 4
useCommandThread: false


Thu Nov 02 19:47:38 CET 2023: PeptideShaker version 3.0.1.
Memory given to the Java virtual machine: 3817865216.
Total amount of memory in the Java virtual machine: 128974848.
Free memory: 86505464.
Java version: 1.8.0_391.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.8.0_391
os.name: Windows 10
memory: 67.4/163.1
processors available: 4
useCommandThread: false


Thu Nov 02 19:57:33 CET 2023: PeptideShaker version 3.0.1.
Memory given to the Java virtual machine: 3817865216.
Total amount of memory in the Java virtual machine: 128974848.
Free memory: 113723896.
Java version: 1.8.0_391.


Thu Nov 02 20:01:11 CET 2023: PeptideShaker version 3.0.1.
Memory given to the Java virtual machine: 3817865216.
Total amount of memory in the Java virtual machine: 128974848.
Free memory: 86417880.
Java version: 1.8.0_391.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.8.0_391
os.name: Windows 10
memory: 66.9/163.1
processors available: 4
useCommandThread: false


Fri Nov 03 11:14:26 CET 2023: PeptideShaker version 3.0.1.
Memory given to the Java virtual machine: 3817865216.
Total amount of memory in the Java virtual machine: 128974848.
Free memory: 86457096.
Java version: 1.8.0_391.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.8.0_391
os.name: Windows 10
memory: 66.7/163.1
processors available: 4
useCommandThread: false


Fri Nov 03 11:24:09 CET 2023: PeptideShaker version 3.0.1.
Memory given to the Java virtual machine: 3817865216.
Total amount of memory in the Java virtual machine: 128974848.
Free memory: 86462168.
Java version: 1.8.0_391.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.8.0_391
os.name: Windows 10
memory: 66.7/163.1
processors available: 4
useCommandThread: false


Fri Nov 03 11:25:46 CET 2023: PeptideShaker version 3.0.1.
Memory given to the Java virtual machine: 11185160192.
Total amount of memory in the Java virtual machine: 128974848.
Free memory: 86264400.
Java version: 1.8.0_391.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.8.0_391
os.name: Windows 10
memory: 66.4/163.1
processors available: 4
useCommandThread: false


Command line: 
"C:\Program Files\Java\jre-1.8\bin\java" -splash:resources\conf\peptide-shaker-splash.png -Xms128M -Xmx12000M -cp "C:\TEMP\PeptideShaker-3.0.1\PeptideShaker-3.0.1.jar" eu.isas.peptideshaker.gui.PeptideShakerGUI 



Fri Nov 03 11:26:44 CET 2023: PeptideShaker version 3.0.1.
Memory given to the Java virtual machine: 11185160192.
Total amount of memory in the Java virtual machine: 128974848.
Free memory: 86918768.
Java version: 1.8.0_391.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.8.0_391
os.name: Windows 10
memory: 67.5/163.1
processors available: 4
useCommandThread: false
Process exitValue: 0



Fri Nov 03 11:34:06 CET 2023: PeptideShaker version 3.0.1.
Memory given to the Java virtual machine: 11185160192.
Total amount of memory in the Java virtual machine: 128974848.
Free memory: 86502848.
Java version: 1.8.0_391.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.8.0_391
os.name: Windows 10
memory: 67.5/163.1
processors available: 4
useCommandThread: false


Fri Nov 03 11:52:20 CET 2023: PeptideShaker version 3.0.1.
Memory given to the Java virtual machine: 11185160192.
Total amount of memory in the Java virtual machine: 128974848.
Free memory: 86487128.
Java version: 1.8.0_391.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.8.0_391
os.name: Windows 10
memory: 67.3/163.1
processors available: 4
useCommandThread: false


Fri Nov 03 11:56:04 CET 2023: PeptideShaker version 3.0.1.
Memory given to the Java virtual machine: 11185160192.
Total amount of memory in the Java virtual machine: 128974848.
Free memory: 86442328.
Java version: 1.8.0_391.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.8.0_391
os.name: Windows 10
memory: 66.3/163.1
processors available: 4
useCommandThread: false


Fri Nov 03 12:00:08 CET 2023: PeptideShaker version 3.0.1.
Memory given to the Java virtual machine: 11185160192.
Total amount of memory in the Java virtual machine: 128974848.
Free memory: 86477440.
Java version: 1.8.0_391.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.8.0_391
os.name: Windows 10
memory: 65.9/163.1
processors available: 4
useCommandThread: false
Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError: java.nio.MappedByteBuffer.position(I)Ljava/nio/MappedByteBuffer;
	at com.compomics.util.experiment.io.mass_spectrometry.cms.CmsFileReader.getSpectrum(CmsFileReader.java:189)
	at com.compomics.util.experiment.io.mass_spectrometry.cms.CmsFileReader.getSpectrum(CmsFileReader.java:253)
	at com.compomics.util.experiment.io.mass_spectrometry.MsFileHandler.getSpectrum(MsFileHandler.java:253)
	at eu.isas.peptideshaker.gui.tabpanels.OverviewPanel.updateSpectrum(OverviewPanel.java:4802)
	at eu.isas.peptideshaker.gui.tabpanels.OverviewPanel.psmTableMouseReleased(OverviewPanel.java:2069)
	at eu.isas.peptideshaker.gui.tabpanels.OverviewPanel.updateSelection(OverviewPanel.java:6701)
	at eu.isas.peptideshaker.gui.tabpanels.OverviewPanel.updatePsmSelection(OverviewPanel.java:5151)
	at eu.isas.peptideshaker.gui.tabpanels.OverviewPanel.access$9200(OverviewPanel.java:102)
	at eu.isas.peptideshaker.gui.tabpanels.OverviewPanel$72.run(OverviewPanel.java:2235)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)


Fri Nov 03 13:28:49 CET 2023: PeptideShaker version 3.0.1.
Memory given to the Java virtual machine: 11185160192.
Total amount of memory in the Java virtual machine: 128974848.
Free memory: 86955896.
Java version: 1.8.0_391.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.8.0_391
os.name: Windows 10
memory: 66.1/163.1
processors available: 4
useCommandThread: false

**Comment by hbarsnes** [comment]
The problem seems to be that you are using a rather old Java version. So if you update your Java version the problem should hopefully be fixed. You can update your Java version here: https://adoptium.net/temurin/releases
