### ISSUE TITLE
PeptideShaker Processing Canceled.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [compomics/peptide-shaker#69]
```
> What steps will reproduce the problem?
Rerunning the command: java -cp PeptideShaker-0.37.7.jar 
eu.isas.peptideshaker.cmd.PeptideShakerCLI ...

> What is the expected output? What do you see instead?
I'm running PeptideShakerCLI mode, to obtain *.cps output, as the GUI is not 
that handy on a server. Unfortunately the tools cancels the processing, so I 
don't have an output yet.

> What version of the product are you using? On what operating system?
PeptideShaker-0.37.7 on Linux based virtual machine with Ubuntu 14.04.1.

> Please provide any additional information below.
I've run SearchGUI with Uniprot database, next I've run PeptideShaker, I 
exported unassigned spectra and rerun SearchGUI with customised database. Then 
I cannot make PeptideShaker run. First I had memory issues so I increased it to 
10GB.

> If the reported issue resulted in the tool crashing, please
> also upload the file called PeptideShaker.log (found in the
> PeptideShaker-X.Y.Z\resources folder).

PeptideShaker.log
Fri Apr 17 09:15:09 CEST 2015: PeptideShaker version 0.37.7.
Memory given to the Java virtual machine: 3817865216.
Total amount of memory in the Java virtual machine: 129499136.
Free memory: 115618224.
Java version: 1.7.0_75.
java.lang.NullPointerException
        at eu.isas.peptideshaker.gui.PeptideShakerGUI$93.run(PeptideShakerGUI.java:4879)
java.lang.NullPointerException
        at eu.isas.peptideshaker.gui.PeptideShakerGUI$93.run(PeptideShakerGUI.java:4879)


Command line:
/usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java 
-splash:resources/conf/peptide-shaker-splash.png -Xms128M -Xmx10000M -cp 
/home/gosia/tools/PeptideShaker-0.37.7/PeptideShaker-0.37.7.jar 
eu.isas.peptideshaker.gui.PeptideShakerGUI



Fri Apr 17 09:18:46 CEST 2015: PeptideShaker version 0.37.7.
Memory given to the Java virtual machine: 9320792064.
Total amount of memory in the Java virtual machine: 129499136.
Free memory: 115637744.
Java version: 1.7.0_75.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.7.0_75
os.name: Linux
memory: 33.4/129.0
processors available: 4
useCommandThread: false
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.7.0_75
os.name: Linux
memory: 38.8/129.5
processors available: 4
useCommandThread: false


I can also send stderr file.



```

Original issue reported on code.google.com by `komor.go...@gmail.com` on 17 Apr 2015 at 9:39

**Comment by hbarsnes** [comment]
This issue should have been fixed in later versions of PeptideShaker. If this is not the case, please let us know and we'll reopen the issue.
