### ISSUE TITLE
Importing data canceled

### ISSUE THREAD

**Issue by GoogleCodeExporter** [compomics/peptide-shaker#83]
```
> What steps will reproduce the problem?
Attempting to load the zip archive from SearchGUI 1.28.1 in PeptideShaker 
0.40.1.  Search was 6 spectra files (thermo files converted to mgf via 
msconvert.exe) against a human database using X!tandem, myrimatch, OMSSA, and 
Comet.  Data import ends up cancelled by PeptideShaker whether I have SearchGUI 
call up PeptideShaker or if I open the zip file separately in PeptideShaker

> What is the expected output? What do you see instead?
I would expect to see the files opened.  Instead, I see
"
An error occurred: Error while loading spectrum 
QE_IA_QQTGG_MG132_BR3_TR2.1928.1928.6 of file QE_IA_QQTGG_MG132_BR3_TR2.mgf.
Wed Jun 10 14:45:18 CDT 2015        Please contact the developers 
(http://code.google.com/p/peptide-shaker/issues/list).

Wed Jun 10 14:45:18 CDT 2015        Importing Data Canceled!"

On the main screen and 
"
java.lang.IllegalArgumentException: Error while loading spectrum 
QE_IA_QQTGG_MG132_BR3_TR2.1928.1928.6 of file QE_IA_QQTGG_MG132_BR3_TR2.mgf.
	at com.compomics.util.experiment.massspectrometry.SpectrumFactory.getSpectrum(SpectrumFactory.java:794)
	at com.compomics.util.experiment.massspectrometry.SpectrumFactory.getSpectrum(SpectrumFactory.java:791)
	at com.compomics.util.experiment.massspectrometry.SpectrumFactory.getSpectrum(SpectrumFactory.java:791)
	at com.compomics.util.experiment.massspectrometry.SpectrumFactory.getSpectrum(SpectrumFactory.java:791)
	at com.compomics.util.experiment.massspectrometry.SpectrumFactory.getSpectrum(SpectrumFactory.java:791)
	at com.compomics.util.experiment.massspectrometry.SpectrumFactory.getSpectrum(SpectrumFactory.java:791)
	at com.compomics.util.experiment.massspectrometry.SpectrumFactory.getSpectrum(SpectrumFactory.java:791)
	at com.compomics.util.experiment.massspectrometry.SpectrumFactory.getSpectrum(SpectrumFactory.java:791)
	at com.compomics.util.experiment.massspectrometry.SpectrumFactory.getSpectrum(SpectrumFactory.java:791)
	at com.compomics.util.experiment.massspectrometry.SpectrumFactory.getSpectrum(SpectrumFactory.java:791)
	at com.compomics.util.experiment.massspectrometry.SpectrumFactory.getSpectrum(SpectrumFactory.java:791)
	at com.compomics.util.experiment.massspectrometry.SpectrumFactory.getSpectrum(SpectrumFactory.java:791)
	at com.compomics.util.experiment.massspectrometry.SpectrumFactory.getSpectrum(SpectrumFactory.java:791)
	at com.compomics.util.experiment.massspectrometry.SpectrumFactory.getSpectrum(SpectrumFactory.java:791)
	at com.compomics.util.experiment.massspectrometry.SpectrumFactory.getSpectrum(SpectrumFactory.java:791)
	at com.compomics.util.experiment.massspectrometry.SpectrumFactory.getSpectrum(SpectrumFactory.java:723)
	at com.compomics.util.experiment.massspectrometry.SpectrumFactory.getSpectrum(SpectrumFactory.java:741)
	at eu.isas.peptideshaker.scoring.psm_scoring.BestMatchSelection.getBestHit(BestMatchSelection.java:593)
	at eu.isas.peptideshaker.fileimport.PsmImporter.importPsm(PsmImporter.java:822)
	at eu.isas.peptideshaker.fileimport.PsmImporter.access$000(PsmImporter.java:62)
	at eu.isas.peptideshaker.fileimport.PsmImporter$PsmImporterRunnable.run(PsmImporter.java:1184)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
"
In the bug report log.  


> What version of the product are you using? On what operating system?
PeptideShaker 0.40.1 in Windows Server 2008 R2 Enterprise, SP1.  SearchGUI is 
1.28.1

> Please provide any additional information below.


> If the reported issue resulted in the tool crashing, please
> also upload the file called PeptideShaker.log (found in the
> PeptideShaker-X.Y.Z\resources folder).

```

Original issue reported on code.google.com by `lparson...@gmail.com` on 10 Jun 2015 at 7:56

**Comment by hbarsnes** [comment]
Hi,

I never heard back from you regarding this issue, so I will assume that you managed to solve the problem on your own?

If this is not the case, then please let me know and I'll reopen the issue.

Best regards,
Harald
