### ISSUE TITLE
ReportCLI : The FASTA file was not found. Please locate it using the GUI

### ISSUE THREAD

**Issue by cdlawless** [compomics/peptide-shaker#95]
Hi

Trying to get peptide/protein reports out of the PeptideShaker project. I ran a search using SearchCLI with options to zip results, mgfs etc. I then use this zip file for PeptideShaker using PeptideShakerCLI. 

When I come to export reports from the PeptideShaker project files, I get the above error about the fasta file. Is there no way of telling PeptideShakerCLI where to locate the fasta file (etc.)

Regards

Craig

**Comment by mvaudel** [comment]
Hi Craig,

Would it be possible to share with us the different command lines used? I see nothing wrong with your setup so the files should be included in the zip package.

Best regards,

Marc

**Comment by cdlawless** [comment]
No problem.

SearchCLI command:

java -Xms4096M -Xmx131072m -cp /mnt/fls01-home01/mjfidcl2/scratch/SearchGUI/SearchGUI-2.0.4/SearchGUI-2.0.4.jar eu.isas.searchgui.cmd.SearchCLI -spectrum_files "/mnt/lustre/scratch/mjfidcl2
/DDIP/TimePoints/mgfs_0_2" -output_folder /mnt/lustre/scratch/mjfidcl2/DDIP/TimePoints/output_0_2/ -id_params /mnt/lustre/scratch/mjfidcl2/DDIP/TimePoints/params/GUI-2.0.4_timepoints_nophos
ph.par -output_option 0 -output_data 1 -output_date 1 -mgf_splitting 2000 -temp_folder /mnt/lustre/scratch/mjfidcl2/DDIP/TimePoints/temp -xtandem 1 -msgf 1 -omssa 1 -myrimatch 1 -comet 1 -t
ide 0 -ms_amanda 0 -andromeda 0 -xtandem_folder /mnt/lustre/scratch/mjfidcl2/DDIP/TimePoints/temp -myrimatch_folder /mnt/lustre/scratch/mjfidcl2/DDIP/TimePoints/temp -comet_folder /mnt/lust
re/scratch/mjfidcl2/DDIP/TimePoints/temp -omssa_folder /mnt/lustre/scratch/mjfidcl2/DDIP/TimePoints/temp -msgf_folder /mnt/lustre/scratch/mjfidcl2/DDIP/TimePoints/temp

PeptideShakerCLI command:

java -Xms1024m -Xmx262144m -cp /scratch/mjfidcl2/PeptideShaker-1.0.4/PeptideShaker-1.0.4.jar eu.isas.peptideshaker.cmd.PeptideShakerCLI -experiment TP_0_2 -sample TP_0_2_sample -replicate 1
 -identification_files "/scratch/mjfidcl2/DDIP/TimePoints/SearchGUI_results/outputs_0_2/2015-9-16_0.15.5_searchgui_out.zip" -out "./TP_0_2.cpsx" -ptm_score 1


ReportCLI Command:
java -Xms1024m -Xmx262144m -cp /scratch/mjfidcl2/PeptideShaker-1.0.4/PeptideShaker-1.0.4.jar eu.isas.peptideshaker.cmd.ReportCLI -in "./TP_0_2.cps" -out_reports "../SearchGUI_results/output
_0_2/" -reports "0,3, 4"


Craig Lawless
---------------------------------------
Postdoctoral Research Associate
Faculty of Life Sciences
Rm B.1071 Michael-Smith
Oxford Road
Manchester
M13 9PT
TEL:(+44)0161 275 1680
--------------------------------------

________________________________

**Comment by mvaudel** [comment]
Many thanks, it seems that the mgf and fasta files are not included in the PeptideShaker project. Can you try to add -zip "myPath/myFile.zip" to the PeptideShakerCLI command, and pass this file as -in "myPath/myFile.zip" to the ReportCLI command?

**Comment by cdlawless** [comment]
Hi Marc

I had just set that running as you replied. I will let you know that outcome.

Many thanks

Craig Lawless
---------------------------------------
Postdoctoral Research Associate
Faculty of Life Sciences
Rm B.1071 Michael-Smith
Oxford Road
Manchester
M13 9PT
TEL:(+44)0161 275 1680
--------------------------------------

________________________________

**Comment by mvaudel** [comment]
Hi again,

Great, eager to know whether it worked. Please note that ReportCLI is essentially made for report generation on existing projects. You can also export the reports upon creation of the projects, for this, append the ReportCLI arguments directly to the PeptideShakerCLI. Something like:

```
java -Xms1024m -Xmx262144m -cp /scratch/mjfidcl2/PeptideShaker-1.0.4/PeptideShaker-1.0.4.jar eu.isas.peptideshaker.cmd.PeptideShakerCLI -experiment TP_0_2 -sample TP_0_2_sample -replicate 1
 -identification_files "/scratch/mjfidcl2/DDIP/TimePoints/SearchGUI_results/outputs_0_2/2015-9-16_0.15.5_searchgui_out.zip" -out "./TP_0_2.cpsx" -ptm_score 1 -out_reports "../SearchGUI_results/output_0_2/" -reports "0,3, 4"
```

You will have one less command to maintain and the generation of reports will be faster :)

Best regards,

Marc

**Comment by cdlawless** [comment]
Hi Marc

No success using the zip option / report output options with PeptideShakerCLI.

First the report indexes are different than those described on the ReportCLI page on github:

Github:
0: Certificate of Analysis,
1: Default Hierarchical Report,
2: Default PSM Report,
3: Default Peptide Report,
4: Default Protein Report,
5-n: Your own custom reports.

Actual:
0: Certificate of Analysis,
1: Default Hierarchical Report,
2: Default PSM Phosphorylation Report,
3: Default PSM Report,
4: Default Peptide Phosphorylation Report,
5: Default Peptide Report,
6: Default Protein Phosphorylation Report,
7: Default Protein Report

Second using the -out_reports & -reports options with PeptideShaker CLI give the following log/error:
Command:

java -Xms1024m -Xmx262144m -cp /scratch/mjfidcl2/PeptideShaker-1.0.4/PeptideShaker-1.0.4.jar eu.isas.peptideshaker.cmd.PeptideShakerCLI -experiment TP_14_16 -sample TP_14_16_sample -replica
te 1 -identification_files "/scratch/mjfidcl2/DDIP/TimePoints/SearchGUI_results/output_14_16/2015-9-16_14.22.23_searchgui_out.zip" -out "./TP_14_16.cpsx" -ptm_score 1 -out_reports "../Searc
hGUI_results/output_14_16/" -reports "0,3, 4" -zip "./TP_14_16.zip"

Report log:
Wed Oct 21 14:18:03 BST 2015 Starting report export.
Wed Oct 21 14:18:03 BST 2015 Exporting. Please Wait...
Wed Oct 21 14:18:03 BST 2015 An error occurred while exporting the Default PSM Report.
Wed Oct 21 14:18:03 BST 2015 Exporting. Please Wait...
Wed Oct 21 14:18:03 BST 2015 An error occurred while exporting the Default Peptide Phosphorylation Report.

Error log:
java.sql.SQLSyntaxErrorException: Table/View '24072015_Stages_14-16h_R4.mgf_psms' does not exist.
        at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
        at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
        at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
        at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
        at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedStatement.execute(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedStatement.executeQuery(Unknown Source)
        at com.compomics.util.db.ObjectsDB.loadObjects(ObjectsDB.java:615)
        at com.compomics.util.experiment.identification.IdentificationDB.loadSpectrumMatches(IdentificationDB.java:841)
        at com.compomics.util.experiment.identification.Identification.loadSpectrumMatches(Identification.java:241)
        at com.compomics.util.experiment.identification.matches_iterators.PsmIterator.checkBuffer(PsmIterator.java:262)
        at com.compomics.util.experiment.identification.matches_iterators.PsmIterator.next(PsmIterator.java:231)
        at eu.isas.peptideshaker.export.sections.PsPsmSection.writeSection(PsPsmSection.java:179)
        at eu.isas.peptideshaker.export.PSExportFactory.writeExport(PSExportFactory.java:300)
        at eu.isas.peptideshaker.cmd.CLIMethods.exportReport(CLIMethods.java:294)
        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:299)
        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:1026)
Caused by: java.sql.SQLException: Table/View '24072015_Stages_14-16h_R4.mgf_psms' does not exist.
        at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
        at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
        ... 18 more
Caused by: ERROR 42X05: Table/View '24072015_Stages_14-16h_R4.mgf_psms' does not exist.
        at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
        at org.apache.derby.impl.sql.compile.FromBaseTable.bindTableDescriptor(Unknown Source)
        at org.apache.derby.impl.sql.compile.FromBaseTable.bindNonVTITables(Unknown Source)
        at org.apache.derby.impl.sql.compile.FromList.bindTables(Unknown Source)
        at org.apache.derby.impl.sql.compile.SelectNode.bindNonVTITables(Unknown Source)
        at org.apache.derby.impl.sql.compile.DMLStatementNode.bindTables(Unknown Source)
        at org.apache.derby.impl.sql.compile.DMLStatementNode.bind(Unknown Source)
        at org.apache.derby.impl.sql.compile.CursorNode.bindStatement(Unknown Source)
        at org.apache.derby.impl.sql.GenericStatement.prepMinion(Unknown Source)
        at org.apache.derby.impl.sql.GenericStatement.prepare(Unknown Source)
        at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.prepareInternalStatement(Unknown Source)
        ... 12 more
java.sql.SQLSyntaxErrorException: Table/View 'PEPTIDES' does not exist.
        at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
        at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
        at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
        at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
        at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedStatement.execute(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedStatement.executeQuery(Unknown Source)
        at com.compomics.util.db.ObjectsDB.loadObjects(ObjectsDB.java:615)
        at com.compomics.util.experiment.identification.IdentificationDB.loadPeptideMatches(IdentificationDB.java:963)
        at com.compomics.util.experiment.identification.Identification.loadPeptideMatches(Identification.java:312)
        at com.compomics.util.experiment.identification.matches_iterators.PeptideMatchesIterator.checkBuffer(PeptideMatchesIterator.java:194)
        at com.compomics.util.experiment.identification.matches_iterators.PeptideMatchesIterator.next(PeptideMatchesIterator.java:163)
        at eu.isas.peptideshaker.export.sections.PsPeptideSection.writeSection(PsPeptideSection.java:154)
        at eu.isas.peptideshaker.export.PSExportFactory.writeExport(PSExportFactory.java:291)
        at eu.isas.peptideshaker.cmd.CLIMethods.exportReport(CLIMethods.java:294)
        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:299)
        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:1026)
Caused by: java.sql.SQLException: Table/View 'PEPTIDES' does not exist.
        at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
        at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
        ... 18 more
Caused by: ERROR 42X05: Table/View 'PEPTIDES' does not exist.
        at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
        at org.apache.derby.impl.sql.compile.FromBaseTable.bindTableDescriptor(Unknown Source)
        at org.apache.derby.impl.sql.compile.FromBaseTable.bindNonVTITables(Unknown Source)
        at org.apache.derby.impl.sql.compile.FromList.bindTables(Unknown Source)
        at org.apache.derby.impl.sql.compile.SelectNode.bindNonVTITables(Unknown Source)
        at org.apache.derby.impl.sql.compile.DMLStatementNode.bindTables(Unknown Source)
        at org.apache.derby.impl.sql.compile.DMLStatementNode.bind(Unknown Source)
        at org.apache.derby.impl.sql.compile.CursorNode.bindStatement(Unknown Source)
        at org.apache.derby.impl.sql.GenericStatement.prepMinion(Unknown Source)
        at org.apache.derby.impl.sql.GenericStatement.prepare(Unknown Source)
        at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.prepareInternalStatement(Unknown Source)


The same/similar results are observed for all data for all timepoints (TP) 0_2, 2_4 etc etc..

I then tried to use the zipped peptideshaker output with reportCLI to generate the reports:

java -Xms4096M -Xmx8192m -cp ../../PeptideShaker/PeptideShaker-1.0.4/PeptideShaker-1.0.4.jar eu.isas.peptideshaker.cmd.ReportCLI -in "PeptideShaker/TP_14_16.zip" -out_reports "./" -reports "0"

I get this output:
Wed Oct 21 19:34:32 BST 2015 Unzipping TP_14_16.zip. Please Wait...
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
10% 90%
Wed Oct 21 19:34:44 BST 2015 An error occurred while reading: /mnt/lustre/scratch/mjfidcl2/DDIP/TimePoints/PeptideShaker/TP_14_16.zip. It looks like another instance of PeptideShaker is still connected to the file. Please close all instances of PeptideShaker and try again.
java.sql.SQLSyntaxErrorException: Table/View 'PEPTIDESHAKER_EXPERIMENT_SETTINGS' does not exist.
        at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
        at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
        at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
        at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
        at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedStatement.execute(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedStatement.executeQuery(Unknown Source)
        at com.compomics.util.db.ObjectsDB.retrieveObjectSynchronized(ObjectsDB.java:797)
        at com.compomics.util.db.ObjectsDB.retrieveObject(ObjectsDB.java:746)
        at eu.isas.peptideshaker.fileimport.CpsFileImporter.getPeptideShakerSettings(CpsFileImporter.java:78)
        at eu.isas.peptideshaker.utils.CpsParent.loadCpsFile(CpsParent.java:234)
        at eu.isas.peptideshaker.utils.CpsParent.loadCpsFromZipFile(CpsParent.java:167)
        at eu.isas.peptideshaker.cmd.ReportCLI.call(ReportCLI.java:104)
        at eu.isas.peptideshaker.cmd.ReportCLI.main(ReportCLI.java:319)
Caused by: java.sql.SQLException: Table/View 'PEPTIDESHAKER_EXPERIMENT_SETTINGS' does not exist.
        at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
        at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
        ... 15 more
Caused by: ERROR 42X05: Table/View 'PEPTIDESHAKER_EXPERIMENT_SETTINGS' does not exist.
        at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
        at org.apache.derby.impl.sql.compile.FromBaseTable.bindTableDescriptor(Unknown Source)
        at org.apache.derby.impl.sql.compile.FromBaseTable.bindNonVTITables(Unknown Source)
        at org.apache.derby.impl.sql.compile.FromList.bindTables(Unknown Source)
        at org.apache.derby.impl.sql.compile.SelectNode.bindNonVTITables(Unknown Source)
        at org.apache.derby.impl.sql.compile.DMLStatementNode.bindTables(Unknown Source)
        at org.apache.derby.impl.sql.compile.DMLStatementNode.bind(Unknown Source)
        at org.apache.derby.impl.sql.compile.CursorNode.bindStatement(Unknown Source)
        at org.apache.derby.impl.sql.GenericStatement.prepMinion(Unknown Source)
        at org.apache.derby.impl.sql.GenericStatement.prepare(Unknown Source)
        at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.prepareInternalStatement(Unknown Source)
        ... 9 more
Wed Oct 21 19:34:44 BST 2015 /mnt/lustre/scratch/mjfidcl2/DDIP/TimePoints/PeptideShaker/TP_14_16.zip successfuly loaded.
Wed Oct 21 19:34:44 BST 2015 An error occurred while loading the fasta file.
java.lang.NullPointerException
        at eu.isas.peptideshaker.utils.CpsParent.loadFastaFile(CpsParent.java:330)
        at eu.isas.peptideshaker.utils.CpsParent.loadFastaFile(CpsParent.java:307)
        at eu.isas.peptideshaker.cmd.ReportCLI.call(ReportCLI.java:133)
        at eu.isas.peptideshaker.cmd.ReportCLI.main(ReportCLI.java:319)


Checking the contents of TP_14_16.zip:

Archive:  TP_14_16.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
 20213760  10-21-2015 14:18   TP_14_16.cpsx
        0  10-21-2015 14:18   data/
 87080274  10-21-2015 14:18   data/augmented_nr_db_v1_concatenated_target_decoy.fasta
  3312980  10-21-2015 14:18   data/augmented_nr_db_v1_concatenated_target_decoy.fasta.cui
 30775216  10-21-2015 14:18   data/24072015_Stages_14-16h_R4.mgf
  1717174  10-21-2015 14:18   data/24072015_Stages_14-16h_R4.mgf.cui
  9171533  10-21-2015 14:18   data/24072015_Stages_14-16h_R2.mgf
   344265  10-21-2015 14:18   data/24072015_Stages_14-16h_R2.mgf.cui
 11206400  10-21-2015 14:18   data/24072015_Stages_14-16h_R3.mgf
   690268  10-21-2015 14:18   data/24072015_Stages_14-16h_R3.mgf.cui
 46633149  10-21-2015 14:18   data/24072015_Stages_14-16h_R1.mgf
  3104023  10-21-2015 14:18   data/24072015_Stages_14-16h_R1.mgf.cui
---------                     -------
214249042                     12 files


The contents appear to be correct but the paths do not seem to be pointing to the correct files.

Craig Lawless
---------------------------------------
Postdoctoral Research Associate
Faculty of Life Sciences
Rm B.1071 Michael-Smith
Oxford Road
Manchester
M13 9PT
TEL:(+44)0161 275 1680
--------------------------------------

________________________________

**Comment by mvaudel** [comment]
Hi again Craig,

On the report documentation, sorry, just noticed we did not update it, will do that right away.

Concerning the file and packaging, it looks like the file is fine, if you download it to your machine, can you open it using the GUI?

The problem seems to be that the tool somehow lost connection to its back-end database. This can happen (1) when running tools on a different server than the file and the connection drops, (2) if you have IO restrictions on where the tool is located or the user folder, or (3) when running different instances on PeptideShaker in the same time. In order to avoid privileges restrictions we recommend to use the -temp_folder "tempFolder" option in your command lines, with the tempFolder a temporary folder where the tool is allowed to write. The given temporary folder will then be used for all temporary files like indexes and the back-end database.

PeptideShakerCLI with the reports should work then, but please make sure that you are running the latest version as we have recently fixed an issue with the temporary files on some servers which might cause this error. I just noticed that the fix was not included in ReportCLI but it will be in the next release :)

Best regards and apologizes for the inconvenience,

Marc

**Comment by cdlawless** [comment]
Hi Marc

Have tried opening with GUI but I get error asking if it is still connected by another instance of PeptideShaker and then quits.

I'm not running multiple instances of PeptideShaker (I get errors immediately when I try to do that).

I run SearchGUI on one cluster (high CPU power) output as zip and transfer the zip file to a second cluster (v. high memory and IO speeds). There are no restrictions on IO where I work out of, it's my own high speed IO space directly connected to the cluster.

I tried downloading the lastest version of PeptideShaker, but I get a major.minor version 51.0 error (Exception in thread "main" java.lang.UnsupportedClassVersionError: com/compomics/util/gui/DummyFrame) . The available java on the clusters are 1.6.0, to get 1.7.0 installed is going to be a bit of an ask.

I'll try the tempfolder option and see if that works with the version I am using.


Craig Lawless
---------------------------------------
Postdoctoral Research Associate
Faculty of Life Sciences
Rm B.1071 Michael-Smith
Oxford Road
Manchester
M13 9PT
TEL:(+44)0161 275 1680
--------------------------------------

________________________________

**Comment by mvaudel** [comment]
Hi again,

The setup of using one cluster with high CPU for SearchGUI and another with
high IO/Memory for PeptideShaker is very smart. We are in the process of
releasing new versions supporting again java 1.6. If you can wait a couple
of days you will have better and more stable versions :)

Best regards,

Marc

2015-10-21 22:29 GMT+02:00 Craig Lawless <notifications@github.com>:

**Comment by mvaudel** [comment]
Hi Craig,

A new version was released (https://github.com/compomics/peptide-shaker 1.1.3), it should work on java 1.6, and should be more stable on servers. Can you try to run this new version with the temp_folder option?

Best regards,

Marc

**Comment by cdlawless** [comment]
Thanks Marc

I'll set this running straight away. I managed to get some of the 
experiments run on my local machine with v1.1.2, as I had 1.7 installed 
and it worked with the temp_folder option. I'll use the same option with 
v1.1.3 on the cluster.

Thanks again

Craig

On 22/10/2015 12:47, Marc Vaudel wrote:
>
> Hi Craig,
>
> A new version was released 
> (https://github.com/compomics/peptide-shaker 1.1.3), it should work on 
> java 1.6, and should be more stable on servers. Can you try to run 
> this new version with the temp_folder option?
>
> Best regards,
>
> Marc
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/compomics/peptide-shaker/issues/95#issuecomment-150196378>.
>

-- 
Craig Lawless
--------------------------------------------
Post-Doctoral Research Associate
Faculty of Life Sciences
University of Manchester
Manchester
M13 9PT

**Comment by hbarsnes** [comment]
Issue assumed solved by later releases of SearchGUI and PeptideShaker, and as part of the revision of the command lines. If this is not the case, please open a new issue explaining the current problems and we'll take it from there.
